---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: AIX 호스트 유틸리티는 AIX 호스트에 연결된 ONTAP 스토리지를 관리할 수 있도록 지원합니다. 
---
= AIX Host Utilities 7.0을 설치합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX 호스트 유틸리티는 AIX 호스트에 연결된 ONTAP 스토리지를 관리할 수 있도록 지원합니다.

AIX Host Utilities는 다음 프로토콜을 지원합니다.

* FC
* FCoE 를 참조하십시오
* iSCSI


AIX Host Utilities는 다음 환경을 지원합니다.

* AIX Microsoft MPIO(다중 경로 I/O)(기본 OS)
* PowerVM
+
PowerVM에 대한 자세한 내용은 IBM PowerVM Live Partition Mobility Red Book을 참조하십시오.



.시작하기 전에
* 안정적인 작업을 위해 전체 iSCSI, FC 또는 FCoE 구성이 지원되는지 확인하십시오.
+
를 사용하여 구성을 확인할 수 https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] 있습니다.

* 모든 FC 및 FCoE 이니시에이터에 대해 동적 추적이 활성화되어 있어야 합니다.



NOTE: NetApp AIX 호스트 유틸리티 소프트웨어 패키지는 에서 압축된 형식으로 `tar.gz file` 사용할 수 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["NetApp Support 사이트"^]있습니다. AIX MPIO를 ONTAP 스토리지와 함께 사용하는 동안 AIX 호스트 유틸리티 키트를 설치해야 합니다.

.단계
. 호스트에 로그인합니다.
+
** AIX 호스트에서 * root * 로 로그인합니다.
** PowerVM 호스트에서 * padmin * 으로 로그인한 다음 `oem_setup_env` 명령을 입력하여 루트 사용자가 됩니다.


. 로 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["NetApp Support 사이트"^] 이동하여 Host Utilities가 포함된 압축 파일을 호스트의 디렉토리에 다운로드합니다.
. 다운로드가 포함된 디렉터리로 이동합니다.
. 파일의 압축을 풀고 SAN Toolkit 소프트웨어 패키지의 압축을 풉니다.
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
파일의 압축을 풀 때 다음 디렉토리가 생성됩니다 `ntap_aix_host_utilities_7.0`. 이 디렉토리에는 MPIO, non_MPIO 또는 SAN_Tool_Kit 하위 디렉토리 중 하나가 포함되어 있습니다.

. AIX MPIO를 설치합니다.
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. SAN 툴킷을 설치합니다.
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. 호스트를 재부팅합니다.
. 설치를 확인합니다.
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. 소프트웨어 버전을 확인합니다.
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
.  `lbp_enabled`다음 명령을 실행하여 SCSI UNMAP 매개 변수가 ODM에 추가되었는지 확인합니다.
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== SAN 툴킷을 참조하십시오

AIX 호스트 유틸리티는 IBM AIX 호스트에 명령줄 툴킷을 제공하는 NetApp 호스트 소프트웨어입니다. 이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 설치됩니다. 이 키트는 를 제공합니다 `sanlun` 유틸리티를 사용하면 LUN 및 호스트 버스 어댑터(HBA)를 관리하는 데 도움이 됩니다. 를 클릭합니다 `sanlun` 명령을 실행하면 호스트에 매핑된 LUN에 대한 정보, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보가 반환됩니다.

* 예 *

다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
# sanlun lun show all
----
* 예제 출력 *

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: 이 툴킷은 모든 호스트 유틸리티 구성과 프로토콜에 공통적으로 적용됩니다. 따라서 모든 부품이 모든 설정에 적용되지 않습니다. 사용하지 않는 구성 요소는 시스템 성능에 영향을 주지 않습니다. SAN 툴킷은 AIX 및 PowerVM/VIOS OS 버전에서 지원됩니다
