---
sidebar: sidebar 
permalink: hu-hpux-sanlun-toolkit.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP 스토리지와 함께 HP-UX Host Utilities 6.0을 사용하는 방법을 설명합니다 
---
= ONTAP 스토리지용 SAN 툴킷에 대해 알아보세요
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HP-UX 호스트 유틸리티는 HP-UX 호스트에서 명령줄 툴킷을 제공하는 NetApp 호스트 소프트웨어입니다.  NetApp Host Utilities 패키지를 설치할 때 툴킷이 설치됩니다.  이 키트는 다음을 제공합니다. `sanlun` ONTAP LUN과 호스트 버스 어댑터를 관리하는 데 도움이 되는 유틸리티입니다.  그만큼 `sanlun` 이 명령은 호스트에 매핑된 LUN, 다중 경로, 이니시에이터 그룹을 만드는 데 필요한 정보에 대한 정보를 반환합니다.

다음 예에서, `sanlun lun show` 명령은 ONTAP LUN 정보를 반환합니다.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----
[NOTE]
====
이 SAN 툴킷은 모든 호스트 유틸리티 구성과 프로토콜에서 공통적으로 사용됩니다.  결과적으로 모든 구성 요소가 모든 구성에 적용되는 것은 아닙니다.  사용하지 않는 구성 요소는 시스템 성능에 영향을 미치지 않습니다.

SAN Toolkit은 AIX 및 PowerVM/VIOS OS 버전에서 지원됩니다.

====


== 다음 단계

link:hu_hpux_60_cmd.html["HP-UX 호스트 유틸리티 도구 사용에 대해 알아보세요"] .
