---
sidebar: sidebar 
permalink: hu-solaris-command-reference.html 
keywords: host utilities, unified, solaris, 8.0, netapp, ontap 
summary: ONTAP 과 함께 Solaris Host Utilities 8.0을 사용하는 방법을 설명합니다. 
---
= Solaris 호스트 유틸리티 명령을 사용하여 ONTAP 스토리지 구성을 확인합니다.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Host Utilities 도구를 사용하여 NetApp 스토리지 구성의 종단 간 유효성 검사를 수행하려면 Solaris Host Utilities 샘플 명령 참조를 사용할 수 있습니다.



== 호스트에 매핑된 모든 호스트 이니시에이터를 나열합니다

호스트에 매핑된 모든 호스트 이니시에이터 목록을 검색할 수 있습니다.

[source, cli]
----
sanlun fcp show adapter -v
----
[role="tabbed-block"]
====
.8.0
--
.Solaris Host Utilities 8.0에 대한 예를 보여주세요
[%collapsible]
=====
[listing]
----
adapter name:      qlc0
WWPN:              2100f4e9d40fe3e0
WWNN:              2000f4e9d40fe3e0
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c4

adapter name:      qlc1
WWPN:              2100f4e9d40fe3e1
WWNN:              2000f4e9d40fe3e1
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c5
----
=====
--
.6.2
--
.Solaris Host Utilities 6.2에 대한 예를 보여주세요.
[%collapsible]
=====
[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----
=====
--
====


== 호스트에 매핑된 모든 LUN을 나열합니다

호스트에 매핑된 모든 LUN 목록을 검색할 수 있습니다.

[source, cli]
----
sanlun lun show -p -v all
----
[role="tabbed-block"]
====
.8.0
--
.Solaris Host Utilities 8.0에 대한 예를 보여주세요
[%collapsible]
=====
[listing]
----

ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 21g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native

----
=====
--
.6.2
--
.Solaris Host Utilities 6.2에 대한 예를 보여주세요.
[%collapsible]
=====
[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----
=====
--
====


== 지정된 SVM에서 호스트에 매핑된 모든 LUN 나열/호스트에 매핑된 특정 LUN의 모든 특성 나열

특정 SVM에서 호스트에 매핑된 모든 LUN 목록을 검색할 수 있습니다.

[source, cli]
----
sanlun lun show -p -v <svm_name>
----
[role="tabbed-block"]
====
.8.0
--
.Solaris Host Utilities 8.0에 대한 예를 보여주세요
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 20g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native
----
=====
--
.6.2
--
.Solaris Host Utilities 6.2에 대한 예를 보여주세요.
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----
=====
--
====


== 호스트 디바이스 파일 이름별 ONTAP LUN 속성 나열

호스트 디바이스 파일 이름을 지정하여 모든 ONTAP LUN 속성 목록을 검색할 수 있습니다.

[source, cli]
----
sanlun lun show all
----
[role="tabbed-block"]
====
.8.0
--
.Solaris Host Utilities 8.0에 대한 예를 보여주세요
[%collapsible]
=====
[source, cli]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                /vol/test1/lun1                         /dev/rdsk/
c0t600A098038314B314E5D574632365A51d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc1            FCP      20g        cDOT
----
=====
--
.6.2
--
.Solaris Host Utilities 6.2에 대한 예를 보여주세요.
[%collapsible]
=====
[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----
=====
--
====