---
sidebar: sidebar 
permalink: hu-veritas-7x.html 
keywords: host utilities, veritas, infoscale, 7, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: Veritas Infoscale 7 시리즈 릴리스에 대한 ONTAP SAN 호스트 구성 설정에 대한 지침을 제공합니다 
---
= ONTAP 스토리지를 사용하여 FC, FCoE 및 iSCSI에 대해 Veritas Infoscale 7 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 소프트웨어는 ONTAP 스토리지에 연결된 Linux 호스트에 대한 관리 및 진단 도구를 제공합니다. Veritas Infoscale 7 for Oracle Linux(Red Hat 호환 커널 기반), Red Hat Enterprise Linux(RHEL), SUSE Linux Enterprise Server 호스트와 함께 Linux 호스트 유틸리티를 사용하면 ONTAP LUN을 사용하여 FC, FCoE, iSCSI 프로토콜 작업을 관리할 수 있습니다.



== 1단계: 필요에 따라 SAN 부팅을 활성화합니다

SAN 부팅을 사용하도록 호스트를 구성하여 배포를 단순화하고 확장성을 개선할 수 있습니다.

.시작하기 전에
* 를 사용하여 link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^]Linux OS, 호스트 버스 어댑터(HBA), HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인합니다.
* SAN 부팅 구성 지원 및 알려진 문제를 확인하려면 Veritas 지원 포털(제품 매트릭스, 플랫폼 조회 및 HCL 매트릭스)을 참조하세요.


.단계
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["SAN 부팅 LUN을 생성하고 호스트에 매핑합니다."^]..
. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하고 OS가 실행 중인지 확인하여 구성이 성공했는지 확인합니다.




== 2단계: Linux Host Utilities를 설치합니다

NetApp 강력히 권장합니다 link:hu-luhu-release-notes.html["Linux 호스트 유틸리티 설치"] ONTAP LUN 관리를 지원하고 기술 지원팀이 구성 데이터를 수집하는 데 도움을 줍니다.


NOTE: Linux Host Utilities를 설치해도 Linux 호스트의 호스트 시간 초과 설정은 변경되지 않습니다.



== 3단계: 호스트에 대한 Veritas Dynamic Multipathing 구성 확인

Veritas Infoscale 7과 함께 Veritas Dynamic Multipathing(VxDMP)을 사용하여 ONTAP LUN을 관리합니다.

호스트에 VxDMP가 올바르게 설정되었는지 확인하려면 VxDMP 구성을 검증하고 ASL(Array Support Library)과 APM(Array Policy Module) 구성을 확인해야 합니다. NetApp 스토리지 시스템용 ASL 및 APM 패키지는 Veritas 소프트웨어 설치 중에 설치됩니다.


NOTE: Veritas Infoscale, Linux Native Device Mapper, LVM 볼륨 관리자를 포함한 이기종 멀티패스 환경의 경우 구성 설정에 대한 Veritas 제품 관리 문서를 참조하세요.

.시작하기 전에
구성이 시스템 요구 사항을 충족하는지 확인하세요. 를 참조하십시오 link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] 그리고 Veritas HCL Matrix.

.단계
. ONTAP 대상 어레이가 VxDMP 멀티패스에 연결되어 있는지 확인하세요.
+
[source, cli]
----
vxdmpadm
----
+
.예제 보기
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. ASL 및 APM 패키지의 구성을 확인하세요. NetApp Veritas 지원 포털에 나열된 최신 지원 패키지를 사용할 것을 권장합니다.
+
.ASL 및 APM 구성 예시 보기
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. 스토리지 장애 조치 작업에서 최적의 시스템 구성을 위해 다음 Veritas VxDMP 튜너블이 있는지 확인하세요.
+
[cols="2*"]
|===
| 매개 변수 | 설정 


| dmp_lun_retry_timeout입니다 | 60 


| dmp_path_age입니다 | 120 


| dmp_restore_interval입니다 | 60 
|===
. DMP 튜너블을 온라인으로 설정합니다.
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. 튜너블이 올바르게 설정되었는지 확인하세요.
+
[source, cli]
----
# vxdmpadm gettune
----
+
다음 예에서는 SAN 호스트의 효과적인 VxDMP 튜너블을 보여줍니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. 프로토콜 시간 초과 값을 구성합니다.
+
[role="tabbed-block"]
====
.FC/FCoE
--
FC 및 FCoE에 기본 시간 초과 값을 사용합니다.

--
.iSCSI
--
설정하다 `replacement_timeout` 매개변수 값을 120으로 설정합니다.

iSCSI `replacement_timeout` 매개변수는 iSCSI 계층이 시간 초과된 경로 또는 세션이 재설정될 때까지 기다려야 하는 시간을 제어하며, 이 시간이 지나면 해당 경로 또는 세션에 대한 명령이 실패합니다. NetApp 다음 값을 설정할 것을 권장합니다. `replacement_timeout` iSCSI 구성 파일에서 120까지.

.예
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. 스토리지 장애 조치 시나리오에서 Veritas Infoscale 환경을 지원하려면 RHEL 8 및 9 시리즈 호스트에 대한 호스트 "udev rport" 값을 설정합니다.
+
파일을 생성하여 "udev rport" 값을 구성합니다. `/etc/udev/rules.d/40-rport.rules` 다음 파일 내용이 포함되어 있습니다.

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Veritas에 특정한 다른 모든 설정에 대해서는 표준 Veritas Infoscale 제품 설명서를 참조하세요.

. ONTAP LUN의 매개 변수 설정 및 경로 상태를 확인합니다.
+
AFF, FAS 또는 ASA 구성에서는 단일 ONTAP LUN에 4개 이상의 경로가 필요하지 않습니다. 4개 이상의 경로가 있는 경우 저장 장애 발생 시 문제가 발생할 수 있습니다.

+
다음 예에서는 ASA, AFF 또는 FAS 구성에서 ONTAP LUN의 올바른 매개변수 설정과 경로 상태를 보여줍니다.

+
[role="tabbed-block"]
====
.ASA 구성
--
ASA 구성은 지정된 LUN에 대한 모든 경로를 최적화하여 활성 상태를 유지합니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

.예제 보기
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.AFF 또는 FAS 구성
--
AFF 또는 FAS 구성에는 우선 순위가 높거나 낮은 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 활성/최적화 경로는 애그리게이트가 위치한 컨트롤러에서 제공합니다. 낮은 우선 순위 경로는 다른 컨트롤러에서 제공되기 때문에 활성 상태이지만 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

다음 예에서는 활성/최적화 경로 2개와 활성/최적화되지 않은 경로 2개가 있는 ONTAP LUN에 대한 출력을 표시합니다.

.예제 보기
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== 4단계: 알려진 문제

알려진 문제가 없습니다.



== 다음 단계

* link:hu-luhu-command-reference.html["Linux Host Utilities 툴 사용에 대해 자세히 알아보십시오"] .

