---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: AIX에서 LUN을 검색 및 구성하는 방법에 대한 설명은 에 나와 있습니다 
---
= (PowerVM이 없는 AIX MPIO) AIX에서 LUN 검색 및 구성
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
PowerVM 없이 AIX를 사용하는 경우 cfgmgr 명령을 사용하여 호스트가 LUN을 검색하도록 합니다. LUN을 검색하기 위해 호스트를 재부팅할 필요가 없습니다. 호스트가 LUN을 검색했는지 확인하려면 sanlun 유틸리티를 사용할 수 있습니다.


NOTE: 다음 단계는 PowerVM 환경을 실행 중인 호스트에는 적용되지 않습니다.

.단계
. 호스트에서 루트로 로그인합니다.
. AIX 호스트에서 다음 명령을 입력하여 새로 생성된 LUN을 검색합니다.
+
cfgmgr

+
cfgmgr 명령을 사용하면 다음과 같은 작업을 수행할 수 있습니다.

+
** Fabric에 로그인하는 이니시에이터
** 시스템에서 새 장치를 확인합니다.
** 새 장치 항목을 생성하는 시스템입니다.


. NetApp LUN을 포함한 모든 AIX 디스크를 표시하려면 다음 명령을 입력하십시오.
+
'lsdev-Cc disk'

+
LUN은 호스트에 디스크로 표시됩니다. 호스트에서 로컬 디스크를 사용하는 것과 동일한 방식으로 이러한 디스크를 사용할 수 있습니다. Host Utilities의 일부로 설치된 호스트 설정 ODM 파일로 인해 LUN이 NetApp FCP 디스크로 표시됩니다.

+
hdisk 인스턴스 번호를 기록합니다. 경로 구성을 수행할 때 이 옵션을 사용합니다.

+
다음은 FC를 사용하는 환경에서 lsdev-Cc disk 명령이 생성하는 출력 유형입니다.

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. 설정에 대한 정보를 보려면 다음 명령을 입력합니다.
+
'lsattr-El hdisk_name'입니다

+
이 명령을 실행하면 다음 출력이 생성됩니다.

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. 구성에서 ALUA를 지원하는 경우 이 구성을 사용하여 경로 우선 순위를 설정할 수 있습니다. ALUA가 설정되었는지 확인합니다.
+
'lun igroup show-instance igroup_name'입니다

+
.. ALUA가 설정되어 있지 않으면 다음을 사용하도록 설정합니다.
+
'igroup set igroup_name ALUA yes'입니다



. 구성에서 ALUA를 지원하지 않는 경우 경로 우선 순위를 설정하려면 dotpath 유틸리티를 실행해야 합니다. dotpath 유틸리티는 Host Utilities를 설치할 때 설치됩니다. ALUA가 활성화된 경우 dotpath 유틸리티를 사용하지 마십시오.
+
.. 모든 Data ONTAP LUN의 우선 순위를 설정하려면 다음을 입력합니다.
+
"도트경로"를 선택합니다

.. 특정 디스크 세트에 대한 우선 순위를 설정하려면 다음을 입력합니다.
+
Dotpaths[-HQV][hdiskN...]'을 선택합니다

+
세부 정보 표시 모드를 활성화하고 모든 우선 순위를 표시하려면 '-v' 옵션을 사용합니다. 모든 또는 개별 디스크 우선 순위를 쿼리하려면 '-q' 옵션을 사용합니다.



. 호스트가 LUN을 검색했는지 확인하려면 다음 명령을 입력합니다.
+
sandlun lun show를 참조하십시오

+
.예
이 예제는 MPIO 다중 경로 환경에서 'show'를 사용한 일반적인 명령의 출력을 보여 줍니다.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

