---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: ONTAP와 함께 IBM AIX 7.2 및/또는 PowerVM VIOS 3.1을 사용하는 방법에 대해 설명합니다 
---
= ONTAP 스토리지용 AIX 호스트 유틸리티 6.1을 설치합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX 호스트 유틸리티는 AIX 호스트에 연결된 ONTAP 스토리지를 관리하는 데 도움이 됩니다.  NetApp ONTAP 스토리지 관리를 개선하고 NetApp 지원팀이 구성에 대한 정보를 수집하는 데 도움이 되도록 AIX 호스트 유틸리티를 설치할 것을 적극 권장합니다.

AIX Host Utilities 6.1은 다음과 같은 전송 프로토콜과 AIX 환경을 지원합니다.

* FC, FCoE 및 iSCSI
* AIX Microsoft 다중 경로 I/O(MPIO)
* PowerVM
+
PowerVM에 대한 자세한 내용은 IBM PowerVM Live Partition Mobility Red Book을 참조하십시오.



.이 작업에 대해
* AIX 호스트에 연결된 ONTAP 스토리지를 관리하려면 AIX MPIO와 함께 AIX Host Utilities SAN Toolkit을 설치해야 합니다.
* AIX 호스트 유틸리티를 설치해도 AIX 호스트의 설정은 변경되지 않습니다.


.시작하기 전에
* 사용하세요link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] AIX OS, 프로토콜 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인하세요.
* 다음을 실행하여 모든 FC 및 FCoE 이니시에이터에 대한 동적 추적을 활성화합니다. `chdev -l <fscsi_device> -a dyntrk=ye` AIX 호스트의 명령.


.단계
. 호스트에 로그인합니다.
+
[role="tabbed-block"]
====
.AIX
--
AIX 호스트에서 * root * 로 로그인합니다.

--
.PowerVM
--
PowerVM 호스트에서:

.. *padmin*으로 로그인하세요.
.. 루트 사용자가 되세요:
+
[source, cli]
----
oem_setup_env
----


--
====
. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["NetApp Support 사이트"^] Host Utilities가 포함된 압축 파일을 호스트의 디렉토리에 다운로드합니다.
. 다운로드가 포함된 디렉터리로 이동합니다.
. 파일의 압축을 풀고 SAN Toolkit 소프트웨어 패키지를 추출합니다.
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
파일 압축을 풀 때 'tap_aix_host_utilities_6.1' 디렉토리가 생성됩니다. 이 디렉토리에는 MPIO, non_MPIO 또는 SAN_Tool_Kit 하위 디렉토리 중 하나가 있습니다.

. AIX MPIO를 설치합니다.
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. SAN 툴킷을 설치합니다.
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. 호스트를 재부팅합니다.
. 설치를 확인합니다.
+
[source, cli]
----
sanlun version
----




== 다음 단계

link:hu-aix-san-toolkit.html["AIX SAN 툴킷에 대해 알아보세요"] .
