---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: Citrix XenServer 7.x를 ONTAP와 함께 사용하는 방법에 대해 설명합니다 
---
= ONTAP에서 Citrix XenServer를 사용합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FC, FCoE 및 iSCSI 프로토콜을 사용하는 Citrix XenServer 7 시리즈 OS 릴리스에 대한 ONTAP SAN 호스트 구성 설정을 구성할 수 있습니다.



== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 OS가 가동되고 경로에서 실행되면 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

Citrix XenServer의 다중 경로 지원은 Device Mapper multipathd 구성 요소를 기반으로 합니다. 디바이스 매퍼 노드는 XenServer에 제공된 모든 LUN에 대해 자동으로 생성되지 않으며 API(Storage Management Layer)에서 LUN을 적극적으로 사용하는 경우에만 프로비저닝됩니다. Citrix XenServer Storage Manager API 플러그인은 다중 경로 노드의 활성화 및 비활성화를 자동으로 처리합니다.

통합 다중 경로 관리 아키텍처와의 비호환성 때문에 Citrix XenCenter 애플리케이션을 사용하여 스토리지 구성을 관리하는 것이 좋습니다. 장치 매퍼 테이블의 상태를 수동으로 쿼리하거나 시스템의 활성 장치 매퍼 다중 경로 노드를 나열해야 하는 경우 "/sbin/mpathutil status" 명령을 사용하여 ONTAP LUN의 설정을 확인할 수 있습니다. 자세한 내용은 Citrix XenServer의 표준 공급업체 설명서를 참조하십시오.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 경로는 활성/최적화입니다. 즉, 애그리게이트가 위치한 컨트롤러에 의해 처리됩니다. 우선 순위가 낮은 경로는 활성 상태이지만 다른 컨트롤러에서 제공되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상인 경우 스토리지 장애 시 경로 문제가 발생할 수 있습니다.



=== 모든 SAN 어레이 구성

모든 SAN 어레이(ASA) 구성에서 지정된 LUN(논리 유닛)에 대한 모든 경로가 활성 및 최적화됩니다. 즉, 모든 경로를 통해 동시에 I/O를 처리할 수 있으므로 성능이 향상됩니다.

.예
다음 예는 4개의 Active/Optimized 경로가 모두 포함된 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상인 경우 스토리지 장애 시 경로 문제가 발생할 수 있습니다.



=== 권장 설정

Citrix XenServer 7.x OS는 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다. Citrix XenServer 7.x의 경우 빈 zerobyte '/etc/multipath.conf' 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다.

XenCenter Management Portal*에서 호스트 다중 경로 서비스를 활성화하고 다중 경로 서비스가 활성화되어 실행 중인지 확인합니다.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
 `/etc/multipath.conf`다중 경로를 관리하지 않으려는 장치가 있거나 기본값을 재정의하는 기존 설정이 없는 경우 파일에 콘텐츠를 추가할 필요가 없습니다. 다음 구문을 `multipath.conf` 파일에 추가하여 원치 않는 장치를 제외할 수 있습니다.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: DevID> * 를 제외할 장치의 WWID 문자열로 바꿉니다.

.예
다음 Citrix XenServer 7.x 예에서 는 `sda` 블랙리스트에 추가할 로컬 SCSI 디스크입니다.

. 다음 명령을 실행하여 WWID를 확인하십시오.
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. 이 WWID를 '/etc/multipath.conf'의 블랙리스트 스탠자에 추가합니다.
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


'$multipathd show config' 명령을 사용하여 multipath 매개 변수 런타임 구성을 참조하십시오. 기본 설정을 재정의할 수 있는 레거시 설정, 특히 기본 섹션에서 실행 중인 구성을 항상 확인해야 합니다.

다음 표에는 ONTAP LUN에 대한 중요 * multipathd * 매개 변수와 필요한 값이 나와 있습니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 덮어쓴 경우 ONTAP LUN에 특별히 적용되는 * multipath.conf * 에서 나중에 Stanzas를 통해 수정해야 합니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 다음 기본값은 NetApp 및/또는 OS 공급업체에 문의하여 영향을 완전히 이해해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| "제_영주"를 선택합니다 | 예 


| DEV_Loss_TMO | "무한대" 


| 페일백 | 즉시 


| 빠른 IO_FAIL_TMO | 5 


| 기능 | "3 queue_if_no_path pg_init_retries 50" 


| "flush_on_last_del" | "예" 


| hardware_handler를 선택합니다 | "0" 


| 'path_checker | "tur" 


| path_grouping_policy입니다 | "group_by_prio(그룹 기준/원시)" 


| '경로 선택기' | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| '제품' | LUN. * 


| "Stain_attached_hw_handler"를 선택합니다 | 예 


| 'RR_WEIGHT | "균일" 


| 'user_friendly_names'입니다 | 아니요 


| '더 너더' | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 * multipath.conf * 파일은 ONTAP LUN과 호환되지 않는 * path_checker * 및 * detect_prio * 에 대한 값을 정의합니다. 호스트에 연결된 다른 SAN 스토리지 때문에 이러한 매개 변수를 제거할 수 없는 경우 디바이스 스탠자가 있는 ONTAP LUN에 대해 이러한 매개 변수를 특별히 수정할 수 있습니다.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix XenServer에서는 지원되는 구성을 위해 모든 Linux 및 Windows 기반 게스트 VM에 Citrix VM 도구를 사용할 것을 권장합니다.



== 알려진 문제

ONTAP를 사용하는 Citrix XenServer 릴리즈에는 알려진 문제가 없습니다.
