---
sidebar: sidebar 
permalink: hu_citrix_8x.html 
keywords: host utilities, citrix, hypervisor, 8.0, 8.1, 8.2, netapp, ontap, sanhost 
summary: ONTAP에서 Citrix Hypervisor 8.x를 사용하는 방법에 대해 설명합니다 
---
= ONTAP에서 Citrix Hypervisor 사용
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FC, FCoE 및 iSCSI 프로토콜을 사용하여 Citrix 하이퍼바이저 8 시리즈 OS 릴리스에 대한 ONTAP SAN 호스트 구성 설정을 구성할 수 있습니다.



== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 OS가 가동되고 경로에서 실행되면 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

Citrix Hypervisor(CH) 8.x의 경우 `/etc/multipath.conf` 파일이 존재해야 하지만 파일을 특별히 변경할 필요는 없습니다. CH 8.x는 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다. status 명령을 사용하여 ONTAP LUN에 대한 설정을 확인할 수 `/sbin/mpathutil` 있습니다. 다음 섹션에서는 ASA 대상에 매핑된 LUN에 대한 샘플 다중 경로 출력을 제공합니다.



=== ASA(All SAN 어레이) 구성

모든 SAN 어레이(ASA) 구성에는 우선 순위가 1인 경로 그룹이 하나 있어야 합니다. 모든 경로가 Active/Optimized입니다. 즉, 컨트롤러에서 서비스를 제공하고 모든 활성 경로에 I/O가 전송됩니다.

.예
다음 예는 4개의 Active/Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
....

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 경로는 활성/최적화입니다. 즉, 애그리게이트가 위치한 컨트롤러에 의해 처리됩니다. 우선 순위가 낮은 경로는 활성 상태이지만 다른 컨트롤러에서 제공되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
 |- 1:0:0:11   sde   8:64    active ready running
`- 12:0:8:11  sdua  66:544  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
   |- 1:0:9:11   sddo  71:96   active ready running
   `- 12:0:26:11 sdyt  129:720 active ready running
....

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



== 권장 설정

Citrix Hypervisor 8.x OS는 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다. Citrix Hypervisor 8.x의 경우 빈 zerobyte '/etc/multipath.conf' 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다.

XenCenter Management Portal*에서 호스트 다중 경로 서비스를 활성화하고 다중 경로 서비스가 활성화되어 실행 중인지 확인합니다.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
 `/etc/multipath.conf`다중 경로를 관리하지 않으려는 장치가 있거나 기본값을 재정의하는 기존 설정이 없는 경우 파일에 콘텐츠를 추가할 필요가 없습니다. 다음 구문을 multipath.conf 파일에 추가하여 원치 않는 디바이스를 제외할 수 있습니다.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: DevID> * 를 제외할 장치의 WWID 문자열로 바꿉니다.

.예
다음 Citrix Hypervisor 8.x 예에서 는 `sda` 블랙리스트에 추가할 로컬 SCSI 디스크입니다.

. 다음 명령을 실행하여 WWID를 확인하십시오.
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. 이 WWID를 '/etc/multipath.conf'의 블랙리스트 스탠자에 추가합니다.
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


'$multipathd show config' 명령을 사용하여 multipath 매개 변수 런타임 구성을 참조하십시오. 기본 설정을 재정의할 수 있는 레거시 설정, 특히 기본 섹션에서 실행 중인 구성을 항상 확인해야 합니다.

다음 표에는 ONTAP LUN에 대한 중요 * multipathd * 매개 변수와 필요한 값이 나와 있습니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 덮어쓴 경우 ONTAP LUN에 특별히 적용되는 * multipath.conf * 에서 나중에 Stanzas를 통해 수정해야 합니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 다음 기본값은 NetApp 및/또는 OS 공급업체에 문의하여 영향을 완전히 이해해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| "제_영주"를 선택합니다 | 예 


| DEV_Loss_TMO | "무한대" 


| 페일백 | 즉시 


| 빠른 IO_FAIL_TMO | 5 


| 기능 | "3 queue_if_no_path pg_init_retries 50" 


| "flush_on_last_del" | "예" 


| hardware_handler를 선택합니다 | "0" 


| 'path_checker | "tur" 


| path_grouping_policy입니다 | "group_by_prio(그룹 기준/원시)" 


| '경로 선택기' | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| '제품' | LUN. * 


| "Stain_attached_hw_handler"를 선택합니다 | 예 


| 'RR_WEIGHT | "균일" 


| 'user_friendly_names'입니다 | 아니요 


| '더 너더' | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 * multipath.conf * 파일은 ONTAP LUN과 호환되지 않는 * path_checker * 및 * detect_prio * 에 대한 값을 정의합니다. 호스트에 연결된 다른 SAN 스토리지 때문에 이러한 매개 변수를 제거할 수 없는 경우 디바이스 스탠자가 있는 ONTAP LUN에 대해 이러한 매개 변수를 특별히 수정할 수 있습니다.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix Hypervisor는 지원되는 구성을 위해 모든 Linux 및 Windows 기반 게스트 VM에 Citrix VM 도구를 사용할 것을 권장합니다.



== 알려진 문제

ONTAP가 포함된 Citrix Hypervisor 릴리즈에는 다음과 같은 알려진 문제가 있습니다.

[cols="4*"]
|===
| NetApp 버그 ID | 제목 | 설명 | Citrix Tracker ID입니다 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1242343["1242343"^] | 스토리지 페일오버 작업 중 QLogic QLE2742 32Gb FC를 사용하는 Citrix Hypervisor 8.0에서 커널 중단 | QLogic QLE2742 32GB HBA를 사용하는 Citrix Hypervisor 8.0 커널(4.19.0+1)에서 스토리지 페일오버 작업 중에 커널 중단이 발생할 수 있습니다. 이 문제는 운영 체제를 재부팅하라는 메시지를 표시하고 응용 프로그램을 중단시킵니다. kdump가 구성된 경우 커널 중단은 /var/crash/ 디렉토리 아래에 vmcore 파일을 생성합니다. vmcore 파일을 사용하여 장애의 원인을 파악할 수 있습니다. 커널이 중단된 후에는 호스트 운영 체제를 재부팅하고 애플리케이션을 다시 시작하여 운영 체제를 복구할 수 있습니다. | link:https://tracker.citrix.com/browse/NETAPP-98["넷엡 - 98"^] 
|===