---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP 스토리지와 함께 HP-UX Host Utilities 6.0을 사용하는 방법을 설명합니다 
---
= ONTAP 스토리지용 HP-UX Host Utilities 6.0을 설치합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HP-UX 호스트 유틸리티는 HP-UX 호스트에 연결된 ONTAP 스토리지를 관리하는 데 도움이 됩니다.  NetApp HP-UX 호스트 유틸리티를 설치할 것을 강력히 권장하지만 필수는 아닙니다.  이러한 유틸리티는 관리를 개선하고 NetApp 고객 지원팀이 구성에 대한 정보를 수집하는 데 도움을 줍니다.

HP-UX 호스트 유틸리티는 다음 환경을 지원합니다.

* 네이티브 Microsoft 다중 경로 I/O(MPIO)
* Veritas 동적 다중 경로(DMP)


.시작하기 전에
안정적인 작동을 위해 다음을 사용하십시오. https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] iSCSI, FC 또는 FCoE 구성이 지원되는지 확인하세요.

.단계
. HP-UX 호스트 호스트에 로그인합니다.
. 에서 HP-UX Host Utilities 파일( netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` )을 다운로드합니다 link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^] HP-UX 호스트에
. 의 압축을 풉니다 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` 파일:
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
압축을 푼 소프트웨어가 서비스 센터 파일의 압축을 푼 디렉토리에 저장됩니다.

. 소프트웨어를 설치합니다.
+
[source, cli]
----
swinstall -s /depot_path
----
+
debot_path는 depot 파일의 경로와 이름을 제공합니다.

+
'winstall' 명령어는 HP-UX 설정 상태를 확인하는 설치 스크립트를 실행합니다. 시스템이 요구 사항을 충족할 경우 이 스크립트는 '/opt/netapp/sandtools/bin' 디렉토리에 'sanlun' 유틸리티 및 진단 스크립트를 설치합니다.

. 설치를 확인합니다.
+
[source, cli]
----
sanlun version
----




== 다음 단계

link:hu-hpux-sanlun-toolkit.html["SAN 툴킷에 대해 알아보세요"] .
