---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP 스토리지와 함께 HP-UX Host Utilities 6.0을 사용하는 방법을 설명합니다 
---
= ONTAP 스토리지용 HP-UX Host Utilities 6.0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp HP-UX 호스트 유틸리티를 사용하면 HP-UX 호스트를 ONTAP 스토리지에 연결할 수 있습니다.

HP-UX Host Utilities는 여러 프로토콜과 다음 환경을 지원합니다.

* 네이티브 Microsoft 다중 경로 I/O(MPIO)
* Veritas 동적 다중 경로(DMP)



NOTE: 사용 중인 환경을 나타내기 위해 이 문서에서는 Veritas DMP 환경에 대해 "DMP"를 지정하고 HP-UX 네이티브 환경에 대해 "MPIO"를 지정하는 경우도 있습니다. 사용하는 드라이버에 따라 명령이 다를 수 있습니다. 이 경우 환경 및 드라이버 유형이 모두 지정됩니다.

.시작하기 전에
* 안정적인 작업을 위해 전체 iSCSI, FC 또는 FCoE 구성이 지원되는지 확인하십시오.


를 사용하여 구성을 확인할 수 link:https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^]있습니다.

.이 작업에 대해
NetApp HP-UX Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["NetApp Support 사이트"^] 압축 파일 파일을 다운로드한 후 설치하기 전에 압축을 해제해야 합니다.

.단계
. 호스트에 로그인합니다.
. 에서 HP-UX Host Utilities 파일( netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` )을 다운로드합니다 link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^] HP-UX 호스트에
. 의 압축을 풉니다 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` 파일:
+
(#gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`)

+
압축을 푼 소프트웨어가 서비스 센터 파일의 압축을 푼 디렉토리에 저장됩니다.

. 소프트웨어를 설치합니다.
+
'#swinstall-s/depot_path'

+
debot_path는 depot 파일의 경로와 이름을 제공합니다.

+
'winstall' 명령어는 HP-UX 설정 상태를 확인하는 설치 스크립트를 실행합니다. 시스템이 요구 사항을 충족할 경우 이 스크립트는 '/opt/netapp/sandtools/bin' 디렉토리에 'sanlun' 유틸리티 및 진단 스크립트를 설치합니다.

. 설치를 확인합니다.
+
안런 버전





== SAN 툴킷을 참조하십시오

HP-UX Host Utilities는 HP-UX 호스트에 명령줄 툴킷을 제공하는 NetApp 호스트 소프트웨어입니다. 이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 설치됩니다. 이 키트에서 제공하는 `sanlun` 유틸리티를 사용하면 LUN 및 호스트 버스 어댑터를 관리할 수 있습니다. 있습니다.  `sanlun`이 명령을 실행하면 호스트에 매핑된 LUN에 대한 정보, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보가 반환됩니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: 이 툴킷은 모든 호스트 유틸리티 구성과 프로토콜에 공통적으로 적용됩니다. 따라서 모든 부품이 모든 설정에 적용되지 않습니다. 사용하지 않는 구성 요소는 시스템 성능에 영향을 주지 않습니다. SAN 툴킷은 AIX 및 PowerVM/VIOS OS 버전에서 지원됩니다.
