---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: ONTAP LUN을 사용하여 FCP 및 iSCSI 프로토콜 작업을 관리하려면 HP-UX 11i v3 호스트에 Linux 호스트 유틸리티를 설치합니다. 
---
= ONTAP 스토리지를 사용하여 FCP 및 iSCSI에 대한 HP-UX 11i v3 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HP-UX 호스트 유틸리티 소프트웨어는 ONTAP 스토리지에 연결된 HP-UX 호스트에 대한 관리 및 진단 도구를 제공합니다.  HP-UX 11i v3 호스트에 HP-UX 호스트 유틸리티를 설치하면 호스트 유틸리티를 사용하여 ONTAP LUN을 사용하여 FCP 및 iSCSI 프로토콜 작업을 관리할 수 있습니다.



== 1단계: 필요에 따라 SAN 부팅을 활성화합니다

배포를 간소화하고 확장성을 개선하기 위해 SAN 부팅을 사용하도록 호스트를 구성하세요.  SAN 부팅은 SAN에 연결된 디스크(LUN)를 HP-UX 호스트의 부팅 장치로 설정하는 프로세스입니다.  호스트 유틸리티는 HP-UX 환경에서 FC 및 FCoE 프로토콜을 사용한 SAN 부팅을 지원합니다.

.단계
. 를 사용하여 link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^]Linux OS, 호스트 버스 어댑터(HBA), HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인합니다.
. HP-UX 공급업체 설명서에서 SAN 부팅을 설정하는 모범 사례를 따르세요.




== 2단계: HP-UX 호스트 유틸리티 설치

NetApp ONTAP LUN 관리를 지원하고 기술 지원팀의 구성 데이터 수집을 돕기 위해 HP-UX 호스트 유틸리티를 설치할 것을 강력히 권장합니다.

link:hu_hpux_60.html["HP-UX Host Utilities 6.0을 설치합니다"]



== 3단계: 호스트의 다중 경로 구성을 확인합니다

HP-UX 11i v3에서 다중 경로를 사용하여 ONTAP LUN을 관리합니다.  다중 경로를 사용하면 호스트와 스토리지 시스템 간에 여러 개의 네트워크 경로를 구성할 수 있습니다.  한 경로에 장애가 발생하더라도 나머지 경로로 교통이 계속 진행됩니다.

HP-UX 호스트 유틸리티를 설치한 후 ONTAP LUN에 대해 NetApp 권장 설정이 구성되어 있는지 확인하세요.

.이 작업에 대해
HP-UX 호스트 유틸리티는 기본 Microsoft Multipath I/O(MPIO) 및 Veritas Dynamic Multipathing을 지원합니다.  다음 단계는 Native MPIO 솔루션을 위한 것입니다.

.단계
. HP-UX 호스트 유틸리티를 설치하면 ONTAP LUN에 대해 다음과 같은 권장 기본 설정이 자동으로 로드됩니다.
+
.매개 변수 설정을 표시합니다
[%collapsible]
====
[cols="2*"]
|===
| 매개 변수 | 기본값을 사용합니다 


| transient_secs | 120 


| leg_mpath_enable | 참 


| 최대_q_깊이 | 8 


| path_fail_secs | 120 


| Load_bal_policy 를 참조하십시오 | round_robin(라운드 로빈 


| Lua_enabled | 참 


| ESD_초 | 30 
|===
====
. ONTAP LUN의 매개 변수 설정 및 경로 상태를 확인합니다.
+
[source, cli]
----
sanlun lun show
----
+
기본 다중 경로 매개변수는 ASA, AFF 및 FAS 구성을 지원합니다.  다음 예제 출력은 ASA, AFF 또는 FAS 구성에서 ONTAP LUN의 올바른 매개변수 설정과 경로 상태를 보여줍니다.

+
[role="tabbed-block"]
====
.ASA 구성
--
ASA 구성은 지정된 LUN에 대한 모든 경로를 최적화하여 활성 상태를 유지합니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--
.AFF 또는 FAS 구성
--
AFF 또는 FAS 구성에는 우선 순위가 높거나 낮은 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 활성/최적화 경로는 애그리게이트가 위치한 컨트롤러에서 제공합니다. 낮은 우선 순위 경로는 다른 컨트롤러에서 제공되기 때문에 활성 상태이지만 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

다음 예에서는 활성/최적화 경로 2개와 활성/최적화되지 않은 경로 2개가 있는 ONTAP LUN에 대한 출력을 표시합니다.

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====




== 4단계: 알려진 문제 검토

ONTAP 스토리지 릴리스가 포함된 HP-UX 11i v3에는 다음과 같은 알려진 문제가 있습니다.

[cols="4*"]
|===
| NetApp 버그 ID | 제목 | 설명 | 파트너 ID입니다 


| 1447287 | SnapMirror 활성 동기화 구성에서 격리된 마스터 클러스터에 대한 AUFO 이벤트로 인해 HP-UX 호스트가 일시적으로 중단됩니다 | 이 문제는 SnapMirror 액티브 동기화 구성에서 격리된 마스터 클러스터에 계획되지 않은 자동 페일오버(AUFO) 이벤트가 있는 경우 발생합니다. HP-UX 호스트에서 I/O를 재개하는 데 120초 이상 걸릴 수 있지만 이로 인해 I/O 중단 또는 오류 메시지가 발생하지는 않습니다. 이 문제로 인해 1차 클러스터와 2차 클러스터 간의 연결이 끊겼고 1차 클러스터와 중재자 사이의 연결도 손실되기 때문에 이중 이벤트 오류가 발생합니다. 이것은 다른 AUFO 이벤트와 달리 드문 사건으로 간주됩니다. | 해당 없음 


| 1344935 | HP-UX 11.31 호스트가 ASA 설정에서 간헐적으로 경로 상태를 잘못 보고합니다. | ASA 구성과 관련된 경로 보고 문제 | 해당 없음 


| 1306354)를 참조하십시오 | HP-UX LVM 생성 시 블록 크기의 I/O가 1MB 이상으로 전송됩니다 | SCSI 최대 전송 길이 1MB는 ONTAP All SAN 어레이에 적용됩니다. ONTAP All SAN 어레이에 연결할 때 HP-UX 호스트에서 최대 전송 길이를 제한하려면 HP-UX SCSI 서브시스템에서 허용하는 최대 I/O 크기를 1MB로 설정해야 합니다. 자세한 내용은 HP-UX 공급업체 문서를 참조하십시오. | 해당 없음 
|===


== 다음은 무엇입니까?

link:hu_hpux_60_cmd.html["HP-UX 호스트 유틸리티 도구 사용에 대해 알아보세요"] .
