---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP와 함께 Linux 호스트 유틸리티 7.1을 사용하는 방법을 설명합니다 
---
= Linux Host Utilities 7.1을 설치합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux 호스트 유틸리티는 Linux 호스트에 연결된 ONTAP 스토리지를 관리하도록 지원합니다. NetApp은 Linux 호스트 유틸리티를 설치할 것을 적극 권장하지만 필수는 아닙니다. 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

지원되는 Linux 배포판은 다음과 같습니다.

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer를 참조하십시오


.시작하기 전에
NetApp Linux 호스트 유틸리티 소프트웨어 패키지는 32비트 또는 64비트 .rpm 파일로 에서 사용할 수 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^]있습니다.

* 안정적인 운영을 위해서는 전체 iSCSI, FC 또는 FCoE 구성이 지원되는지 확인해야 합니다.
+
를 사용하여 구성을 확인할 수 link:https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^]있습니다.

* 공급업체 지원 사이트에서 사용할 수 있는 HBA(호스트 버스 어댑터) 관리 패키지를 설치해야 합니다.
+
관리 소프트웨어를 사용하면 SAN 툴킷 명령이 WWPN과 같은 FC HBA에 대한 정보를 수집할 수 있습니다.  `sanlun fcp show adapter`명령을 사용하려면 다음 패키지가 올바르게 설치되어 있는지 확인하십시오.

+
** Marvell QLogic HBA – QConvergeConsole CLI
** Broadcom Emulex HBA-OneCommand Manager 핵심 응용 프로그램 CLI
** Marvell Brocade HBA – Brocade 명령 유틸리티 CLI


* 각 Linux 배포에서 사용할 수 있는 rpm 패키지 "libhbaapi" 및 "libhbalinux"는 호스트 OS에 설치해야 합니다.



NOTE: Linux Host Utilities 소프트웨어는 NVMe/FC(NVMe over Fibre Channel) 및 NVMe/TCP(NVMe over TCP) 호스트 프로토콜을 지원하지 않습니다.

.단계
. 현재 Linux Host Utilities 버전이 설치되어 있는 경우 다음 명령을 사용하여 제거합니다.
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
이전 버전의 Linux Host Utilities의 경우, 호스트 유틸리티 소프트웨어가 설치된 디렉토리로 이동하고 uninstall 명령을 입력하여 설치된 패키지를 제거합니다.

. 에서 호스트로 32비트 또는 64비트 Linux Host Utilities 소프트웨어 패키지를 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^]다운로드합니다.
. 소프트웨어 패키지를 다운로드한 디렉토리로 이동한 후 다음 명령을 사용하여 설치합니다.
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. 설치를 확인합니다.
+
[source, cli]
----
sanlun version
----
+
[listing]
----
sanlun version 7.1.386.1644
----




== Linux 커널에서 권장되는 드라이버 설정

Linux 커널과 함께 번들로 제공되는 기본 받은 편지함 드라이버를 사용하는 FC 환경을 구성하는 경우 드라이버의 기본값을 사용할 수 있습니다.



== SAN 툴킷을 참조하십시오

Linux Host Utilities는 Linux 호스트에 명령줄 툴킷을 제공하는 NetApp 호스트 소프트웨어입니다.

이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 자동으로 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[source, cli]
----
# sanlun lun show all
----
예제 출력:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* 이 툴킷은 Host Utilities의 모든 구성 및 프로토콜에서 공통적으로 사용됩니다. 따라서 일부 내용은 한 설정에 적용되지만 다른 설정에는 적용되지 않습니다. 사용하지 않는 구성 요소가 있으면 시스템 성능에 영향을 주지 않습니다.
* SAN 툴킷은 Citrix XenServer, Oracle VM 및 Red Hat Enterprise Virtualization Hypervisor에서 지원되지 않습니다.


====