---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Linux Unified Host Utilities 7.1 릴리스 정보 
---
= Linux Unified Host Utilities 7.1 릴리스 정보
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
릴리즈 노트에서는 ONTAP 스토리지 시스템에서 특정 호스트를 구성 및 관리하기 위한 새로운 기능 및 향상된 기능, 알려진 문제 및 제한 사항, 중요한 주의 사항에 대해 설명합니다.

Host Utilities가 지원하는 운영 체제 버전 및 업데이트에 대한 자세한 내용은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].



== 새로운 기능

Linux Host Utilities 7.1 릴리스에는 다음과 같은 새로운 기능과 향상된 기능이 포함되어 있습니다.

* Linux 호스트 유틸리티는 SANtricity를 실행하는 NetApp E-Series 스토리지 시스템과 ONTAP을 실행하는 AFF, FAS 및 ASA 시스템을 지원하기 때문에 이제 _ Linux 통합 호스트 유틸리티라고 합니다.
+

NOTE: 이 문서에서 Host Utilities 또는 Linux Host Utilities에 대한 언급은 Linux Unified Host Utilities를 참조합니다.

* 이제 다음 운영 체제가 지원됩니다.
+
** SUSE Linux Enterprise Server 15 시리즈
** Oracle VM 3.2 시리즈
** Oracle Linux 6 및 7 시리즈
** Red Hat Enterprise Linux 6 및 7 시리즈
** SUSE Linux Enterprise Server 11 SP4
** KVM 및 XEN, RHEV 6.4 및 6.5
** Citrix XenServer를 참조하십시오


* RHEL(Red Hat Enterprise Linux) 6 및 RHEL 7 호스트에서 이제 서버 프로필 설정을 위한 조정된 패키지가 지원됩니다. 를 사용할 수 있습니다 `tuned-adm` 환경에 따라 다른 프로파일을 설정하는 명령입니다. 예를 들어, 가상 게스트 프로파일을 게스트 가상 머신으로 사용할 수도 있고 엔터프라이즈 스토리지 어레이의 LUN이 사용되는 구성에 엔터프라이즈 스토리지 프로파일을 사용할 수도 있습니다. 조정된 패키지를 사용하면 ONTAP의 처리량과 지연 시간이 개선될 수 있습니다.
* Broadcom Emulex 및 Marvell Qlogic의 32Gb FC 어댑터에 대한 지원을 추가합니다.



NOTE: NetApp은 최초 릴리즈 이후에도 Host Utilities와 계속 협력하여 기능에 대한 지원을 추가합니다. 지원되는 기능 및 추가된 새 기능에 대한 최신 정보는 를 참조하십시오 link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].



== 이 릴리스에서 수정되었습니다

SUSE Linux Enterprise Server 12 SP1, OL 7.2, RHEL 7.2 및 RHEL 6.8에서 명령을 실행할 때 발생하는 간헐적인 호스트 OS 장애 문제는 `sanlun lun show -p` 이 릴리스에서 해결되었습니다.



== 알려진 문제 및 제한 사항

Linux Host Utilities 7.1 릴리스에는 다음과 같은 알려진 문제와 제한 사항이 있습니다.

[cols="10, 30, 30"]
|===
| NetApp 버그 ID | 제목 | 설명 


| 1457017 | Sanlun 설치는 libdevmapper.so와 libnl.so 라이브러리와 관련된 경고 메시지를 발행한다. 이러한 경고는 '선' 키트의 기능에 영향을 주지 않습니다. | SAN 호스트에서 Linux Unified Host Utilities CLI 명령 " sanlun fcp show adapter -v "를 실행할 때 명령이 실패하고 HBA(호스트 버스 어댑터) 검색에 필요한 라이브러리 종속성이 로 표시되지 않는다는 오류 메시지가 표시됩니다
위치:

[root@hostname~]#sanlun fcp show adapter-v
/usr/lib64/libHBAAPI.so 라이브러리를 찾을 수 없습니다
라이브러리를 설치하는 패키지가 설치 및 로드되었는지 확인합니다
NetApp 온라인 버그 참조 - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp 온라인 버그"^] 가능한 경우 권장 해결 방법을 포함하여 대부분의 알려진 문제에 대한 전체 정보를 제공합니다.
