---
sidebar: sidebar 
permalink: hu_ol_66.html 
keywords: host utilities, oracle, linux, 6.6, netapp, ontap 
summary: ONTAP와 함께 Oracle Linux 6.6을 사용하는 방법을 설명합니다 
---
= Oracle Linux 6.6과 NetApp ONTAP 사용
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Linux Unified Host Utilities 설치

NetApp Linux Unified Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support 사이트"^] 32비트 및 64비트 .rpm 파일 구성에 적합한 파일을 모르는 경우 를 사용합니다 link:https://mysupport.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴"^] 필요한 것을 확인합니다.

Linux Unified Host Utilities를 설치하는 것이 좋지만 반드시 설치해야 하는 것은 아닙니다. 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

.필요한 것
현재 Linux Unified Host Utilities 버전이 설치되어 있는 경우 또는 를 업그레이드해야 합니다. 이 유틸리티를 제거하고 다음 단계를 따라 최신 버전을 설치해야 합니다.

. 에서 32비트 또는 64비트 Linux Unified Host Utilities 소프트웨어 패키지를 다운로드합니다 link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support 사이트"^] 사이트를 호스트에 연결.
. 다음 명령을 사용하여 소프트웨어 패키지를 설치합니다.
+
"rpm -ivh NetApp_linux_unified_host_utilities-7-1.x86_64"




NOTE: 이 컨텐츠에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== SAN 툴킷을 참조하십시오

이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 자동으로 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 https://mysupport.netapp.com/matrix/imt.jsp?components=74908;74907;71545;71546;69941;69939;69940;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+
여러 경로는 호스트 OS가 가동되어 경로에서 실행된 후에만 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

Oracle Linux 6.6의 경우 /etc/multipath.conf 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다. Oracle Linux 6.6은 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다. ALUA 처리기를 활성화하려면 다음 단계를 수행하십시오.

.단계
. initrd-image의 백업을 생성합니다.
. ' rdloaddriver=scsi_dh_ALUA'를 작동하려면 다음 매개 변수 값을 ALUA 및 비 ALUA용 커널에 추가하십시오
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. mkinitrd 명령을 사용하여 initrd-image를 다시 생성합니다. Oracle 6x 이상 버전에서는 mkinitrd -f /boot/initrd-"uname -r".img uname -r" 명령을 사용하거나 dracut -f 명령을 사용합니다
. 호스트를 재부팅합니다.
. 의 출력을 확인합니다 `cat /proc/cmdline` 명령을 사용하여 설정이 완료되었는지 확인합니다. 를 사용할 수 있습니다 `multipath -ll` 명령을 사용하여 ONTAP LUN의 설정을 확인합니다. 우선 순위가 다른 두 개의 경로 그룹이 있어야 합니다. 우선순위가 높은 경로는 Active/Optimized이며, 이는 애그리게이트는 컨트롤러가 서비스를 제공하는 것을 의미합니다. 우선 순위가 낮은 경로는 활성 경로이지만 다른 컨트롤러에서 서비스되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화된 경로를 사용할 수 없는 경우에만 사용됩니다.


.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
|-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



== 권장 설정

Oracle Linux 6.6 OS는 ONTAP LUN을 인식하여 모든 구성 매개 변수를 올바르게 설정하도록 컴파일되었습니다.

다중 경로 데몬을 시작하려면 multipath.conf 파일이 있어야 하지만 'touch/etc/multipath.conf' 명령을 사용하여 빈 0바이트 파일을 생성할 수 있습니다. 이 파일을 처음 생성할 때 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
multipath.conf에 직접 추가할 필요는 없습니다. 다중 경로를 통해 관리하지 않으려는 장치가 있거나 기본값을 덮어쓰는 기존 설정이 있는 경우에는 예외입니다. 다음 구문을 multipath.conf 파일에 추가하여 원치 않는 디바이스를 제외할 수 있습니다.


NOTE: DevID>를 제외할 장치의 WWID 문자열로 바꿉니다. 다음 명령을 사용하여 WWID를 확인하십시오.

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.예
이 예에서 sda는 블랙리스트에 추가해야 하는 로컬 SCSI 디스크입니다.

. 다음 명령을 실행하여 WWID를 확인하십시오.
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. 이 WWID를 /etc/multipath.conf의 "blacklist" 스탠자에 추가합니다.
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


기본 설정을 재정의할 수 있는 기본 섹션에서 항상 '/etc/multipath.conf' 파일에서 기존 설정을 확인해야 합니다. 아래 표에는 ONTAP LUN에 대한 중요 매개 변수와 필요한 값이 나와 있습니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 재정의될 경우 ONTAP LUN에 특별히 적용되는 'multipath.conf'에서 나중에 stanzas로 수정해야 합니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp 및/또는 OS 공급업체에 문의하여 영향을 완전히 이해해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "3 queue_if_no_path pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| no_path_retry 를 선택합니다 | 대기열 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "라운드 로빈 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN. * 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 'multitpath.conf' 파일은 ONTAP LUN과 호환되지 않는 path_checker와 detect_prio의 값을 정의합니다. 호스트에 아직 연결된 다른 SAN 스토리지 때문에 제거할 수 없는 경우 이러한 매개 변수를 디바이스 스탠자가 있는 ONTAP LUN에 대해 특별히 수정할 수 있습니다.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Oracle Linux 6.6 RedHat Enterprise Kernel(RHCK)을 구성하려면 를 사용하십시오 link:hu_rhel_66.html#recommended-settings["권장 설정"] RHEL(Red Hat Enterprise Linux) 6.6의 경우



== 알려진 문제 및 제한 사항

Oracle 6.6에는 알려진 문제가 없습니다.


NOTE: Oracle Linux(Red Hat 호환 커널) 알려진 문제에 대해서는 을 참조하십시오 link:hu_rhel_66.html#known-problems-and-limitations["알려진 문제"] RHEL(Red Hat Enterprise Linux) 6.6의 경우



== 릴리즈 노트



=== ASM 미러링

ASM 미러링은 ASM이 문제를 인식하고 대체 장애 그룹으로 전환할 수 있도록 Linux 다중 경로 설정을 변경해야 할 수 있습니다. ONTAP의 대다수 ASM 구성은 외부 이중화를 사용하는데, 이는 외부 어레이를 통해 데이터가 보호되고 ASM은 데이터를 미러링하지 않는다는 뜻입니다. 일부 사이트는 ASM에서 일반적인 수준의 이중화를 사용하며 일반적으로 여러 사이트에 걸쳐 양방향 미러링을 제공합니다. 을 참조하십시오 link:https://www.netapp.com/us/media/tr-3633.pdf["ONTAP 기반의 Oracle 데이터베이스"^] 를 참조하십시오.
