---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: ONTAP에서 Oracle Linux 7.6을 사용하는 방법에 대해 설명합니다 
---
= ONTAP와 함께 Oracle Linux 7.6을 사용합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SAN 호스트 구성 설정을 사용하여 ONTAP를 대상으로 Oracle Linux 7.6을 구성할 수 있습니다.



== Linux Unified Host Utilities를 설치합니다

NetApp Linux Unified Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^] 32비트 및 64비트 .rpm 파일 구성에 적합한 파일을 모르는 경우 를 사용합니다 link:https://mysupport.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴"^] 필요한 것을 확인합니다.

NetApp은 Linux 통합 호스트 유틸리티를 설치할 것을 적극 권장하지만 반드시 설치할 필요는 없습니다. 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

현재 Linux Unified Host Utilities 버전이 설치되어 있는 경우 이를 업그레이드하거나 제거한 후 다음 단계에 따라 최신 버전을 설치해야 합니다.

.단계
. 에서 32비트 또는 64비트 Linux Unified Host Utilities 소프트웨어 패키지를 다운로드합니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^] 사이트를 호스트에 연결.
. 다음 명령을 사용하여 소프트웨어 패키지를 설치합니다.
+
"rpm -ivh NetApp_linux_unified_host_utilities-7-1.x86_64"




NOTE: 이 문서에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== SAN 툴킷을 참조하십시오

이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 자동으로 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[source, cli]
----
# sanlun lun show all
----
예제 출력:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=86309;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 OS가 가동되고 경로에서 실행되면 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

Oracle Linux 7.6의 경우 /etc/multipath.conf 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다. Oracle Linux 7.6은 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다.

 `multipath -ll`명령을 사용하여 ONTAP LUN의 설정을 확인할 수 있습니다. 우선 순위가 다른 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 경로는 활성/최적화로, 이는 애그리게이트가 위치한 컨트롤러에서 서비스됩니다. 우선 순위가 낮은 경로는 활성 상태이지만 다른 컨트롤러에서 제공되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상인 경우 스토리지 장애 시 경로 문제가 발생할 수 있습니다.



== 권장 설정

Oracle Linux 7.6 OS는 ONTAP LUN을 인식하여 모든 구성 매개 변수를 올바르게 설정합니다.  `multipath.conf`다중 경로 데몬을 시작하려면 파일이 있어야 합니다. 이 파일이 없는 경우 명령을 사용하여 빈 0바이트 파일을 만들 수 있습니다 `touch /etc/multipath.conf`

 `multipath.conf`파일을 처음 만들 때 다음 명령을 사용하여 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

다중 경로를 관리하지 않으려는 장치가 있거나 기본값을 재정의하는 기존 설정이 없는 경우 파일에 직접 아무것도 추가할 필요가 `multipath.conf` 없습니다. 원치 않는 디바이스를 제외하려면 `multipath.conf` 파일에 다음 구문을 추가하여 <DevId>를 제외할 디바이스의 WWID 문자열로 대체합니다.

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
다음 예에서는 디바이스의 WWID를 확인하여 `multipath.conf` 파일에 추가합니다.

.단계
. WWID 확인:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` 블랙리스트에 추가할 로컬 SCSI 디스크입니다.

. 를 추가합니다 `WWID` 에서 블랙리스트로 `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


기본 설정을 무시할 수 있는 레거시 설정은 항상 파일, 특히 기본값 섹션에서 확인해야 `/etc/multipath.conf` 합니다.

다음 표에서는 ONTAP LUN에 대한 중요 매개 변수와 필요한 설정을 보여 `multipathd` 줍니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 재정의되면 `multipath.conf` ONTAP LUN에 특별히 적용되는 파일에서 이후의 stanzas로 수정되어야 합니다. 이 수정 사항이 없으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp, OS 공급업체 또는 둘 다와 상의하고 영향을 완전히 이해할 때만 재정의해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "3 queue_if_no_path pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN. * 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 'multitpath.conf' 파일은 ONTAP LUN과 호환되지 않는 path_checker와 detect_prio의 값을 정의합니다. 호스트에 아직 연결된 다른 SAN 스토리지 때문에 제거할 수 없는 경우 이러한 매개 변수를 디바이스 스탠자가 있는 ONTAP LUN에 대해 특별히 수정할 수 있습니다.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Oracle Linux 7.6 RHCK(Red Hat Enterprise Kernel)을 구성하려면 link:hu_rhel_76.html#recommended-settings["권장 설정"]RHEL(Red Hat Enterprise Linux) 7.6용 을 사용하십시오.



== 알려진 문제

ONTAP 릴리즈가 포함된 Oracle Linux 7.6에는 다음과 같은 알려진 문제가 있습니다.

[cols="3*"]
|===
| NetApp 버그 ID | 제목 | 설명 


| 1440718 | SCSI 재검색을 수행하지 않고 LUN을 매핑 해제하거나 매핑하면 호스트에서 데이터가 손상될 수 있습니다. | 'isable_changed_WWID' 다중 경로 구성 매개변수를 Yes로 설정하면 WWID 변경 시 경로 장치에 대한 액세스를 비활성화합니다. 경로 WWID가 다중 경로 장치의 WWID로 복구될 때까지 다중 경로가 경로 장치에 대한 액세스를 비활성화합니다. 자세한 내용은 을 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp 기술 자료: Oracle Linux 7의 iSCSI LUN에서 파일 시스템이 손상되었습니다"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | QLogic QLE2742 어댑터가 있는 OL7U6 호스트의 원격 포트 "없음" 상태로 인해 호스트 검색 중에 LUN을 사용할 수 없습니다 | 호스트 검색 중에 QLogic QLE2742 어댑터가 있는 OL7U6 호스트의 FC(Fibre Channel) 원격 포트 상태가 "없음" 상태로 전환될 수 있습니다. "없음" 상태의 원격 포트로 인해 LUN에 대한 경로를 사용할 수 없게 될 수 있습니다. 스토리지 페일오버 중에 경로 이중화가 감소되어 I/O 중단이 발생할 수 있습니다. 다음 명령을 입력하여 원격 포트 상태를 확인할 수 있습니다. #cat/sys/class/fc_remote_ports/rport- * /port_state 온라인 상태가 온라인 상태가 아닌 온라인 상태로 표시되는 출력의 예입니다 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | 스토리지 페일오버 작업 중 Qlogic(QLE2672) 16GB FC HBA를 사용하여 실행되는 Oracle Linux 7.6에서 커널 중단이 발생합니다 | Qlogic QLE2672 FC(Fibre Channel) HBA(호스트 버스 어댑터)를 사용하는 Oracle Linux 7.6에서 스토리지 페일오버 작업 중에 커널의 패닉이 발생합니다. 커널 패닉이 발생하면 Oracle Linux 7.6이 재부팅되어 애플리케이션이 중단됩니다. kdump 메커니즘이 활성화된 경우 커널 패닉이 /var/crash/ 디렉토리에 있는 vmcore 파일을 생성합니다. vmcore 파일을 분석하여 패닉 원인을 확인할 수 있습니다. 커널이 중단된 후 호스트 OS를 재부팅하고 운영 체제를 복구한 다음 필요에 따라 모든 애플리케이션을 다시 시작할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | 스토리지 페일오버 작업 중에 Qlogic(QLE2742) 32Gb FC HBA를 사용하여 실행되는 Oracle Linux 7.6에서 커널 중단이 발생할 수 있습니다 | Qlogic QLE2742 FC(Fibre Channel) HBA(호스트 버스 어댑터)가 있는 Oracle Linux 7.6에서 스토리지 페일오버 작업 중에 커널의 패닉이 발생할 수 있습니다. 커널 패닉이 발생하면 Oracle Linux 7.6이 재부팅되어 애플리케이션이 중단됩니다. kdump 메커니즘이 활성화된 경우 커널 패닉이 /var/crash/ 디렉토리에 있는 vmcore 파일을 생성합니다. vmcore 파일을 분석하여 패닉 원인을 확인할 수 있습니다. 커널이 중단된 후 호스트 OS를 재부팅하고 운영 체제를 복구한 다음 필요에 따라 모든 애플리케이션을 다시 시작할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | 스토리지 페일오버 작업 중 Emulex(LPe32002-M2) 32Gb FC HBA와 함께 실행되는 Oracle Linux 7.6에서 커널 중단이 발생할 수 있습니다 | Emulex LPe32002-M2 FC(Fibre Channel) HBA(호스트 버스 어댑터)가 있는 Oracle Linux 7.6에서 스토리지 페일오버 작업 중에 커널 패닉이 발생할 수 있습니다. 커널 패닉이 발생하면 Oracle Linux 7.6이 재부팅되어 애플리케이션이 중단됩니다. kdump 메커니즘이 활성화된 경우 커널 패닉이 /var/crash/ 디렉토리에 있는 vmcore 파일을 생성합니다. vmcore 파일을 분석하여 패닉 원인을 확인할 수 있습니다. 커널이 중단된 후 호스트 OS를 재부팅하고 운영 체제를 복구한 다음 필요에 따라 모든 애플리케이션을 다시 시작할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | 스토리지 페일오버 작업 중에 Emulex LPe16002B-M6 16G FC HBA를 사용하여 실행되는 UEK5U2 커널이 있는 Oracle Linux 7.6에서 I/O 진행률이 없습니다 | Emulex LPe16002B-M6 16G FC(Fibre Channel) HBA(호스트 버스 어댑터)를 사용하여 실행되는 UEK5U2 커널이 있는 Oracle Linux 7.6에서 스토리지 페일오버 작업 중에 보고서가 차단되어 I/O 진행이 중지될 수 있습니다. 스토리지 페일오버 작업에서 변경 사항을 "온라인" 상태에서 "차단됨" 상태로 보고하여 읽기 및 쓰기 작업이 지연됩니다. 작업이 성공적으로 완료되면 보고서가 "온라인" 상태로 다시 이동하지 못하고 "차단됨" 상태로 유지됩니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327)을 참조하십시오"^] | 스토리지 페일오버 작업 중에 QLogic QLE2672 16G 호스트의 원격 포트 상태가 차단되었습니다 | 스토리지 페일오버 작업 중에 RHEL(Red Hat Enterprise Linux) 7.6에서 QLogic QLE2672 16G 호스트를 사용하는 FC(Fibre Channel) 원격 포트가 차단될 수 있습니다. 스토리지 노드가 다운될 때 논리 인터페이스가 다운되기 때문에 원격 포트는 스토리지 노드 상태를 차단됨 으로 설정합니다. QLogic QLE2672 16G 호스트와 QLE2742 32Gb 파이버 채널(FC) 호스트 버스 어댑터(HBA)를 모두 실행하는 경우 차단된 포트로 인해 IO 진행이 중지될 수 있습니다. 스토리지 노드가 최적 상태로 돌아오면 논리 인터페이스도 함께 가동되고 원격 포트는 온라인 상태가 됩니다. 그러나 원격 포트는 여전히 차단되어 있을 수 있습니다. 이 차단된 상태는 다중 경로 계층의 LUN에 장애가 발생한 것으로 등록됩니다. 다음 명령을 사용하여 원격 포트의 상태를 확인할 수 있습니다. #cat/sys/class/fc_remote_ports/rport- * /port_stat 차단된 온라인 온라인 온라인 온라인 온라인 온라인 상태의 출력은 다음과 같습니다 
|===