---
sidebar: sidebar 
permalink: hu_rhel_80.html 
keywords: host utilities, red hat, rhel, linux, 8.0, netapp, ontap 
summary: ONTAP와 함께 Red Hat Enterprise Linux 8.0을 사용하는 방법을 설명합니다 
---
= NetApp ONTAP와 함께 Red Hat Enterprise Linux 8.0 사용
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Linux Unified Host Utilities 설치

NetApp Linux Unified Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support 사이트"^] 64비트 .rpm 파일

Linux Unified Host Utilities를 설치하는 것이 좋지만 반드시 설치해야 하는 것은 아닙니다. 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

현재 Linux Unified Host Utilities 버전이 설치되어 있는 경우 또는 를 업그레이드해야 합니다. 이 유틸리티를 제거하고 다음 단계를 따라 최신 버전을 설치해야 합니다.

.단계
. 에서 64비트 Linux Unified Host Utilities 소프트웨어 패키지를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support 사이트"^] 호스트에.
. 다음 명령을 사용하여 소프트웨어 패키지를 설치합니다.
+
"rpm -ivh NetApp_linux_unified_host_utilities-7-1.x86_64"




NOTE: 이 컨텐츠에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== SAN 툴킷을 참조하십시오

이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 자동으로 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN 부팅

SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+
여러 경로는 호스트 OS가 가동되어 경로에서 실행된 후에만 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

RHEL(Red Hat Enterprise Linux) 8.0의 경우 /etc/multipath.conf 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다. RHEL 8.0은 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다.

'multipath -ll' 명령을 사용하여 ONTAP LUN의 설정을 확인할 수 있습니다. 다음 섹션에서는 ASA 및 비 ASA 대상에 매핑된 LUN에 대한 샘플 다중 경로 출력을 제공합니다.



=== 모든 SAN 어레이 구성

모든 SAN 어레이(ASA) 구성에서 지정된 LUN(논리 유닛)에 대한 모든 경로가 활성 및 최적화됩니다. 즉, 모든 경로를 통해 동시에 I/O를 처리할 수 있으므로 성능이 향상됩니다.

다음 예는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 다른 두 개의 경로 그룹이 있어야 합니다. 우선순위가 높은 경로는 Active/Optimized이며, 이는 애그리게이트는 컨트롤러가 서비스를 제공하는 것을 의미합니다. 우선 순위가 낮은 경로는 활성 경로이지만 다른 컨트롤러에서 서비스되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화된 경로를 사용할 수 없는 경우에만 사용됩니다.

다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



== 권장 설정

RHEL 8.0 OS는 ONTAP LUN을 인식하여 ASA 및 비 ASA 구성 모두에 대해 모든 구성 매개 변수를 올바르게 자동 설정하도록 컴파일됩니다.

다중경로 데몬을 시작하려면 'multipath.conf' 파일이 있어야 하지만 'touch/etc/multipath.conf' 명령을 사용하여 빈 0바이트 파일을 생성할 수 있습니다

이 파일을 처음 생성할 때 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
다중 경로로 관리하지 않으려는 장치가 있거나 기본값을 덮어쓰는 기존 설정이 없는 경우 외에는 multipath.conf 파일에 아무것도 직접 추가할 필요가 없습니다.

다음 구문을 'multitpath.conf' 파일에 추가하여 원치 않는 디바이스를 제외할 수 있습니다.

'<DevID>'을(를) 제외할 장치의 WWID 문자열로 바꿉니다. 다음 명령을 사용하여 WWID를 확인하십시오.

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
이 예에서는 `sda` 블랙리스트에 추가해야 하는 로컬 SCSI 디스크입니다.

.단계
. 다음 명령을 실행하여 WWID를 확인하십시오.
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. 이 WWID를 '/etc/multipath.conf'의 블랙리스트 스탠자에 추가합니다.
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


기본 설정을 재정의할 수 있는 기본 섹션에서 항상 '/etc/multipath.conf' 파일에서 기존 설정을 확인해야 합니다.

아래 표에는 ONTAP LUN에 대한 중요 매개 변수와 필요한 값이 나와 있습니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 재정의될 경우 ONTAP LUN에 특별히 적용되는 'multipath.conf'에서 나중에 stanzas로 수정해야 합니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp 및/또는 OS 공급업체에 문의하여 영향을 완전히 이해해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "2 pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| no_path_retry 를 선택합니다 | 대기열 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN. * 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 'multitpath.conf' 파일은 ONTAP LUN과 호환되지 않는 path_checker와 no_path_retry의 값을 정의합니다. 호스트에 아직 연결된 다른 SAN 스토리지 때문에 제거할 수 없는 경우 이러한 매개 변수를 디바이스 스탠자가 있는 ONTAP LUN에 대해 특별히 수정할 수 있습니다.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== KVM 설정

권장 설정을 사용하여 KVM(커널 기반 가상 시스템)도 구성할 수 있습니다. LUN이 하이퍼바이저에 매핑되므로 KVM을 구성하는 데 필요한 변경 사항은 없습니다.



== 알려진 문제 및 제한 사항

[cols="4*"]
|===
| NetApp 버그 ID | 제목 | 설명 | Bugzilla ID입니다 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1238719["1238719)를 참조하십시오"^] | 스토리지 페일오버 작업 중 RHEL8에서 QLogic QLE2672 16GB FC의 커널 중단 | 커널 중단은 QLogic QLE2672 HBA(호스트 버스 어댑터)가 있는 RHEL(Red Hat Enterprise Linux) 8 커널에서 스토리지 페일오버 작업 중에 발생할 수 있습니다. 커널이 중단되면 운영 체제가 재부팅됩니다. kdump가 구성된 경우 재부팅으로 인해 애플리케이션이 중단되고 /var/crash/ 디렉토리 아래에 vmcore 파일이 생성됩니다. vmcore 파일을 사용하여 장애의 원인을 식별합니다. 이 경우 "kmem_cache_alloc+160" 모듈에서 중단이 발생한 것입니다. vmcore 파일에 "[exception RIP: kmem_cache_alloc+160]" 문자열을 사용하여 기록됩니다. 호스트 OS를 재부팅하여 운영 체제를 복구한 다음 애플리케이션을 재시작합니다. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1710009["1710009"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1226783["1226783을 참조하십시오"^] | RHEL8 OS는 204개 이상의 SCSI 장치가 모든 FC(Fibre Channel) HBA(호스트 버스 어댑터)에 매핑될 때 "비상 모드"로 부팅됩니다. | 운영 체제 재부팅 프로세스 중에 호스트가 204개 이상의 SCSI 장치와 매핑된 경우 RHEL8 OS가 "정상 모드"로 부팅되지 않고 "긴급 모드"로 전환됩니다. 이로 인해 대부분의 호스트 서비스를 사용할 수 없게 됩니다. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1690356["1690356)을 참조하십시오"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1230882["1230882"^] | RHEL8 설치 중에 iSCSI 다중 경로 장치에 파티션을 생성할 수 없습니다. | iSCSI SAN LUN 다중 경로 장치는 RHEL 8 설치 중에 디스크 선택에 표시되지 않습니다. 따라서 SAN 부팅 장치에서 다중 경로 서비스가 활성화되지 않습니다. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1235998["1235998)을 참조하십시오"^] | "rescan-scsi-bus.sh -a" 명령은 328개 이상의 장치를 검색하지 않습니다 | 328개 이상의 SCSI 장치가 있는 Red Hat Enterprise Linux 8 호스트가 매핑되는 경우 호스트 OS 명령 "rescan-scsi-bus.sh -A"는 328개의 장치만 검색합니다. 호스트가 나머지 매핑된 디바이스를 검색하지 않습니다. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231087["1231087"^] | 스토리지 페일오버 작업 중 RHEL8에서 Emulex LPe16002 16GB FC를 사용하여 원격 포트를 차단 상태로 전환합니다 | 스토리지 페일오버 작업 중 RHEL8에서 Emulex LPe16002 16GB 파이버 채널(FC)을 사용하여 원격 포트를 차단 상태로 전환합니다. 스토리지 노드가 최적 상태로 돌아가면 LIF도 함께 올라가고 원격 포트 상태가 "온라인"으로 표시되어야 합니다. 원격 포트 상태가 계속 "차단됨" 또는 "없음"으로 표시될 수 있습니다. 이 상태에서는 다중 경로 계층의 LUN에 대한 "장애 발생" 경로가 발생할 수 있습니다 | link:https://bugzilla.redhat.com/show_bug.cgi?id=1702005["1702005"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231098["1231098"^] | 스토리지 페일오버 작업 중 Emulex LPe32002 32Gb FC를 사용하여 RHEL8에서 원격 포트를 차단 상태로 전환합니다 | 스토리지 페일오버 작업 중 Emulex LPe32002 32GB파이버 채널(FC)을 사용하여 RHEL8에서 원격 포트를 차단 상태로 전환합니다. 스토리지 노드가 최적 상태로 돌아가면 LIF도 함께 올라가고 원격 포트 상태가 "온라인"으로 표시되어야 합니다. 원격 포트 상태가 계속 "차단됨" 또는 "없음"으로 표시될 수 있습니다. 이 상태에서는 다중 경로 계층의 LUN에 대한 "장애 발생" 경로가 발생할 수 있습니다. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1705573["1705573"^] 
|===


== 릴리즈 노트



=== ASM 미러링

ASM 미러링은 ASM이 문제를 인식하고 대체 장애 그룹으로 전환할 수 있도록 Linux 다중 경로 설정을 변경해야 할 수 있습니다. ONTAP의 대다수 ASM 구성은 외부 이중화를 사용하는데, 이는 외부 어레이를 통해 데이터가 보호되고 ASM은 데이터를 미러링하지 않는다는 뜻입니다. 일부 사이트는 ASM에서 일반적인 수준의 이중화를 사용하며 일반적으로 여러 사이트에 걸쳐 양방향 미러링을 제공합니다. 을 참조하십시오 link:https://www.netapp.com/us/media/tr-3633.pdf["ONTAP 기반의 Oracle 데이터베이스"^] 를 참조하십시오.
