---
sidebar: sidebar 
permalink: hu_rhel_93.html 
keywords: host utilities, red hat, rhel, linux, 9.3, netapp, ontap, rhel 
summary: ONTAP에서 Red Hat Enterprise Linux 9.3을 사용하는 방법을 설명합니다 
---
= ONTAP와 함께 Red Hat Enterprise Linux 9.3을 사용하십시오
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SAN 호스트 구성 설정을 사용하여 ONTAP가 포함된 Red Hat Enterprise Linux 9.3을 대상으로 구성할 수 있습니다.



== Linux Unified Host Utilities를 설치합니다

NetApp Linux Unified Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^] 64비트 .rpm 파일

NetApp은 Linux 통합 호스트 유틸리티를 설치할 것을 적극 권장하지만 반드시 설치할 필요는 없습니다. 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

.필요한 것
현재 Linux Unified Host Utilities 버전이 설치되어 있는 경우 업그레이드 또는 제거한 다음 다음 다음 단계에 따라 최신 버전을 설치해야 합니다.

.단계
. 에서 64비트 Linux Unified Host Utilities 소프트웨어 패키지를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^] 호스트에.
. 소프트웨어 패키지를 설치합니다.
+
"rpm -ivh NetApp_linux_unified_host_utilities-7-1.x86_64"





== SAN 툴 키트

NetApp 호스트 유틸리티 패키지를 설치하면 도구 키트가 자동으로 설치됩니다. 이 키트는 를 제공합니다 `sanlun` 유틸리티를 사용하여 LUN 및 HBA를 관리할 수 있습니다. 를 클릭합니다 `sanlun` 명령을 실행하면 호스트에 매핑된 LUN에 대한 정보, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보가 반환됩니다.

다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[source, cli]
----
# sanlun lun show all
----
* 출력 예: *

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdb	Host11  FCP        10g	cDOT
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdx	Host11  FCP        10g	cDOT
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdbt  host12 FCP        10g	cDOT
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdax	host12  FCP        10g	cDOT
----


== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] OS, HBA, HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 OS가 가동되고 경로에서 실행되면 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅에 성공했는지 확인합니다.




== 다중 경로

RHEL(Red Hat Enterprise Linux) 9.3의 경우 `/etc/multipath.conf` 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다. RHEL 9.3은 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다.

'multipath -ll' 명령을 사용하여 ONTAP LUN의 설정을 확인할 수 있습니다. 다음 섹션에서는 ASA 및 비 ASA 대상에 매핑된 LUN에 대한 샘플 다중 경로 출력을 제공합니다.



=== 모든 SAN 어레이 구성

모든 SAN 어레이(ASA) 구성에서 지정된 LUN에 대한 모든 경로가 활성 및 최적화됩니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

.예
다음 예는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a098038314359725d516c69733471 dm-22 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:3:0  sdau 66:224 active ready running
  |- 12:0:4:0  sdco 69:192 active ready running
  |- 12:0:0:0  sdav 66:240 active ready running
  `- 11:0:2:0  sdat 66:208 active ready running
----

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선순위가 높은 경로는 Active/Optimized이며, 이는 애그리게이트는 컨트롤러가 서비스를 제공하는 것을 의미합니다. 우선 순위가 낮은 경로는 활성 경로이지만 다른 컨트롤러에서 서비스되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화된 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a0980383149783224544d334a644d dm-10 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 12:0:0:18 sdbj 67:208 active ready running
| `- 11:0:1:18 sdan 66:112 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:18 sdt  65:48  active ready running
  `- 12:0:3:18 sdcf 69:48  active ready running

----

NOTE: 단일 LUN에 너무 많은 경로를 사용하지 마십시오. 경로가 4개 이상 필요하지 않습니다. 8개 이상의 경로로 인해 스토리지 장애가 발생했을 때 경로 문제가 발생할 수 있습니다.



== 권장 설정

RHEL 9.3 OS는 ONTAP LUN을 인식하도록 컴파일되며 자동으로 ASA 및 비 ASA 구성 모두에 대해 모든 구성 매개 변수를 올바르게 설정합니다. 다음과 같은 권장 설정을 사용하여 호스트 구성의 성능을 더욱 최적화할 수 있습니다.

를 클릭합니다 `multipath.conf` 다중 경로 데몬을 시작하려면 파일이 있어야 하지만 다음 명령을 사용하여 빈 0바이트 파일을 생성할 수 있습니다.

`touch /etc/multipath.conf`

이 파일을 처음 생성할 때 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* 에 직접 추가할 필요는 없습니다 `multipath.conf` 파일 - 다중 경로를 통해 관리하지 않으려는 장치가 있거나 기본값을 재정의하는 기존 설정이 없는 경우
* 원치 않는 디바이스를 제외하려면 에 다음 구문을 추가합니다 `multipath.conf` 파일.
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
를 교체합니다 `<DevId>` 를 사용하여 `WWID` 제외할 장치의 문자열입니다.

+
.예
이 예에서는 디바이스의 WWID를 확인하고 에 추가합니다 `multipath.conf` 파일.

+
.단계
.. 다음 명령을 실행하여 WWID를 확인하십시오.
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` 블랙리스트에 추가해야 하는 로컬 SCSI 디스크입니다.

.. 를 추가합니다 `WWID` 에서 블랙리스트로 `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----




을 항상 확인해야 합니다 `/etc/multipath.conf` 기본 설정을 재정의할 수 있는 레거시 설정 파일(특히 기본값 섹션에 있음)

다음 표에서는 위험 요소를 보여 줍니다 `multipathd` ONTAP LUN에 대한 매개 변수 및 필수 값입니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 재정의될 경우 에서 나중에 Stanzas를 사용하여 수정해야 합니다 `multipath.conf` ONTAP LUN에 특별히 적용되는 파일입니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp 및/또는 OS 공급업체와 상담할 때만 재정의되어야 하며, 그 영향이 완전히 이해될 때만 재정의되어야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "2 pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| no_path_retry 를 선택합니다 | 대기열 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN. * 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우, 입니다 `multipath.conf` 파일은 에 대한 값을 정의합니다 `path_checker` 및 `no_path_retry` ONTAP LUN과 호환되지 않습니다. 다른 SAN 스토리지가 아직 호스트에 연결되어 있으므로 제거할 수 없는 경우 이러한 매개 변수를 특히 디바이스 스탠자가 있는 ONTAP LUN에 대해 수정할 수 있습니다.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry    queue
      path_checker     tur
   }
}
----


=== KVM 설정

권장 설정을 사용하여 KVM(커널 기반 가상 시스템)도 구성할 수 있습니다. LUN이 하이퍼바이저에 매핑되므로 KVM을 구성하는 데 필요한 변경 사항은 없습니다.



== 알려진 문제

RHEL 9.3과 ONTAP 릴리스의 알려진 문제는 다음과 같습니다.

[cols="20, 20, 50,20"]
|===
| NetApp 버그 ID | 제목 | 설명 | Jira ID입니다 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^] | NetApp Linux 호스트 유틸리티 CLI에서 Emulex HBA(호스트 버스 어댑터) 어댑터 검색을 지원하려면 추가 라이브러리 패키지 종속성이 필요합니다 | RHEL 9.x에서 NetApp Linux SAN 호스트 유틸리티 CLI `sanlun fcp show adapter -v` Emulex HBA(호스트 버스 어댑터) 검색을 지원하기 위한 라이브러리 패키지 종속성을 찾을 수 없기 때문에 실패합니다. | 해당 없음 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1593771["1593771"^] | Red Hat Enterprise Linux 9.3 QLogic SAN 호스트가 스토리지 이동성 작업 중에 부분 다중 경로 손실이 발생합니다 | ONTAP 스토리지 컨트롤러 테이크오버 작동 중에 다중 경로의 절반이 중단되거나 페일오버 모드로 전환된 다음 반환 워크플로우 중에 전체 경로 수로 복구해야 합니다. 하지만 RHEL(Red Hat Enterprise Linux) 9.3 QLogic 호스트를 사용하면 스토리지 페일오버 기브백 작업 후에 부분 다중 경로만 복구됩니다. | RHEL 17811을 참조하십시오 
|===