---
sidebar: sidebar 
permalink: hu_rhel_70.html 
keywords: host utilities, red hat, rhel, linux, 7.0, netapp, ontap 
summary: ONTAP와 함께 Red Hat Enterprise Linux 7.0을 사용하는 방법에 대해 설명합니다 
---
= ONTAP와 함께 Red Hat Enterprise Linux 7.0을 사용하십시오
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SAN 호스트 구성 설정을 사용하여 ONTAP를 대상으로 Red Hat Enterprise Linux 7.0을 구성할 수 있습니다.



== Linux Unified Host Utilities를 설치합니다

NetApp Linux 통합 호스트 유틸리티 소프트웨어 패키지는 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^]32비트 및 64비트 .rpm 파일에서 제공됩니다. 구성에 적합한 파일을 모르는 경우 를 사용하여 필요한 파일을 link:https://mysupport.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴"^]확인합니다.

NetApp은 Linux 통합 호스트 유틸리티를 설치할 것을 적극 권장하지만 필수는 아닙니다. 이 유틸리티는 Linux 호스트의 설정을 변경하지 않습니다. 유틸리티를 사용하면 관리를 개선하고 NetApp 고객 지원 이 귀사의 구성 정보를 수집할 수 있도록 지원합니다.

현재 Linux Unified Host Utilities가 설치되어 있는 경우 최신 버전으로 업그레이드하거나 제거한 후 다음 단계에 따라 최신 버전을 설치해야 합니다.

.단계
. 에서 32비트 또는 64비트 Linux Unified Host Utilities 소프트웨어 패키지를 다운로드합니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^] 호스트에.
. 소프트웨어 패키지를 설치합니다.
+
"rpm -ivh NetApp_linux_unified_host_utilities-7-1.x86_64"




NOTE: 이 문서에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== SAN 툴킷을 참조하십시오

이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 자동으로 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[source, cli]
----
# sanlun lun show all
----
예제 출력:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=68128;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 운영 체제가 실행된 후 경로에서 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

RHEL(Red Hat Enterprise Linux) 7.0의 경우 /etc/multipath.conf 파일이 있어야 하지만 파일을 구체적으로 변경할 필요는 없습니다. RHEL 7.0은 ONTAP LUN을 인식하고 올바르게 관리하는 데 필요한 모든 설정으로 컴파일됩니다.

'multipath -ll' 명령을 사용하여 ONTAP LUN의 설정을 확인할 수 있습니다.

다음 섹션에서는 ASA 및 비 ASA 대상에 매핑된 LUN에 대한 다중 경로 출력 예를 제공합니다.



=== 모든 SAN 어레이 구성

모든 SAN 어레이(ASA) 구성에서 지정된 LUN에 대한 모든 경로가 활성 및 최적화됩니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

.예
다음 예는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상인 경우 스토리지 장애 시 경로 문제가 발생할 수 있습니다.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 경로는 활성/최적화입니다. 즉, 애그리게이트가 위치한 컨트롤러에 의해 처리됩니다. 우선 순위가 낮은 경로는 활성 상태이지만 다른 컨트롤러에서 제공되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: 단일 LUN에는 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상인 경우 스토리지 장애 시 경로 문제가 발생할 수 있습니다.



== 권장 설정

RHEL 7.0 OS는 ONTAP LUN을 인식하여 ASA 및 비 ASA 구성 모두에 대해 모든 구성 매개 변수를 올바르게 자동 설정하도록 컴파일됩니다.

 `multipath.conf`다중 경로 데몬을 시작하려면 파일이 있어야 합니다. 이 파일이 없는 경우 명령을 사용하여 0바이트 빈 파일을 만들 수 `touch /etc/multipath.conf` 있습니다.

 `multipath.conf`파일을 처음 만들 때 다음 명령을 사용하여 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

다중 경로를 관리하지 않으려는 장치가 있거나 기본값을 재정의하는 기존 설정이 없는 경우 파일에 직접 아무것도 추가할 필요가 `multipath.conf` 없습니다. 원치 않는 디바이스를 제외하려면 `multipath.conf` 파일에 다음 구문을 추가하여 <DevId>를 제외할 디바이스의 WWID 문자열로 대체합니다.

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
다음 예에서는 디바이스의 WWID를 확인하여 `multipath.conf` 파일에 추가합니다.

.단계
. WWID 확인:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` 블랙리스트에 추가할 로컬 SCSI 디스크입니다.

. 를 추가합니다 `WWID` 에서 블랙리스트로 `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


 항상기본 설정을 무시할 수 있는 레거시 설정은 확인해야 `/etc/multipath.conf` 파일, 특히 기본값 섹션에서 합니다.

다음 표에서는 `multipathd` ONTAP LUN에 대한 중요 매개 변수와 필요한 값을 보여 줍니다. 호스트가 다른 공급업체의 LUN에 접속되어 있고 이러한 매개 변수 중 하나라도 재정의되면 `multipath.conf` ONTAP LUN에 특별히 적용되는 파일에서 이후의 stanzas로 수정되어야 합니다. 이 수정 사항이 없으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp, OS 공급업체 또는 둘 다와 상의하고 영향을 완전히 이해할 때만 재정의해야 합니다.

[cols="2*"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "3 queue_if_no_path pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| no_path_retry 를 선택합니다 | 대기열 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN. * 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
.예
다음 예제에서는 재정의된 기본값을 수정하는 방법을 보여 줍니다. 이 경우 'multitpath.conf' 파일은 ONTAP LUN과 호환되지 않는 path_checker와 no_path_retry의 값을 정의합니다. 호스트에 아직 연결된 다른 SAN 스토리지 때문에 제거할 수 없는 경우 이러한 매개 변수를 디바이스 스탠자가 있는 ONTAP LUN에 대해 특별히 수정할 수 있습니다.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== KVM 설정

권장 설정을 사용하여 KVM(커널 기반 가상 시스템)도 구성할 수 있습니다. LUN이 하이퍼바이저에 매핑되므로 KVM을 구성하는 데 필요한 변경 사항은 없습니다.



== 알려진 문제

ONTAP가 포함된 RHEL 7.0 릴리스에는 다음과 같은 알려진 문제가 있습니다.

[cols="3*"]
|===
| NetApp 버그 ID | 제목 | 설명 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=844417["844417"^] | 스토리지 페일오버 작업이 수행되는 I/O 중에 Emulex 16G FC(LPe16002B-M6) 호스트가 충돌합니다 | 스토리지 페일오버 작업 중 I/O에서 16G FC Emulex(LPe16002B-M6) 호스트 충돌이 관찰될 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=811587["811587)을 참조하십시오"^] | 스토리지 페일오버 작업이 수행되는 I/O 중에 Emulex 16G FC(LPe16002B-M6) 호스트가 충돌합니다 | 스토리지 페일오버 작업 중 I/O에서 16G FC Emulex(LPe16002B-M6) 호스트 충돌이 관찰될 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=803071["803071"^] | 스토리지 페일오버 작업이 수행되는 I/O 중에 Emulex 16G FC(LPe16002B-M6) 호스트가 충돌합니다 | 스토리지 페일오버 작업 중 I/O에서 16G FC Emulex(LPe16002B-M6) 호스트 충돌이 관찰될 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=820163["820163"^] | 스토리지 페일오버 작업이 있는 I/O에서 QLogic 호스트 중단 또는 경로 장애가 관찰되었습니다 | 스토리지 페일오버 작업 중 입출력 중에 QLogic 호스트에서 호스트 중단 또는 경로 장애가 발생할 수 있습니다. 이러한 경우 "Mailbox cmd timeout occurred, cmd=0x54, MB[0]=0x54 and Firmware dump saved to temp buffer"(사서함 cmd 시간 초과 발생, cmd=0x54, MB[0]=0x54 및 펌웨어 덤프가 임시 버퍼에 저장됨)" 메시지가 나타나고 호스트 멈춤/경로 오류가 발생할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799323["799323"^] | Emulex FCoE(OCe10102-FX-D) 호스트 중단 또는 경로 장애가 스토리지 페일오버 작업 중 I/O에서 관찰되었습니다 | 스토리지 페일오버 작업이 포함된 I/O에서 Emulex 10G FCoE 호스트(OCe10102-FX-D)의 호스트 중단 또는 경로 장애가 관찰될 수 있습니다. 이러한 경우 "드라이버 버퍼 풀이 비어 있음, IO 버스 작동 및 SCSI 계층 I/O 중단 요청 상태" 메시지가 나타나면서 호스트 중단/경로 오류가 발생할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=849212["849212)를 참조하십시오"^] | Emulex 16G FC(LPe16002B-M6) 호스트 중단 또는 경로 장애가 스토리지 페일오버 작업 중 I/O에서 관찰되었습니다 | 스토리지 페일오버 작업이 수행되는 I/O 중에 Emulex 16G FC(LPe16002B-M6) 호스트에서 호스트 중단 또는 경로 장애가 관찰될 수 있습니다. 이러한 경우 "RSCN timeout Data and iotag x1301 is out of range: max iotag" 메시지가 나타나면서 호스트 중단/경로 오류가 발생할 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836800["836800"^] | RHEL 7.0 OS 설치 중에 로그인이 성공하더라도 Anaconda는 iSCSI 로그인 실패 메시지를 표시합니다 | iSCSI 다중 경로(iSCI) LUN에 루트(/)를 설치할 때 이더넷 인터페이스의 IP 주소가 커널 명령줄에 지정되어 iSCSI 서비스가 시작되기 전에 IP 주소가 할당됩니다. 그러나 iSCSI 서비스가 시작되기 전에 dracut은 부팅 중에 모든 이더넷 포트에 IP 주소를 할당할 수 없습니다. 이로 인해 IP 주소가 없는 인터페이스에서 iSCSI 로그인이 실패합니다. iSCSI 서비스가 로그인을 여러 번 시도하여 OS 부팅 시간이 지연되는 것을 볼 수 있습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836875["836875"^] | iSCSI 다중 경로 LUN에 설치된 RHEL 7.0 OS를 부팅하는 동안 IP 주소가 항상 할당되는 것은 아닙니다 | RHEL 7.0을 설치할 때 anaconda 설치 화면에 iSCSI 로그인이 성공적임에도 여러 대상 IP에 대한 iSCSI 로그인이 실패했음을 표시합니다. Anaconda는 다음과 같은 오류 메시지를 표시합니다. "노드 로그인 실패" iSCSI 로그인에 대해 여러 대상 IP를 선택한 경우에만 이 오류가 발생합니다. "확인" 버튼을 클릭하여 OS 설치를 계속할 수 있습니다. 이 버그는 iSCSI 또는 RHEL 7.0 OS 설치를 방해하지 않습니다. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836657["836657"^] | Anaconda는 커널 cmd 행에 bootdev 인수를 추가하지 않고 iSCSI 다중 경로 dun LUN에 설치된 RHEL 7.0 OS의 IP 주소를 설정합니다 | Anaconda는 커널 명령줄에 bootdev 인수를 추가하지 않습니다. 여기서 iSCSI 다중 경로 dl에 RHEL 7.0 OS를 설치하는 동안 IPv4 주소를 설정합니다. 따라서 RHEL 7.0 부팅 중에 스토리지 서브시스템과 iSCSI 세션을 설정하도록 구성된 이더넷 인터페이스에 IP 주소를 할당하지 못합니다. iSCSI 세션이 설정되지 않았으므로 OS 부팅 시 루트 LUN이 검색되지 않아 OS 부팅이 실패합니다. 
|===