---
sidebar: sidebar 
permalink: hu_solaris_114.html 
keywords: host utilities, solaris, 114, netapp, ontap 
summary: ONTAP와 함께 IBM AIX 7.2 및/또는 PowerVM VIOS 3.1을 사용하는 방법에 대해 설명합니다 
---
= ONTAP와 함께 Solaris 11.4를 사용합니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP SAN 호스트 구성 설정을 사용하여 ONTAP를 대상으로 Solaris 11.4를 구성할 수 있습니다.



== Solaris 호스트 유틸리티를 설치합니다

에서 Host Utilities 소프트웨어 패키지가 포함된 압축 파일을 다운로드할 수 있습니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support 사이트"^]. 파일을 다운로드한 후 Host Utilities를 설치하는 데 필요한 소프트웨어 패키지를 가져오려면 zip 파일의 압축을 풀어야 합니다.

.단계
. 에서 Host Utilities가 포함된 압축 파일 사본을 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support 사이트"^] 호스트의 디렉토리로 이동합니다.
. 다운로드가 포함된 디렉터리로 이동합니다.
. 파일의 압축을 풉니다.
+
다음 예에서는 SPARC 시스템에 대한 파일의 압축을 해제합니다. x86-64 플랫폼의 경우 를 사용합니다 `x86/x64` 패키지.

+
'gunzip netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar.gz'

. 를 사용합니다 `tar xvf` 명령을 사용하여 파일을 추출합니다.
+
'tar xvf netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar'

. tar 파일에서 추출한 패키지를 호스트에 추가합니다.
+
pkgadd-d NTAPtaggool.pkg

+
패키지는 '/opt/ntap/soolkit/bin' 디렉토리에 추가됩니다.

+
설치를 완료하려면 를 사용하여 사용자 환경에 대한 호스트 매개 변수(이 경우 Oracle Solaris I/O Multipathing 또는 MPxIO)를 구성해야 합니다 `host_config` 명령.

+
'host_config' 명령의 형식은 다음과 같습니다.

+
'/opt/ntap/soolkit/bin/host_config <-setup><-protocol fcp | iscsi | mixed><-multipath mpxio | dmp | non>[-noalua][-MCC 60|90|120]'

+
'host_config' 명령은 다음과 같은 작업을 수행합니다.

+
** x86 및 SPARC 시스템에 대한 FC 및 SCSI 드라이버 설정을 변경합니다
** 두 MPxIO 구성에 대한 SCSI 시간 초과 설정을 제공합니다
** VID/PID 정보를 설정합니다
** ALUA를 설정하거나 해제합니다
** x86 및 SPARC 시스템 모두에 대해 MPxIO 및 SCSI 드라이버에 사용되는 ALUA 설정을 구성합니다


. 호스트를 재부팅합니다.




== SAN 툴킷

NetApp 호스트 유틸리티 패키지를 설치하면 도구 키트가 자동으로 설치됩니다. 이 키트는 를 제공합니다 `sanlun` 유틸리티를 사용하여 LUN 및 HBA를 관리할 수 있습니다. 를 클릭합니다 `sanlun` 명령을 실행하면 호스트에 매핑된 LUN에 대한 정보, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보가 반환됩니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
#sanlun lun show

controller(7mode)/                 device                                            host             lun
vserver(Cmode)     lun-pathname    filename                                         adapter protocol  size  mode
------------------------------------------------------------------------------------------------------
data_vserver       /vol/vol1/lun1  /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2  qlc1  FCP       60g   C
data_vserver       /vol/vol2/lun2  /dev/rdsk/c0t600A098038314362705D51465A626475d0s2  qlc1  FCP       20g   C
----


== SAN 부팅

.필요한 것
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용할 수 있습니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] 사용 중인 OS, HBA, HBA 펌웨어 및 HBA 부팅 BIOS, ONTAP 버전이 지원되는지 확인합니다.

SAN 부팅은 Solaris 호스트의 부팅 장치로 SAN 연결 디스크(LUN)를 설정하는 프로세스입니다.

FC 프로토콜을 사용하고 Solaris Host Utilities를 실행하여 Solaris MPxIO 환경에서 작동하도록 SAN 부팅 LUN을 설정할 수 있습니다. SAN 부팅 LUN을 설정하는 방법은 볼륨 관리자 및 파일 시스템에 따라 다를 수 있습니다. 을 참조하십시오 link:hu_solaris_62.html["Solaris 호스트 유틸리티를 설치합니다"] Solaris MPIO(다중 경로 I/O) 환경의 SAN 부팅 LUN에 대한 자세한 내용은 을 참조하십시오.



== 다중 경로

다중 경로를 사용하면 호스트와 스토리지 시스템 간의 여러 네트워크 경로를 구성할 수 있습니다. 한 경로에 장애가 발생하면 트래픽이 나머지 경로에서 계속됩니다. Solaris 11.4에서는 Oracle Solaris I/O Multipathing 또는 MPxIO가 기본적으로 사용됩니다. 의 기본 설정입니다 `/kernel/drv/fp.conf` mpxio-disable="no"로 변경합니다.



=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선순위가 높은 경로는 Active/Optimized이며, 이는 애그리게이트는 컨트롤러가 서비스를 제공하는 것을 의미합니다. 우선 순위가 낮은 경로는 활성 경로이지만 다른 컨트롤러에서 서비스되기 때문에 최적화되지 않습니다. 최적화되지 않은 경로는 최적화된 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

OS native mpathadm show lu <lun>' 명령의 각 LUN에 대한 * 액세스 상태 * 섹션에 대해 경로 우선 순위가 표시됩니다.



=== 모든 SAN 어레이 구성

ASA 구성에서는 지정된 LUN에 대한 모든 경로가 활성화되어 최적화되어 있습니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

.예
다음 예는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

'sanlun' 명령의 출력은 ASA 및 non-ASA 구성과 동일합니다.

OS native mpathadm show lu <lun>' 명령의 각 LUN에 대한 * 액세스 상태 * 섹션에 대해 경로 우선 순위가 표시됩니다.

[listing]
----
#sanlun lun show -pv sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun

                    ONTAP Path: sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun
                           LUN: 0
                      LUN Size: 30g
                   Host Device: /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

NOTE: Solaris 호스트에 대한 ONTAP 9.8부터 모든 SAN 어레이(ASA) 구성이 지원됩니다.



== 권장 설정

NetApp은 NetApp ONTAP LUN에 Solaris 11.4 SPARC 및 x86_64에 대해 다음 매개 변수 설정을 사용할 것을 권장합니다. 이러한 매개 변수 값은 Host Utilities에서 설정합니다. Solaris 11.4 시스템 설정에 대한 자세한 내용은 Oracle DOC ID: 2595926.1을 참조하십시오.

[cols="2*"]
|===
| 매개 변수 | 값 


| throttle_max | 8 


| 준비 안 됨_재시도 | 300 


| busy_reTRIES입니다 | 30 


| reset_retries(재시도 재설정 | 30 


| throttle_min | 2 


| timeout_reTRIES | 10 


| 물리적_블록_크기 | 4096 
|===
모든 Solaris OS 버전(Solaris 10.x 및 Solaris 11.x 포함)은 Solaris HUK 6.2를 지원합니다.

* Solaris 11.4의 경우 FC 드라이버 바인딩이 에서 변경됩니다 `ssd` 를 선택합니다 `sd`. 다음 구성 파일은 HUK 6.2 설치 프로세스 중에 부분적으로 업데이트됩니다.
+
** `/kernel/drv/sd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Solaris 11.3의 경우 FC 드라이버 바인딩이 을 사용합니다 `ssd`. 다음 구성 파일은 HUK 6.2 설치 프로세스 중에 부분적으로 업데이트됩니다.
+
** `/kernel/drv/ssd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Solaris 10.x의 경우 HUK 6.2 설치 프로세스 중에 다음 구성 파일이 완전히 업데이트됩니다.
+
** `/kernel/drv/sd.conf`
** `/kernel/drv/ssd.conf`
** `/kernel/drv/scsi_vhci.conf`




구성 문제를 해결하려면 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_the_Solaris_Host_recommendations_for_Supporting_HUK_6.2["HUK 6.2를 지원하기 위한 Solaris 호스트 권장 사항은 무엇입니까"^].

NetApp은 NetApp LUN을 사용하는 zpool에서 4KB 정렬 I/O를 성공적으로 수행하려면 다음을 권장합니다.

* 4KB I/O 크기 정렬을 지원하는 모든 Solaris 기능을 사용할 수 있는지 확인하기 위해 최신 Solaris OS를 실행하고 있는지 확인합니다.
* Solaris 10 업데이트 11에 최신 커널 패치가 설치되어 있고 Solaris 11.4에는 최신 SRU(지원 리포지토리 업데이트)가 설치되어 있는지 확인합니다.
* NetApp 논리 유닛에는 이 있어야 합니다 `lun/host-type` 현재 `Solaris` LUN 크기에 관계없이




=== MetroCluster에 대한 권장 설정입니다

기본적으로 Solaris OS는 LUN에 대한 모든 경로가 손실되면 * 20 * 이후 I/O 작업을 실행하지 못합니다. 이 기능은 에 의해 제어됩니다 `fcp_offline_delay` 매개 변수. 의 기본값입니다 `fcp_offline_delay` 표준 ONTAP 클러스터에 적합합니다. 그러나 MetroCluster 구성에서 의 값은 입니다 `fcp_offline_delay` 계획되지 않은 페일오버를 포함하여 작업 중에 I/O가 중간에 시간 초과되지 않도록 하려면 * 120초 * 로 늘려야 합니다. 기본 설정에 대한 추가 정보 및 권장 변경 사항은 기술 자료 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["MetroCluster 구성에서 Solaris 호스트 지원 고려 사항"^].



== Oracle Solaris 가상화

* Solaris 가상화 옵션에는 Solaris Logical Domains(LDOM 또는 SPARC용 Oracle VM Server), Solaris Dynamic Domains, Solaris Zones 및 Solaris Containers가 있습니다. 이러한 기술은 다른 아키텍처를 기반으로 한다는 사실에도 불구하고 일반적으로 "Oracle Virtual Machines"로 브랜드가 변경되었습니다.
* 경우에 따라 특정 Solaris 논리적 도메인 내의 Solaris 컨테이너와 같은 여러 옵션을 함께 사용할 수 있습니다.
* NetApp은 일반적으로 전체 구성이 Oracle에서 지원되며 LUN에 직접 액세스할 수 있는 파티션이 에 나와 있는 가상화 기술의 사용을 지원합니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스"^] 를 클릭합니다. 여기에는 루트 컨테이너, LDOM I/O 도메인 및 NPIV를 사용한 LDOM이 포함됩니다.
* 와 같은 가상화된 스토리지 리소스만 사용하는 파티션 또는 가상 머신 `vdsk`NetApp LUN에 직접 액세스할 수 없으므로 특정 조건이 필요하지 않습니다. LDOM I/O 도메인과 같이 기본 LUN에 직접 액세스할 수 있는 파티션 또는 가상 머신만 에서 찾아야 합니다 link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].




=== 가상화에 권장되는 설정입니다

LDOM 내에서 LUN을 가상 디스크 디바이스로 사용할 경우 LUN의 소스는 가상화를 통해 마스킹되고 LDOM은 블록 크기를 제대로 감지하지 못합니다. 이 문제를 방지하려면 _Oracle Bug 15824910_ 및 에 대해 LDOM OS를 패치해야 합니다 `vdc.conf` 가상 디스크의 블록 크기를 로 설정하는 파일을 생성해야 합니다 `4096`. 자세한 내용은 Oracle DOC:2157669.1을 참조하십시오.

패치를 확인하려면 다음을 수행합니다.

.단계
. zpool을 생성합니다.
. 실행 `zdb -C` zpool을 기준으로 * ashift * 의 값이 인지 확인합니다 `12`.
+
ashift * 의 값이 아닌 경우 `12`를 참조하여 올바른 패치가 설치되었는지 확인하고 의 내용을 다시 확인하십시오 `vdc.conf`.

+
ashift * 가 값을 표시할 때까지 진행하지 마십시오 `12`.




NOTE: 다양한 버전의 Solaris에서 Oracle 버그 15824910 패치를 사용할 수 있습니다. 최상의 커널 패치를 결정하는 데 지원이 필요한 경우 Oracle에 문의하십시오.



== SnapMirror 비즈니스 연속성에 대한 권장 설정

SM-BC(SnapMirror Business Continuity) 환경에서 계획되지 않은 사이트 페일오버 스위치오버가 발생할 때 Solaris 클라이언트 애플리케이션이 무중단 운영인지 확인하려면 Solaris 11.4 호스트에서 다음 설정을 구성해야 합니다. 이 설정은 페일오버 모듈을 재정의합니다 `f_tpgs` 모순을 감지하는 코드 경로의 실행을 방지합니다.


NOTE: ONTAP 9.9.1부터 Solaris 11.4 호스트에서 SM-BC 설정 구성이 지원됩니다.

다음 지침에 따라 override 매개변수를 구성합니다.

.단계
. 구성 파일을 생성합니다 `/etc/driver/drv/scsi_vhci.conf` 호스트에 연결된 NetApp 스토리지 유형에 대해 다음과 유사한 항목을 제공합니다.
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. 를 사용합니다 `devprop` 및 `mdb` override 매개 변수가 성공적으로 적용되었는지 확인하는 명령:
+
' root@host-a:~#devprop-v -n /scsi_vhci scsi -vhci -failover -override scsi -vhci -failover -override=NetApp lun+f_tpgs root@host -a:~#echo" * scsi_vhci_dip: print -xi vci vdev vci vci vci vci vci vci vip ti 출력 pi vdev vci vci vci vci vci vci vci vci vci vci vdi ti ti vprint tp.pi

+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: 이후 `scsi-vhci-failover-override` 이(가) 적용되었습니다. `conf` 이(가) 에 추가됩니다 `svl_fops_name`. 기본 설정에 대한 추가 정보 및 권장 변경 사항은 NetApp 기술 문서 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 호스트 지원 SM-BC(SnapMirror Business Continuity) 구성에서 권장되는 설정입니다"^].



== 알려진 문제

ONTAP 릴리즈가 포함된 Solaris 11.4에는 다음과 같은 알려진 문제가 있습니다.

[cols="4*"]
|===
| NetApp 버그 ID | 제목 | 설명 | Oracle ID입니다 


| 1362435 | HUK 6.2 및 Solaris_11.4 FC 드라이버 바인딩 변경 | Solaris 11.4 및 HUK 권장 사항을 참조하십시오. FC 드라이버 바인딩이 에서 변경됩니다 `ssd (4D)` 를 선택합니다 `sd (4D)`. 에서 기존 설정을 이동합니다 `ssd.conf` 를 선택합니다 `sd.conf` Oracle DOC:2595926.1)에 설명되어 있습니다. 이 동작은 새로 설치된 Solaris 11.4 시스템과 Solaris 11.3 이전 버전에서 업그레이드한 시스템에 따라 달라집니다. | (문서 ID 2595926.1) 


| 1366780 | x86 Arch에서 Emulex 32G 호스트 버스 어댑터(HBA)를 사용하여 스토리지 페일오버(SFO) 반환 작업 중에 Solaris LIF 문제가 발견되었습니다 | x86_64 플랫폼에서 Emulex 펌웨어 버전 12.6.x 이상에서 Solaris LIF 문제가 발견되었습니다. | SR 3-24746803021 


| 1368957을 참조하십시오 | 솔라리스 11.x `cfgadm -c configure` 엔드 투 엔드 Emulex 구성에서 I/O 오류가 발생합니다 | 실행 중입니다 `cfgadm -c configure` Emulex에서 종단간 구성으로 인해 I/O 오류가 발생합니다. 이는 ONTAP 9.5P17, 9.6P14, 9.7P13 및 9.8P2에서 수정되었습니다 | 해당 없음 


| 1345622)를 참조하십시오 | OS 기본 명령을 사용하는 ASA/PPorts를 사용하여 Solaris 호스트에서 비정상적인 경로 보고 | ASA(All SAN Array)를 사용하는 Solaris 11.4에서 간헐적인 경로 보고 문제가 발생합니다. | 해당 없음 
|===