---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP에서 Solaris 호스트 유틸리티 6.2를 사용하는 방법을 설명합니다 
---
= ONTAP 스토리지용 Solaris Host Utilities 6.2를 설치합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris 호스트 유틸리티는 Solaris 호스트에 연결된 ONTAP 스토리지를 관리하고 기술 지원팀이 구성 데이터를 수집하도록 돕습니다.

Solaris 호스트 유틸리티는 여러 Solaris 환경과 여러 전송 프로토콜을 지원합니다.  다음은 주요 Solaris 호스트 유틸리티 환경입니다.

* SPARC 프로세서나 x86/64 프로세서를 사용하는 시스템에서 MPxIO와 파이버 채널(FC) 또는 iSCSI 프로토콜을 갖춘 기본 OS입니다.
* SPARC 프로세서를 사용하는 시스템에서 FC 또는 iSCSI 프로토콜을 사용하는 Veritas DMP(Dynamic Multipathing) 또는 x86/64 프로세서를 사용하는 시스템의 iSCSI 프로토콜


Solaris Host Utilities 6.2는 다음 Solaris 시리즈를 지원합니다.

* 솔라리스 11.x
* 솔라리스 10.x


.시작하기 전에
iSCSI, FC 또는 FCoE 구성이 지원되는지 확인하세요.  당신은 사용할 수 있습니다link:https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] 구성을 확인하세요.

.단계
. 호스트에 루트로 로그인합니다.
. 호스트 유틸리티가 포함된 압축 파일의 사본을 다운로드하세요.link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support 사이트"^] Solaris 호스트의 디렉토리로:
+
[role="tabbed-block"]
====
.스파크 CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64 CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. 다운로드가 있는 Solaris 호스트의 디렉토리로 이동합니다.
. 를 사용하여 파일의 압축을 풉니다 `gunzip` 명령:
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. 다음을 사용하여 파일을 추출합니다. `tar xvf` 명령:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. tar 파일에서 추출한 패키지를 호스트에 추가합니다.
+
[source, cli]
----
pkgadd
----
+
패키지는 '/opt/ntap/soolkit/bin' 디렉토리에 추가됩니다.

+
다음 예에서는 명령을 사용하여 `pkgadd` Solaris 설치 패키지를 설치합니다.

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. 다음 명령 중 하나를 사용하여 툴킷이 성공적으로 설치되었는지 확인하세요.
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.예제 출력 표시
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. MPxIO 또는 Veritas DMP 환경에 대한 호스트 매개변수를 구성하세요.
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. 설치를 확인합니다.
+
[source, cli]
----
sanlun version
----




== 다음 단계

link:hu-solaris-san-toolkit.html["SAN 툴킷에 대해 알아보세요"] .
