---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: ONTAP에서 Linux 통합 호스트 유틸리티 7.1을 사용하는 방법에 대해 설명합니다 
---
= Solaris 호스트 유틸리티 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Solaris 통합 호스트 유틸리티를 사용하면 Solaris 호스트에 연결된 NetApp ONTAP 스토리지를 관리할 수 있습니다.



== SAN 툴킷을 참조하십시오

Solaris Host Utilities는 Oracle Solaris 호스트에서 명령줄 툴킷을 제공하는 NetApp 호스트 소프트웨어입니다. 이 툴킷은 NetApp Host Utilities 패키지를 설치할 때 설치됩니다. 이 키트는 LUN과 HBA를 관리하는 데 도움이 되는 'anlun' 유틸리티를 제공합니다. 'anlun' 명령은 호스트에 매핑된 LUN, 다중 경로 및 이니시에이터 그룹을 생성하는 데 필요한 정보에 대한 정보를 반환합니다.

.예
다음 예에서는 'show'라는 'anlun lun show' 명령을 사용하여 LUN 정보를 반환합니다.

[listing]
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT


----

NOTE: 이 툴킷은 Host Utilities의 모든 구성 및 프로토콜에서 공통적으로 사용됩니다. 따라서 일부 내용은 한 설정에 적용되지만 다른 설정에는 적용되지 않습니다. 사용하지 않는 구성 요소가 있으면 시스템 성능에 영향을 주지 않습니다.



== Solaris 호스트 유틸리티를 설치합니다

Solaris Host Utilities 6.2는 여러 Solaris 환경 및 다중 프로토콜을 지원합니다. 기본 호스트 유틸리티 환경은 다음과 같습니다.

* SPARC 프로세서 또는 x86/64 프로세서를 사용하는 시스템에서 FC(Fibre Channel) 또는 iSCSI 프로토콜을 사용하는 MPxIO가 있는 네이티브 OS입니다.
* SPARC 프로세서를 사용하는 시스템에서 FC 또는 iSCSI 프로토콜을 사용하는 DMP(Veritas Dynamic Multipathing)와 x86/64 프로세서를 사용하는 시스템의 iSCSI 프로토콜을 사용하는 DMP(Veritas Dynamic Multipathing)



NOTE: NetApp Solaris Host Utilities 소프트웨어 패키지는 에서 사용할 수 있습니다 link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^] 프로세서를 위한 압축 파일 형식. 사용자 환경에 맞는 Host Utilities 소프트웨어 패키지를 Support 사이트에서 다운로드할 수 있습니다.

.단계
. 호스트에 루트로 로그인합니다.
. 에서 Host Utilities가 포함된 압축 파일 사본을 다운로드합니다 link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^] 호스트의 디렉토리로 이동합니다.
+
이 문서를 준비할 때 압축된 파일은 다음과 같이 불렸습니다.

+
** SPARC CPU:'NetApp_Solaris_HOST_UTPITUS_6_2_SPARC.tar.gz'
** x86/x64 CPU:'NetApp_Solaris_host_utilities_6_2_AMD.tar.gz'


. 다운로드가 포함된 디렉터리로 이동합니다.
. gunzip 명령을 사용하여 파일의 압축을 풉니다
+
'#gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz'

. 파일의 압축을 풉니다. 를 사용할 수 있습니다 `tar xvf` 명령을 사용하여 이 작업을 수행합니다.
+
"#tar xvf NetApp_Solaris_host_utilities_6_2_SPARC.tar"

. tar 파일에서 추출한 패키지를 호스트에 추가합니다. pkgadd 명령을 사용하여 이 작업을 수행할 수 있습니다.
+
패키지는 '/opt/ntap/soolkit/bin' 디렉토리에 추가됩니다. 다음 예에서는 "pkgadd" 명령을 사용하여 Solaris 설치 패키지를 설치합니다.

+
pkgadd -d./NTAPsagtagool.pkg

. pkginfo 명령 또는 ls -al 명령을 사용하여 툴킷이 성공적으로 설치되었는지 확인합니다.
+
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
. 작업을 마친 후에는 '/opt/NTAP/sotoolkit/bin/host_config' 명령을 사용하여 환경에 대한 호스트 매개 변수를 구성해야 합니다.
+
** MPxIO
** Veritas DMP


. 설치를 확인합니다.
+
안런 버전


