---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: FC, FCoE 및 iSCSI 프로토콜을 사용하는 VMware vSphere 8.x 릴리즈에 대한 ONTAP SAN 호스트 설정을 구성할 수 있습니다. 
---
= ONTAP와 함께 VMware vSphere 8.x를 사용합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FC, FCoE 및 iSCSI 프로토콜을 사용하는 VMware vSphere 8.x 릴리즈에 대한 ONTAP SAN 호스트 설정을 구성할 수 있습니다.



== 하이퍼바이저 SAN 부팅

.시작하기 전에
SAN 부팅을 사용하려는 경우 구성에 의해 지원되어야 합니다. 를 사용하여 OS, HBA, HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 지원되는지 확인할 수 link:https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^]있습니다.

.단계
. SAN 부팅 LUN을 호스트에 매핑합니다.
. 여러 경로를 사용할 수 있는지 확인합니다.
+

NOTE: 호스트 OS가 가동되고 경로에서 실행되면 여러 경로를 사용할 수 있습니다.

. SAN 부팅 LUN이 매핑되는 포트에 대해 서버 BIOS에서 SAN 부팅을 설정합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하여 부팅이 성공했는지 확인합니다.




== 다중 경로

ESXi는 NMP(Native Multipathing Plug-in)라는 확장 가능한 경로 다중화 모듈을 제공하여 하위 플러그인, SATP(Storage Array Type Plugins) 및 PSP(Path Selection Plugins)를 관리합니다. 기본적으로 이러한 SATP 규칙은 ESXi에서 사용할 수 있습니다.

ONTAP 스토리지의 경우 "VMW_SATP_ALUA" 플러그인이 기본적으로 PSP(경로 선택 정책)로 "VMW_PSP_RR"과 함께 사용됩니다. 다음 명령을 실행하여 PSP를 확인할 수 있습니다.

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
예제 출력:

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== 비 ASA 구성

비 ASA 구성의 경우 우선 순위가 서로 다른 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 높은 경로는 활성/최적화입니다. 즉, 애그리게이트가 위치한 컨트롤러에서 서비스합니다. 우선 순위가 낮은 경로는 다른 컨트롤러에서 제공되기 때문에 활성 상태이지만 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

.예
다음 예는 두 개의 Active/Optimized 경로와 두 개의 Active/Non-Optimized 경로가 있는 ONTAP LUN에 대한 올바른 출력을 표시합니다.

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
예제 출력:

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
예제 출력:

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
<stdin>에서 해결되지 않은 지시문 - include::_include/hu/reuse_hu_asa_configuration.adoc[]

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
예제 출력:

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
예제 출력:

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVOL

VVOL(가상 볼륨)은 가상 머신(VM) 디스크, 스냅샷 및 고속 클론에 해당하는 VMware 오브젝트 유형입니다.

VMware vSphere용 ONTAP 툴에는 VMware vCenter가 VVOL 기반 스토리지를 활용할 수 있도록 통합 지점을 제공하는 ONTAP용 VASA Provider가 포함되어 있습니다. ONTAP 툴 OVA(Open Virtualization Appliance)를 구축하면 vCenter 서버에 자동으로 등록되고 VASA Provider가 활성화됩니다.

vCenter UI를 사용하여 VVols 데이터 저장소를 만들 때 데이터 저장소의 백업 스토리지로 FlexVols를 생성하는 방법을 안내합니다. VVol 데이터 저장소 내의 VVol은 PE(프로토콜 엔드포인트)를 사용하여 ESXi 호스트에서 액세스합니다. SAN 환경에서는 PE로 사용하기 위해 데이터 저장소의 각 FlexVol에 4MB LUN이 하나씩 생성됩니다. SAN PE는 ALU(관리 논리 단위)이며 VVol은 자회사 논리 단위(SLU)입니다.

VVOL을 사용할 때는 다음을 비롯한 SAN 환경에 대한 표준 요구사항 및 모범 사례가 적용됩니다(이에 국한되지 않음).

* 사용하려는 SVM당 각 노드에 SAN LIF를 하나 이상 생성합니다. Best Practice는 노드당 최소 2개를 생성하는 것이지만 필요한 만큼 생성하는 것이 아닙니다.
* 단일 장애 지점 제거 여러 가상 스위치를 사용할 때 NIC 팀을 사용하는 서로 다른 네트워크 서브넷에서 여러 개의 VMkernel 네트워크 인터페이스를 사용하거나 여러 물리적 스위치에 연결된 여러 개의 물리적 NIC를 사용하여 HA와 향상된 처리량을 제공합니다.
* 호스트 연결에 필요한 조닝, VLAN 또는 둘 다를 구성합니다.
* 필요한 모든 이니시에이터가 원하는 SVM의 타겟 LIF에 로그인되어 있는지 확인합니다.



NOTE: VASA Provider를 설정하려면 VMware vSphere용 ONTAP 툴을 구축해야 합니다. VASA Provider는 모든 iGroup 설정을 관리하므로 VVOL 환경에서 iGroup을 생성하거나 관리할 필요가 없습니다.

현재 NetApp은 VVOL 설정을 기본값에서 변경하지 않는 것을 권장합니다.

특정 버전의 ONTAP 툴은 을 참조하고 https://imt.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^], 특정 버전의 vSphere 및 ONTAP는 기존 VASA Provider를 참조하십시오.

VVOL의 프로비저닝 및 관리에 대한 자세한 내용은 VMware vSphere용 ONTAP 툴 설명서, link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["ONTAP 기반의 VMware vSphere"^]및 를 참조하십시오.link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vvols-overview.html["ONTAP 툴을 이용한 VVOL(가상 볼륨) 10"^]



== 권장 설정



=== ATS 잠금

VAAI 호환 스토리지와 업그레이드된 VMFS5의 경우 ATS 잠금은 * 필수 * 이며 ONTAP LUN의 적절한 상호 운용성과 최적의 VMFS 공유 스토리지 I/O 성능을 위해 필요합니다. ATS 잠금 활성화에 대한 자세한 내용은 VMware 설명서를 참조하십시오.

[cols="4*"]
|===
| 설정 | 기본값 | ONTAP를 권장합니다 | 설명 


| HardwareAcceleratedLocking | 1 | 1 | ATS(Atomic Test and Set) 잠금을 사용하는 데 도움이 됩니다 


| 디스크 IOP | 1000입니다 | 1 | IOPS 제한: 라운드 로빈 PSP의 기본값은 IOPS 제한 1000입니다. 이 기본 사례에서는 1,000개의 I/O 작업이 실행된 후에 새 경로가 사용됩니다. 


| 디스크/QFullSampleSize | 0 | 32 | ESXi가 임계치 조절을 시작하기 전에 전체 또는 사용 중인 대기열 수입니다. 
|===

NOTE: 활성화 `Space-alloc` 용 VMware vSphere에 매핑된 모든 LUN에 대한 설정입니다 `UNMAP` 있습니다. 자세한 내용은 ONTAP 설명서를 참조하십시오.



=== 게스트 OS 시간 초과

권장 게스트 OS 튜닝을 사용하여 가상 머신을 수동으로 구성할 수 있습니다. 업데이트 조정 후 업데이트를 적용하려면 게스트를 재부팅해야 합니다.

* GOS 시간 초과 값: *

[cols="2*"]
|===
| 게스트 OS 유형입니다 | 시간 초과 


| Linux 버전 | 디스크 시간 초과 = 60 


| Windows | 디스크 시간 초과 = 60 


| Solaris | 디스크 시간 초과 = 60 사용 중 재시도 = 300 준비 안 됨 재시도 = 300 재설정 재시도 = 30 최대 스로틀 = 32분 스로틀 = 8 
|===


=== 조정 가능한 vSphere를 확인합니다

다음 명령을 사용하여 를 확인할 수 있습니다 `HardwareAcceleratedLocking` 설정.

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== 디스크 IOPS 설정을 확인합니다

다음 명령을 사용하여 IOP 설정을 확인할 수 있습니다.

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== QFullSampleSize의 유효성을 검사합니다

다음 명령을 사용하여 QFullSampleSize 를 확인할 수 있습니다.

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== 알려진 문제

ONTAP가 포함된 VMware vSphere 8.x 릴리즈에는 다음과 같은 알려진 문제가 있습니다.

[cols="10,30,30"]
|===
| NetApp 버그 ID | 제목 | 설명 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1543660["1543660)을 참조하십시오"^] | vNVMe 어댑터를 사용하는 Linux VM에서 긴 모든 경로 중단(APD) 창이 발생할 때 I/O 오류가 발생합니다  a| 
vSphere 8.x 이상을 실행하고 vNVMe(vNVME) 어댑터를 사용하는 Linux VM에서 기본적으로 vNVMe 재시도 작업이 비활성화되어 I/O 오류가 발생합니다. APD(All Path Down) 또는 입출력 로드가 많을 때 이전 커널을 실행하는 Linux VM의 중단을 방지하기 위해 VMware는 vNVMe 재시도 작업을 비활성화하기 위해 조정 가능한 "VSCSIDisableNvmeRetry"를 도입했습니다.

|===
.관련 정보
* link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["ONTAP 기반의 VMware vSphere"^]
* link:https://kb.vmware.com/s/article/2031038["NetApp MetroCluster(2031038)를 통한 VMware vSphere 5.x, 6.x 및 7.x 지원"^]
* link:https://kb.vmware.com/s/article/83370["NetApp vMSC(VMware vSphere Metro Storage Cluster)와 SnapMirror Active Sync가 있는 NetApp ONTAP"^]

