---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Unified Host Utilities에는 Windows 호스트에서 NetApp ONTAP 및 E-Series 플랫폼의 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= Windows Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Windows 호스트 유틸리티의 정의

Windows Unified Host Utilities에는 Windows 호스트에서 NetApp ONTAP 및 E-Series 플랫폼의 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA(호스트 버스 어댑터) 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다.

Host Utilities 소프트웨어를 설치할 때 설치 관리자는 필요한 Windows 레지스트리 및 HBA(호스트 버스 어댑터) 매개 변수를 설정합니다.

Windows 호스트 컴퓨터에 설치된 프로그램 및 파일은 다음과 같습니다. 기본 디렉토리는 'C:\Program Files\NetApp\Windows Host Utilities'입니다.

|===
| 프로그램 | 목적 


| 에멀렉스바 reg | 문제 해결 프로그램: 기술 지원 담당자가 지시한 경우에만 이 프로그램을 실행하십시오. 


| '\NetAppQCLI\fcconfig.exe' | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\fcconfig.ini` | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\ *. *' | 설치 프로그램에서 QLogic Fibre Channel HBA 매개변수를 설정하는 데 사용됩니다. 


| san_version.exe를 선택합니다 | Host Utilities 및 Fibre Channel HBA의 버전을 표시합니다. 
|===


== Host Utilities에서 지원되는 구성입니다

Host Utilities는 다양한 Windows 호스트 구성, 프로토콜 및 다중 경로 옵션을 지원합니다. 자세한 내용은 을 참조하십시오 https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^].



== 호스트 및 스토리지 시스템 구성을 확인합니다

Host Utilities를 설치하기 전에 Host Utilities 버전이 호스트 및 스토리지 시스템 구성을 지원하는지 확인하여 소프트웨어가 올바르게 설치되었는지 확인해야 합니다.

.단계
. 에서 지원되는 구성을 확인합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 의 해당 호스트에 필요한 핫픽스를 확인합니다 link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN 호스트 Windows 설명서"].
+

NOTE: link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["ONTAP와 함께 Windows Server 2022 사용"] 에 대한 지침은 에 나와 있습니다 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Windows 핫픽스 설치 중"] Windows Server 2022의 경우. 이전 버전의 Windows 서버에 대한 관련 핫픽스 정보를 찾으려면 호스트 구성 범주의 Windows 문서를 참조하십시오.

. iSCSI 또는 FCP 라이센스를 추가하고 대상 서비스를 시작합니다.
+
파이버 채널 및 iSCSI 프로토콜은 SANtricity 스토리지 관리자를 사용하여 E-Series 스토리지 시스템에 대한 라이센스가 필요하지 않습니다.

. 케이블 연결을 확인합니다
+
를 참조하십시오 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["SAN 구성 가이드 를 참조하십시오"^] ONTAP 또는 용 https://mysupport.netapp.com/ecm/ecm_get_file/ECMLP2773533["E-Series 하드웨어 케이블 연결 가이드 를 참조하십시오"^] 자세한 케이블 연결 및 구성 정보를 참조하십시오.





== FC HBA 및 스위치를 구성합니다

스토리지 시스템에 대한 Fibre Channel 접속을 위해 지원되는 하나 이상의 Fibre Channel HBA(호스트 버스 어댑터)를 설치하고 구성합니다.

Windows Host Utilities 설치 프로그램에서 필요한 Fibre Channel HBA 설정을 설정합니다.


NOTE: HBA 설정을 수동으로 변경하지 마십시오.

.단계
. HBA 공급업체가 제공한 지침에 따라 하나 이상의 지원되는 Fibre Channel HBA(호스트 버스 어댑터)를 설치합니다.
. 지원되는 HBA 드라이버 및 관리 유틸리티를 얻고 HBA 공급업체에서 제공하는 지침에 따라 설치합니다.
. HBA를 Fibre Channel 스위치에 접속하거나 스토리지 시스템에 직접 연결합니다.
. Fibre Channel 스위치 설명서에 따라 Fibre Channel 스위치에 영역을 생성합니다.
. ONTAP의 경우 WWPN으로 스위치를 조닝(Zoning)하십시오. 스토리지 컨트롤러의 물리적 포트가 아니라 LIF의 WWPN을 사용해야 합니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["SAN 구성 가이드 를 참조하십시오"^].




== Host Utilities를 설치합니다

설치 프로그램은 Host Utilities 패키지를 설치하고 Windows 레지스트리 및 HBA 설정을 설정합니다.

Windows Unified Host Utilities 소프트웨어 패키지를 설치할 때 다중 경로 지원을 포함할지 여부를 지정해야 합니다. 설치 프로그램에서 다음 항목을 선택하라는 메시지가 나타납니다. Windows 명령 프롬프트에서 자동(무인) 설치를 실행할 수도 있습니다.

.다중 경로 지원
* Windows 호스트 또는 가상 시스템에서 스토리지 시스템까지 경로가 둘 이상인 경우 MPIO 를 선택합니다.
* 스토리지 시스템에 대한 단일 경로를 사용하는 경우에만 MPIO를 선택하지 않습니다.
* MPIO 선택은 Windows XP 및 Windows Vista 시스템에서는 사용할 수 없으며, 다중 경로 I/O는 이러한 게스트 운영 체제에서 지원되지 않습니다.
* Hyper-V 게스트의 경우 다중 경로 지원을 선택한 경우 원시(통과) 디스크가 게스트 OS에 나타나지 않습니다. 원시 디스크를 사용하거나 MPIO를 사용할 수 있지만 게스트 OS에서 둘 다 사용할 수는 없습니다.




=== 호스트 유틸리티를 대화식으로 설치합니다

Host Utilities 소프트웨어 패키지를 대화식으로 설치하려면 Host Utilities 설치 프로그램을 실행하고 화면에 나타난 지침을 따라야 합니다.

.단계
. 에서 실행 파일을 다운로드합니다 https://mysupport.netapp.com/site/["NetApp Support 사이트"^].
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 'NetApp_Windows_HOST_UTPITECTS_7.1_x64' 파일을 실행하고 화면의 지시를 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.




=== 명령줄에서 Host Utilities를 설치합니다

* Windows 명령 프롬프트에 적절한 명령을 입력하여 Host Utilities의 자동(무인) 설치를 수행할 수 있습니다.
* Host Utilities 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다.
* 호스트 유틸리티를 대화식으로 설치하기 위한 지침에 따라 설치 패키지를 가져옵니다.
* 설치가 완료되면 시스템이 자동으로 재부팅됩니다.


.단계
. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
Msiexec /i installer.msi /quiet 다중경로 = {0|1} [INSTALLDIR=inst_path]'

+
** 여기서 installer는 CPU 아키텍처에 대한 '.msi' 파일의 이름입니다.
** 다중 경로 는 MPIO 지원이 설치되었는지 여부를 지정합니다. 허용되는 값은 0이고, 1은 예입니다
** inst_path는 Host Utilities 파일이 설치된 경로입니다. 기본 경로는 'C:\Program Files\NetApp\Windows Host Utilities\'입니다.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 Windows 명령 프롬프트에 'msiexec /help'를 입력합니다. 예: msiexec /i install.msi /quiet /l * v <install.log> LOGVERBOSE=1'



== Host Utilities를 업그레이드합니다

새 Host Utilities 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다. 호스트 유틸리티를 대화식으로 설치하기 위한 지침에 따라 설치 패키지를 가져옵니다.



=== 호스트 유틸리티를 대화식으로 업그레이드합니다

Host Utilities 소프트웨어 패키지를 대화식으로 설치하려면 Host Utilities 설치 프로그램을 실행하고 화면에 나타난 지침을 따라야 합니다.

.단계
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 실행 파일을 실행하고 화면의 지침을 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.
. 재부팅 후 Host Utility의 버전을 확인합니다.
+
.. 제어판 * 을 엽니다.
.. 프로그램 및 기능 * 으로 이동하여 호스트 유틸리티 버전을 확인합니다.






=== 명령줄에서 Host Utilities를 업그레이드합니다

Windows 명령 프롬프트에 적절한 명령을 입력하여 새 호스트 유틸리티의 자동(무인) 설치를 수행할 수 있습니다. 새 호스트 유틸리티 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다. 호스트 유틸리티를 대화식으로 설치하기 위한 지침에 따라 설치 패키지를 가져옵니다.

.단계
. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
Msiexec /i installer.msi /quiet 다중경로 = {0|1} [INSTALLDIR=inst_path]'

+
** 여기서 '설치 프로그램'은 CPU 아키텍처에 대한 '.msi' 파일의 이름입니다.
** 다중 경로 는 MPIO 지원이 설치되었는지 여부를 지정합니다. 허용되는 값은 0이고, 1은 예입니다
** inst_path는 Host Utilities 파일이 설치된 경로입니다. 기본 경로는 'C:\Program Files\NetApp\Windows Host Utilities\'입니다.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 Windows 명령 프롬프트에 'msiexec /help'를 입력합니다. 예: msiexec /i install.msi /quiet /l * v <install.log> LOGVERBOSE=1'

설치가 완료되면 시스템이 자동으로 재부팅됩니다.



== Windows Host Utilities 복구 및 제거

Host Utilities 설치 프로그램의 복구 옵션을 사용하여 HBA 및 Windows 레지스트리 설정을 업데이트할 수 있습니다. 호스트 유틸리티를 대화식으로 또는 Windows 명령줄에서 완전히 제거할 수 있습니다.



=== 대화식으로 Windows Host Utilities를 복구하거나 제거합니다

복구 옵션은 Windows 레지스트리 및 Fibre Channel HBA를 필요한 설정으로 업데이트합니다. Host Utilities를 완전히 제거할 수도 있습니다.

.단계
. Windows * 프로그램 및 기능 * (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019)을 엽니다.
. NetApp Windows Unified Host Utilities * 를 선택합니다.
. 변경 * 을 클릭합니다.
. 필요에 따라 * 복구 * 또는 * 제거 * 를 클릭합니다.
. 화면의 지침을 따릅니다.




=== 명령줄에서 Windows Host Utilities를 복구하거나 제거합니다

복구 옵션은 Windows 레지스트리 및 Fibre Channel HBA를 필요한 설정으로 업데이트합니다. Windows 명령줄에서 Host Utilities를 완전히 제거할 수도 있습니다.

.단계
. Windows 명령줄에서 다음 명령을 입력하여 Windows Host Utilities를 복구합니다.
+
msiexec {/uninstall | /f] installer.msi[/quiet]'

+
** '/uninstall'은 Host Utilities를 완전히 제거합니다.
** '/f'는 설치를 복구합니다.
** "installer.msi"는 시스템에 설치된 Windows Host Utilities 설치 프로그램의 이름입니다.
** '/quiet'은 모든 피드백을 억제하고 명령이 완료되면 확인 메시지 없이 시스템을 자동으로 재부팅합니다.






== Host Utilities에서 사용하는 설정 개요

Host Utilities는 Windows 호스트가 스토리지 시스템 동작을 올바르게 처리하도록 하기 위해 특정 레지스트리 및 매개 변수 설정이 필요합니다.

Windows Host Utilities는 Windows 호스트가 데이터 지연 또는 손실에 대응하는 방식에 영향을 주는 매개 변수를 설정합니다. Windows 호스트가 스토리지 시스템에 있는 컨트롤러 중 하나의 페일오버와 같은 이벤트를 파트너 컨트롤러로 올바르게 처리하도록 특정 값을 선택했습니다.

모든 값이 SANtricity 저장소 관리자용 DSM에 적용되는 것은 아니지만 호스트 유틸리티에서 설정한 값과 SANtricity 저장소 관리자용 DSM에서 설정한 값이 중복되지 않으면 충돌이 발생하지 않습니다. Fibre Channel 및 iSCSI HBA(호스트 버스 어댑터)에도 최상의 성능을 보장하고 스토리지 시스템 이벤트를 성공적으로 처리하도록 설정해야 하는 매개 변수가 있습니다.

Windows Unified Host Utilities와 함께 제공되는 설치 프로그램에서는 Windows 및 Fibre Channel HBA 매개 변수를 지원되는 값으로 설정합니다.


NOTE: iSCSI HBA 매개 변수를 수동으로 설정해야 합니다.

설치 프로그램은 설치 프로그램을 실행할 때 MPIO(다중 경로 I/O) 지원을 지정하는지 여부에 따라 다른 값을 설정합니다.

기술 지원 부서에서 지시하지 않는 한 이러한 값을 변경해서는 안 됩니다.



== Windows Unified Host Utilities에서 설정한 레지스트리 값입니다

Windows Unified Host Utilities 설치 프로그램은 설치하는 동안 선택한 항목에 따라 레지스트리 값을 자동으로 설정합니다. 이러한 레지스트리 값, 즉 운영 체제 버전을 알고 있어야 합니다. 다음 값은 Windows Unified Host Utilities 설치 프로그램에서 설정합니다. 달리 명시되지 않는 한 모든 값은 10진수입니다. HKLM은 HKEY_LOCAL_MACHINE의 약어입니다.

[cols="~, 10, ~"]
|===
| 레지스트리 키 | 값 | 설정합니다 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\DsmMaximumRetryTimeDuringStateTransition | 120 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\DsmMaximumStateTransitionTime | 120 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


.2+| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\DsmlSupportedDeviceList | "NETAPPLUN" | MPIO 지원이 지정된 경우 


| "NetApp LUN", "NetApp LUN C-Mode" | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Control\Class\{iSCSI_driver_GUID}\Instance_ID\Parameters\IPSecConfigTimeout | 60 | Data ONTAP DSM이 감지된 경우를 제외하고 항상 


| HKLM\SYSTEM\CurrentControlSet\Control\Class\{iSCSI_driver_GUID}\Instance_ID\Parameters\LinkDownTime | 10 | 항상 


| HKLM\SYSTEM\CurrentControlSet\Services\ClusDisk\Parameters\ManageDisksOnSystemBuses | 1 | Data ONTAP DSM이 감지된 경우를 제외하고 항상 


.2+| HKLM\SYSTEM\CurrentControlSet\Control\Class\{iSCSI_driver_GUID}\Instance_ID\Parameters\MaxRequestHoldTime | 120 | MPIO 지원을 선택하지 않은 경우 


| 30 | Data ONTAP DSM이 감지된 경우를 제외하고 항상 


.2+| HKLM\SYSTEM\CurrentControlSet\Control\MPDEV\MPIOSupportedDeviceList | "NetApp LUN" | MPIO 지원이 지정된 경우 


| "NetApp LUN", "NetApp LUN C-Mode" | MPIO가 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\PathRecoveryInterval | 40 | 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016만 해당됩니다 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\PathVerifyEnabled | 0 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\PathVerifyEnabled | 0 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\PathVerifyEnabled | 0 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msiscdsm\Parameters\PathVerifyEnabled | 0 | MPIO 지원이 지정되고 서버가 Windows Server 2003인 경우(Data ONTAP DSM이 감지된 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetApp\Parameters\PathVerifyEnabled | 0 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\PDORemovePeriodd | 130 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\PDORemovePeriodd | 130 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msiscdsm\Parameters\PDORemovePeriodd | 130 | MPIO 지원이 지정되고 서버가 Windows Server 2003인 경우(Data ONTAP DSM이 감지된 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetApp\Parameters\PDORemovePeriod입니다 | 130 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\RetryCount | 6 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\RetryCount | 6 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msiscdsm\Parameters\RetryCount | 6 | MPIO 지원이 지정되고 서버가 Windows Server 2003인 경우(Data ONTAP DSM이 감지된 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetApp\Parameters\RetryCount | 6 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\RetryInterval | 1 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm\Parameters\RetryInterval | 1 | MPIO 지원이 지정되고 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016인 경우(Data ONTAP DSM이 검색되는 경우는 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetApp\Parameters\RetryInterval | 1 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


.2+| HKLM\SYSTEM\CurrentControlSet\Services\disk\TimeOutValue | 120 | MPIO 지원이 선택되지 않은 경우(Data ONTAP DSM이 감지된 경우 제외) 


| 60 | MPIO 지원이 지정된 경우(Data ONTAP DSM이 감지된 경우 제외) 


| HKLM\SYSTEM\CurrentControlSet\Services\MPIO\Parameters\UseCustomPathRecoveryInterval | 1 | 서버가 Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 또는 Windows Server 2016만 해당됩니다 
|===
을 참조하십시오 https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/windows-registry-advanced-users["Microsoft 문서"^] 레지스트리 매개 변수에 대한 자세한 내용은 를 참조하십시오.



== Windows Host Utilities에서 설정한 FC HBA 값입니다

Fibre Channel을 사용하는 시스템에서 Host Utilities 설치 관리자는 Emulex 및 QLogic FC HBA에 필요한 시간 초과 값을 설정합니다. Emulex Fibre Channel HBA의 경우 MPIO를 선택할 때 설치 프로그램에서 다음 매개 변수를 설정합니다.

|===
| 속성 유형 | 속성 값 


| 링크 시간 초과 | 1 


| NodeTimeOut을 참조하십시오 | 10 
|===
Emulex Fibre Channel HBA의 경우 MPIO를 선택하지 않은 경우 설치 프로그램에서 다음 매개 변수를 설정합니다.

|===
| 속성 유형 | 속성 값 


| 링크 시간 초과 | 30 


| NodeTimeOut을 참조하십시오 | 120 
|===
QLogic Fibre Channel HBA의 경우 MPIO를 선택할 때 설치 프로그램에서 다음 매개 변수를 설정합니다.

|===
| 속성 유형 | 속성 값 


| LinkDownTimeOut 을 참조하십시오 | 1 


| PortDownRetryCount | 10 
|===
QLogic Fibre Channel HBA의 경우 MPIO가 선택되지 않은 경우 설치 프로그램에서 다음 매개 변수를 설정합니다.

|===
| 속성 유형 | 속성 값 


| LinkDownTimeOut 을 참조하십시오 | 30 


| PortDownRetryCount | 120 
|===

NOTE: 매개 변수의 이름은 프로그램에 따라 약간 다를 수 있습니다. 예를 들어, QLogic QConvergeConsole 프로그램에서 이 매개변수는 "Link Down Timeout"으로 표시됩니다. Host Utilities의 fcconfig.ini` 파일은 MPIO 지정 여부에 따라 이 매개변수를 LinkDownTimeOut 또는 MPioLinkDownTimeOut으로 표시합니다. 그러나 이러한 이름은 모두 동일한 HBA 매개 변수를 나타냅니다.

을 참조하십시오 https://www.broadcom.com/support/download-search["에뮬렉스"^] 또는 https://driverdownloads.qlogic.com/QLogicDriverDownloads_UI/Netapp_search.aspx["QLogic"^] Site(사이트) 를 클릭하여 시간 초과 매개 변수에 대해 자세히 알아보십시오.



== 문제 해결

이 섹션에서는 Windows Host Utilities의 일반적인 문제 해결 기법을 설명합니다. 최신 릴리스 정보에서 알려진 문제 및 해결 방법을 확인하십시오.

.상호 운용성 문제를 식별할 수 있는 영역이 다릅니다
* 잠재적인 상호 운용성 문제를 식별하려면 호스트 유틸리티가 호스트 운영 체제 소프트웨어, 호스트 하드웨어, ONTAP 소프트웨어 및 스토리지 시스템 하드웨어의 조합을 지원하는지 확인해야 합니다.
* 상호 운용성 매트릭스를 확인해야 합니다.
* 올바른 iSCSI 구성이 있는지 확인해야 합니다.
* 재부팅 후 iSCSI LUN을 사용할 수 없는 경우 Microsoft iSCSI 초기자 GUI의 영구 대상 탭에 대상이 영구 대상으로 나열되는지 확인해야 합니다.
* LUN을 사용하는 애플리케이션이 시작할 때 오류를 표시할 경우 애플리케이션이 iSCSI 서비스에 따라 구성되었는지 확인해야 합니다.
* ONTAP를 실행하는 스토리지 컨트롤러에 대한 파이버 채널 경로의 경우 FC 스위치가 노드의 물리적 포트에 대한 WWPN이 아니라 타겟 LIF의 WWPN을 사용하여 조닝(zoning)되는지 확인해야 합니다.
* 을(를) 검토해야 합니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2789205["Windows Host Utilities 릴리스 정보"^] 알려진 문제를 확인합니다. 릴리스 노트에는 알려진 문제와 제한 사항의 목록이 포함되어 있습니다.
* 의 문제 해결 정보를 검토해야 합니다 https://docs.netapp.com/ontap-9/index.jsp["SAN 관리 가이드를 참조하십시오"^] ONTAP 버전용.
* 검색해야 합니다 https://mysupport.netapp.com/site/bugs-online/["온라인 버그"^] 최근에 발견된 문제에 대해.
* 버그 유형 필드의 고급 검색에서 iSCSI-Windows를 선택한 다음 이동을 클릭해야 합니다. 버그 유형 FCP - Windows에 대한 검색을 반복해야 합니다.
* 시스템에 대한 정보를 수집해야 합니다.
* 호스트 또는 스토리지 시스템 콘솔에 표시되는 오류 메시지를 기록합니다.
* 호스트 및 스토리지 시스템 로그 파일을 수집합니다.
* 문제가 발생하기 직전에 문제 증상 및 호스트 또는 스토리지 시스템의 변경 사항을 기록합니다.
* 문제를 해결할 수 없는 경우 NetApp 기술 지원 팀에 문의할 수 있습니다.


http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
https://mysupport.netapp.com/portal/documentation["NetApp 문서"^]
https://mysupport.netapp.com/NOW/cgi-bin/bol["NetApp 온라인 버그"^]



=== 호스트 유틸리티의 FC HBA 드라이버 설정 변경 사항을 이해합니다

FC 시스템에 필요한 Emulex 또는 QLogic HBA 드라이버를 설치하는 동안 여러 매개 변수를 확인하고 경우에 따라 수정합니다.

Windows MPIO용 MS DSM이 감지된 경우 Host Utilities는 다음 매개변수에 대한 값을 설정합니다.

* LinkTimeOut - 물리적 링크가 중단된 후 호스트 포트가 입출력을 재개하기 전에 대기하는 시간(초)을 정의합니다.
* NodeTimeOut – 호스트 포트에서 타겟 디바이스와의 연결이 다운되었음을 인식하기 전의 시간(초)을 정의합니다.


HBA 문제를 해결할 때 이러한 설정이 올바른 값인지 확인하십시오. 올바른 값은 다음 두 가지 요소에 따라 달라집니다.

* HBA 공급업체
* 다중 경로 소프트웨어(MPIO)를 사용하는지 여부


Windows Host Utilities 설치 프로그램의 복구 옵션을 실행하여 HBA 설정을 수정할 수 있습니다.



==== FC 시스템에서 Emulex HBA 드라이버 설정을 확인합니다

Fibre Channel 시스템이 있는 경우 Emulex HBA 드라이버 설정을 확인해야 합니다. 이러한 설정은 HBA의 각 포트에 대해 존재해야 합니다.

.단계
. OnCommand 관리자를 엽니다.
. 목록에서 적절한 HBA를 선택하고 * Driver Parameters * 탭을 클릭합니다.
+
드라이버 매개 변수가 나타납니다.

. MPIO 소프트웨어를 사용하는 경우 다음과 같은 드라이버 설정이 있는지 확인합니다.
+
** 링크 시간 초과 - 1
** NodeTimeOut-10


. MPIO 소프트웨어를 사용하지 않는 경우 다음 드라이버 설정이 있는지 확인합니다.
+
** LinkTimeOut - 30
** NodeTimeOut-120






==== FC 시스템에서 QLogic HBA 드라이버 설정을 확인합니다

FC 시스템에서 QLogic HBA 드라이버 설정을 확인해야 합니다. 이러한 설정은 HBA의 각 포트에 대해 존재해야 합니다.

.단계
. QConvergConsole을 열고 도구 모음에서 * Connect * 를 클릭합니다.
+
호스트에 연결 대화 상자가 나타납니다.

. 목록에서 적절한 호스트를 선택한 다음 * 연결 * 을 클릭합니다.
+
HBA 목록이 FC HBA 창에 나타납니다.

. 목록에서 적절한 HBA 포트를 선택한 다음 * 설정 * 탭을 클릭합니다.
. 설정 선택 * 섹션에서 * 고급 HBA 포트 설정 * 을 선택합니다.
. MPIO 소프트웨어를 사용하는 경우 다음과 같은 드라이버 설정이 있는지 확인합니다.
+
** 링크 다운 시간 제한(linkdwnto) - 1
** 포트 다운 재시도 횟수(portdwnrc) - 10


. MPIO 소프트웨어를 사용하지 않는 경우 다음과 같은 드라이버 설정이 있는지 확인합니다.
+
** 링크 다운 시간 제한(linkdwnto) - 30
** 포트 다운 재시도 횟수(portdwnrc) - 120



