---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities에는 Windows 호스트가 ONTAP 및 E-Series 플랫폼에 대한 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= ONTAP 스토리지용 Windows 호스트 유틸리티 업그레이드
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
설치 지침에 따라 대화형으로 진행하거나 Windows 명령줄을 사용하여 ONTAP 스토리지 구성에서 Windows 호스트 유틸리티 소프트웨어를 업그레이드할 수 있습니다.  Windows 호스트에서 액세스할 수 있는 경로에 새로운 Windows 호스트 유틸리티 설치 소프트웨어를 설치해야 합니다.

[role="tabbed-block"]
====
.대화형으로 업그레이드
--
호스트 유틸리티 설치 프로그램을 실행하고 화면의 지시를 따라 Windows 호스트 유틸리티 소프트웨어를 대화형으로 업그레이드합니다.

.단계
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 실행 파일을 실행하고 화면의 지침을 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.
. 재부팅이 완료된 후 호스트 유틸리티 버전을 확인합니다.
+
.. 제어판 * 을 엽니다.
.. 프로그램 및 기능 * 으로 이동하여 호스트 유틸리티 버전을 확인합니다.




--
.비대화형 업그레이드
--
Windows 명령줄을 사용하여 비대화형 Windows 호스트 유틸리티 소프트웨어 업그레이드를 수행합니다.

.단계
. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 의 이름입니다 `.msi` CPU 아키텍처용 파일입니다.
** 경로 다중화는 Microsoft MPIO(다중 경로 I/O) 지원 설치 여부를 지정합니다. 허용되는 값은 "0"이고 "1"은 "예"입니다.
** inst_path는 Host Utilities 파일이 설치된 경로입니다. 기본 경로는 'C:\Program Files\NetApp\Windows Host Utilities\'입니다.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 를 입력합니다 `msiexec /help` Windows 명령 프롬프트에서 예를 들면, 입니다 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 명령은 로깅 정보를 표시합니다.

설치가 완료되면 시스템이 자동으로 재부팅됩니다.

--
====