---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities에는 Windows 호스트가 ONTAP 및 E-Series 플랫폼에 대한 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= ONTAP 스토리지용 Windows Host Utilities 7.1 설치
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 호스트 유틸리티를 사용하여 Windows 호스트 컴퓨터를 NetApp 스토리지 시스템에 연결할 수 있습니다.

Windows Host Utilities는 다음 버전의 Windows를 지원합니다.

* Windows 2022
* 윈도우즈 2019
* Windows 2016
* Windows 2012R2
* Windows 2012 를 참조하십시오


Windows 호스트 유틸리티에는 Windows 호스트가 ONTAP 및 E-Series 플랫폼에서 스토리지 시스템 동작을 올바르게 처리할 수 있도록 필요한 Windows 레지스트리 및 HBA(호스트 버스 어댑터) 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다.

Host Utilities 소프트웨어를 설치하면 설치 관리자에서 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정합니다.

Windows 호스트 컴퓨터에 설치된 프로그램 및 파일은 다음과 같습니다. 기본 디렉토리는 'C:\Program Files\NetApp\Windows Host Utilities'입니다.

|===
| 프로그램 | 목적 


| 에멀렉스바 reg | 문제 해결 프로그램: 기술 지원 담당자가 지시한 경우에만 이 프로그램을 실행하십시오. 


| '\NetAppQCLI\fcconfig.exe' | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\fcconfig.ini` | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\ *. *' | 설치 프로그램에서 QLogic FC HBA 매개 변수를 설정하는 데 사용됩니다. 


| san_version.exe를 선택합니다 | Host Utilities 및 FC HBA의 버전을 표시합니다. 
|===
Host Utilities는 다양한 Windows 호스트 구성, 프로토콜 및 다중 경로 옵션을 지원합니다. 지원되는 구성의 현재 목록은 를 https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^] 참조하십시오.



== 1단계: 호스트 및 스토리지 시스템 구성 확인

용 Windows Host Utilities를 설치하기 전에 호스트 및 스토리지 시스템 구성이 지원되는지 <<supported-windows-versions-71,지원되는 Windows 버전>>확인하십시오.

.단계
. 에서 지원되는 구성을 http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴"^] 확인합니다.
. Windows Server 호스트 버전에 필요한 핫픽스를 확인하세요.link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN 호스트 Windows 설명서"] .
+
예를 들어,link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["ONTAP 스토리지를 위한 Windows Server 2022 구성"] 설명서에서는 Windows Server 2022에 대한 Windows 핫픽스를 설치하는 방법에 대한 지침을 제공합니다.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["iSCSI 또는 FCP 라이센스 추가"^] .
+

NOTE: FC 및 iSCSI 프로토콜은 SANtricity Storage Manager 사용하는 E-시리즈 스토리지 시스템에서는 라이센스가 필요하지 않습니다.

. 대상 서비스를 시작합니다.
. 케이블 연결을 확인합니다.
+
를 참조하세요 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 구성 참조"^] 자세한 케이블링 및 구성 정보는 여기를 참조하세요.





== 2단계: FC HBA 및 스위치 구성

스토리지 시스템에 대한 FC 접속을 위해 지원되는 하나 이상의 FC HBA(호스트 버스 어댑터)를 설치하고 구성합니다.

Windows Host Utilities 설치 프로그램에서 필요한 FC HBA 설정을 설정합니다.


CAUTION: HBA 매개변수는 Windows 호스트 유틸리티 설치 프로그램에서만 설정해야 합니다.  이를 통해 Windows 호스트가 ONTAP 플랫폼의 스토리지 시스템 동작을 올바르게 처리할 수 있습니다.

.단계
. HBA 공급업체가 제공한 지침에 따라 하나 이상의 지원되는 FC HBA를 설치합니다.
. 지원되는 HBA 드라이버 및 관리 유틸리티를 얻고 HBA 공급업체에서 제공하는 지침에 따라 설치합니다.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["HBA를 FC 스위치 또는 스토리지 시스템에 직접 연결하세요."^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["FC 스위치 설명서에 따라 FC 스위치에 영역을 만듭니다."^] .
. ONTAP 의 경우 WWPN으로 스위치를 구역화합니다.  스토리지 컨트롤러의 물리적 포트의 WWPN이 아닌 논리적 인터페이스(LIF)의 WWPN을 사용해야 합니다. 를 참조하세요  https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 구성 참조"^] 자세한 내용은.




== 3단계: Windows 호스트 유틸리티 설치

설치 프로그램은 Windows 호스트 유틸리티 패키지를 설치하고 Windows 레지스트리와 HBA 설정을 지정합니다.

.이 작업에 대해
선택적으로 Windows 호스트 유틸리티 소프트웨어 패키지를 설치할 때 다중 경로 지원을 포함할 수 있습니다.  설치 프로그램에서 다음 옵션을 묻습니다.

* 을 선택합니다 `MPIO` Windows 호스트 또는 가상 머신에서 스토리지 시스템까지 경로가 두 개 이상 있는 경우
* 선택하다 `no MPIO` 저장 시스템에 단일 경로를 사용하는 경우에만 해당됩니다.


Windows 명령줄 프롬프트를 사용하여 다중 경로 지원을 선택할 수도 있습니다.

Hyper-V 게스트의 경우 다중 경로 지원을 선택하면 원시(패스스루) 디스크가 게스트 OS에 나타나지 않습니다.  원시 디스크나 MPIO를 모두 사용할 수 있지만, 게스트 OS에서는 둘 다 사용할 수 없습니다.


CAUTION: MPIO 소프트웨어를 설치하지 않으면 Windows OS에서 각 경로를 별도의 디스크로 볼 수 있습니다. 데이터가 손상될 수 있습니다.


NOTE: Hyper-V 가상 시스템에서 실행되는 Windows XP 또는 Windows Vista는 MPIO를 지원하지 않습니다.

.단계
호스트 유틸리티는 대화형으로 또는 Windows 명령줄을 사용하여 설치할 수 있습니다.  새로운 호스트 유틸리티 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다.

[role="tabbed-block"]
====
.대화형으로 설치합니다
--
Host Utilities 설치 프로그램을 실행하고 화면의 지시를 따라 Host Utilities 소프트웨어 패키지를 대화형으로 설치합니다.

. 에서 실행 파일을 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support 사이트"^].
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 'NetApp_Windows_HOST_UTPITECTS_7.1_x64' 파일을 실행하고 화면의 지시를 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.


--
.비대화형으로 설치
--
Windows 명령줄을 사용하여 호스트 유틸리티의 비대화형 설치를 수행합니다.  설치가 완료되면 시스템이 자동으로 재부팅됩니다.

. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 의 이름입니다 `.msi` CPU 아키텍처용 파일입니다
** 다중 경로 는 MPIO 지원이 설치되었는지 여부를 지정합니다. 허용되는 값은 아니요의 경우 "0", yes의 경우 "1"입니다
** inst_path는 Host Utilities 파일이 설치된 경로입니다. 기본 경로는 'C:\Program Files\NetApp\Windows Host Utilities\'입니다.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 를 입력합니다 `msiexec /help` Windows 명령 프롬프트에서. 예를 들어, 'msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1' 명령은 로깅 정보를 표시합니다.

--
====


== 다음 단계

link:hu_wuhu_hba_settings.html["Windows 호스트 유틸리티에 대한 레지스트리 설정 구성"] .
