---
sidebar: sidebar 
permalink: hu_wuhu_troubleshoot.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Unified Host Utilities에는 Windows 호스트에서 NetApp ONTAP 및 E-Series 플랫폼의 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= 문제 해결
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Windows Host Utilities의 일반적인 문제 해결 기술을 사용할 수 있습니다. 최신 릴리스 정보에서 알려진 문제 및 해결 방법을 확인하십시오.

다음은 잠재적인 상호 운용성 문제에 대해 조사할 수 있는 여러 영역 목록입니다.

* 잠재적인 상호 운용성 문제를 식별하려면 Host Utilities에서 호스트 운영 체제 소프트웨어, 호스트 하드웨어, ONTAP 소프트웨어 및 스토리지 시스템 하드웨어의 조합을 지원하는지 확인하십시오. 를 참조하십시오 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 를 참조하십시오.
* iSCSI 구성이 올바른지 확인합니다.
* 재부팅 후 iSCSI LUN을 사용할 수 없는 경우 Microsoft iSCSI Initiator GUI의 * Persistent Targets * 탭에 대상이 영구 대상으로 표시되는지 확인합니다.
* 시작 시 LUN을 사용하는 응용 프로그램에 오류가 표시되면 응용 프로그램이 iSCSI 서비스에 따라 구성되었는지 확인합니다.
* ONTAP를 실행하는 스토리지 컨트롤러에 대한 FC 경로의 경우 FC 스위치가 노드에 있는 물리적 포트의 WWPN이 아니라 대상 LIF의 WWPN을 사용하여 조닝되는지 확인합니다.
* 를 검토합니다 link:hu_wuhu_71_rn.html["릴리즈 노트"] Windows Host Utilities에서 알려진 문제를 확인합니다. 릴리스 노트에는 알려진 문제와 제한 사항 목록이 포함되어 있습니다.
* 사용 중인 ONTAP 버전에 대한 SAN 관리 가이드 의 문제 해결 정보를 검토합니다.
* 검색 https://mysupport.netapp.com/site/bugs-online/product["NetApp 온라인 버그"^] 최근에 발견된 문제에 대해.
+
** 고급 검색 아래의 버그 유형 필드에서 * iSCSI - Windows * 를 선택한 다음 * Go * 를 선택합니다. 버그 유형 * FCP - Windows * 에 대한 검색을 반복해야 합니다.


* 시스템에 대한 정보를 수집합니다.
* 호스트 또는 스토리지 시스템 콘솔에 표시되는 오류 메시지를 기록합니다.
* 호스트 및 스토리지 시스템 로그 파일을 수집합니다.
* 문제가 발생하기 직전에 문제 증상 및 호스트 또는 스토리지 시스템의 변경 사항을 기록합니다.
* 문제를 해결할 수 없는 경우 NetApp 기술 지원 팀에 문의하여 지원을 받으십시오.

