---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: wuhu, 7.2, host utilities, SAN, windows, unified 
summary: Windows 유니파이드 호스트 유틸리티에는 Windows 호스트에서 NetApp ONTAP 및 E-Series 플랫폼의 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= Windows Unified Host Utilities 7.2를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wuhu(Windows 통합 호스트 유틸리티)를 사용하면 Windows 호스트 컴퓨터를 NetApp 스토리지 시스템에 연결할 수 있습니다.

Windows Unified Host Utilities는 다음과 같은 버전의 Windows를 지원합니다.

* Windows 2022
* 윈도우즈 2019
* Windows 2016
* Windows 2012R2
* Windows 2012 를 참조하십시오


Windows 통합 호스트 유틸리티에는 Windows 호스트가 NetApp ONTAP 및 E-Series 플랫폼에 대한 스토리지 시스템 동작을 올바르게 처리할 수 있도록 필요한 Windows 레지스트리 및 HBA(호스트 버스 어댑터) 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다.

Host Utilities 소프트웨어를 설치하면 설치 관리자에서 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정합니다.

Windows 호스트 컴퓨터에 설치된 프로그램 및 파일은 다음과 같습니다. 기본 디렉토리는 'C:\Program Files\NetApp\Windows Host Utilities'입니다.

|===
| 프로그램 | 목적 


| 에멀렉스바 reg | 문제 해결 프로그램: 기술 지원 담당자가 지시한 경우에만 이 프로그램을 실행하십시오. 


| '\NetAppQCLI\fcconfig.exe' | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\fcconfig.ini` | 설치 프로그램에서 HBA 매개 변수를 설정하는 데 사용됩니다. 


| '\NetAppQCLI\ *. *' | 설치 프로그램에서 QLogic FC HBA 매개변수를 설정하는 데 사용됩니다. 


| san_version.exe를 선택합니다 | Host Utilities 및 FC HBA의 버전을 표시합니다. 
|===
호스트 유틸리티는 다양한 Windows 호스트 구성, 프로토콜 및 다중 경로 옵션을 지원합니다. 자세한 내용은 를 참조하십시오 https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^].



== 호스트 및 스토리지 시스템 구성을 확인합니다

호스트 유틸리티를 설치하기 전에 호스트 유틸리티 버전이 소프트웨어가 올바르게 설치되도록 호스트 및 스토리지 시스템 구성을 지원하는지 확인해야 합니다.

.단계
. 에서 지원되는 구성을 확인합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 에서 해당 호스트에 필요한 핫픽스를 확인합니다 link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN 호스트 Windows 설명서"].
+

NOTE: 를 클릭합니다 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["ONTAP와 함께 Windows Server 2022 사용"] 문서에 에 대한 지침이 나와 있습니다 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Windows 핫픽스 설치 중"] Windows Server 2022의 경우. 이전 버전의 Windows Server에 대한 관련 핫픽스 정보는 호스트 구성 범주의 Windows 문서를 참조하십시오.

. iSCSI, FCP 또는 NVMe-oF 라이센스를 추가하고 타겟 서비스를 시작합니다.
+

NOTE: FC 및 iSCSI 프로토콜은 SANtricity Storage Manager를 사용하는 E-Series 스토리지 시스템에 대한 라이센스가 필요하지 않습니다.

. 케이블 연결을 확인합니다.
+
를 참조하십시오 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 구성 참조"^] 사용 중인 ONTAP 또는 버전에 대한 설명서입니다 https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["E-Series 하드웨어 케이블링"^] 자세한 케이블 연결 및 구성 정보를 참조하십시오.





== FC HBA 및 스위치를 구성합니다

스토리지 시스템에 대한 FC 접속을 위해 지원되는 하나 이상의 FC HBA(호스트 버스 어댑터)를 설치하고 구성합니다.

Windows Host Utilities 설치 프로그램에서 필요한 FC HBA 설정을 설정합니다.


CAUTION: HBA 설정을 수동으로 변경하지 마십시오.

.단계
. HBA 공급업체가 제공한 지침에 따라 하나 이상의 지원되는 FC HBA를 설치합니다.
. 지원되는 HBA 드라이버 및 관리 유틸리티를 얻고 HBA 공급업체에서 제공하는 지침에 따라 설치합니다.
. HBA를 FC 스위치에 연결하거나 스토리지 시스템에 직접 연결합니다.
. FC 스위치 설명서에 따라 FC 스위치에 영역을 만듭니다.
. ONTAP의 경우 WWPN으로 스위치를 조닝(Zoning)하십시오. 스토리지 컨트롤러의 물리적 포트 WWPN이 아니라 논리 인터페이스(LIF)의 WWPN을 사용해야 합니다. 를 참조하십시오 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 구성 참조"^] 설명서를 참조하십시오.




== Host Utilities를 설치합니다

설치 프로그램은 호스트 유틸리티 패키지를 설치하고 Windows 레지스트리 및 HBA 설정을 설정합니다.

Windows Unified Host Utilities 소프트웨어 패키지를 설치할 때 다중 경로 지원을 포함할지 여부를 지정해야 합니다. 설치 프로그램에서 다음 옵션을 묻는 메시지가 나타납니다. Windows 명령 프롬프트에서 자동(무인) 설치를 실행할 수도 있습니다.

.다중 경로 지원
* 을 선택합니다 `MPIO` Windows 호스트 또는 가상 머신에서 스토리지 시스템까지 경로가 두 개 이상 있는 경우
* 을 선택합니다 `no MPIO` 스토리지 시스템에 대한 단일 경로를 사용하는 경우에만 가능합니다.


MPIO 선택은 Windows XP 및 Windows Vista 시스템에서는 사용할 수 없으며, 다중 경로 I/O는 이러한 게스트 운영 체제에서 지원되지 않습니다. Hyper-V 게스트의 경우 다중 경로 지원을 선택한 경우 원시(통과) 디스크가 게스트 OS에 나타나지 않습니다. 원시 디스크를 사용하거나 MPIO를 사용할 수 있지만 게스트 OS에서 둘 다 사용할 수는 없습니다.

호스트 유틸리티를 대화형으로 설치하거나 명령줄을 사용하여 설치할 수 있습니다. 새 Host Utilities 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다. Host Utilities를 대화식 또는 Windows 명령줄에서 설치하기 위한 지침을 따르십시오.

[role="tabbed-block"]
====
.대화형으로 설치합니다
--
Host Utilities 소프트웨어 패키지를 대화식으로 설치하려면 호스트 유틸리티 설치 프로그램을 실행하고 표시되는 메시지를 따라야 합니다.

.단계
. 에서 실행 파일을 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp Support 사이트"^].
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 를 실행합니다 `netapp_windows_host_utilities_7.2_x64` 파일을 만들고 화면의 지침을 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.


--
.명령줄에서 설치합니다
--
Windows 명령 프롬프트에 적절한 명령을 입력하여 호스트 유틸리티의 자동(무인) 설치를 수행할 수 있습니다. 설치가 완료되면 시스템이 자동으로 재부팅됩니다.

.단계
. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
Msiexec /i installer.msi /quiet 다중경로 = {0|1} [INSTALLDIR=inst_path]'

+
** `installer` 의 이름입니다 `.msi` CPU 아키텍처용 파일입니다.
** 다중 경로 는 MPIO 지원이 설치되었는지 여부를 지정합니다. 허용되는 값은 "0"이고 "1"은 "예"입니다.
** `inst_path` 호스트 유틸리티 파일이 설치된 경로입니다. 기본 경로는 입니다 `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 를 입력합니다 `msiexec /help` Windows 명령 프롬프트에서 예를 들면, 입니다 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 명령은 로깅 정보를 표시합니다.

--
====