---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Unified Host Utilities에는 Windows 호스트에서 NetApp ONTAP 및 E-Series 플랫폼의 스토리지 시스템 동작을 올바르게 처리하도록 필요한 Windows 레지스트리 및 HBA 매개 변수를 설정하는 설치 프로그램이 포함되어 있습니다. 
---
= Windows Unified Host Utilities를 업그레이드합니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
새 Host Utilities 설치 패키지는 Windows 호스트에서 액세스할 수 있는 경로에 있어야 합니다. 설치 패키지를 업그레이드하려면 Host Utilities를 대화형으로 설치하거나 Windows 명령줄에서 지침을 따르십시오.

[role="tabbed-block"]
====
.대화형으로 업그레이드
--
Host Utilities 소프트웨어 패키지를 대화식으로 업그레이드하려면 Host Utilities 설치 프로그램을 실행하고 표시되는 메시지를 따라야 합니다.

.단계
. 실행 파일을 다운로드한 디렉터리로 변경합니다.
. 실행 파일을 실행하고 화면의 지침을 따릅니다.
. 메시지가 나타나면 Windows 호스트를 재부팅합니다.
. 재부팅이 완료된 후 호스트 유틸리티 버전을 확인합니다.
+
.. 제어판 * 을 엽니다.
.. 프로그램 및 기능 * 으로 이동하여 호스트 유틸리티 버전을 확인합니다.




--
.명령줄에서 업그레이드
--
Windows 명령 프롬프트에서 적절한 명령을 입력하여 새 Host Utilities를 자동(자동) 업그레이드를 수행할 수 있습니다.

.단계
. Windows 명령 프롬프트에서 다음 명령을 입력합니다.
+
Msiexec /i installer.msi /quiet 다중경로 = {0|1} [INSTALLDIR=inst_path]'

+
** `installer` 의 이름입니다 `.msi` CPU 아키텍처용 파일입니다.
** 다중 경로 는 MPIO 지원이 설치되었는지 여부를 지정합니다. 허용되는 값은 "0"이고 "1"은 "예"입니다.
** inst_path는 Host Utilities 파일이 설치된 경로입니다. 기본 경로는 'C:\Program Files\NetApp\Windows Host Utilities\'입니다.





NOTE: 로깅 및 기타 기능에 대한 표준 MSI(Microsoft Installer) 옵션을 보려면 를 입력합니다 `msiexec /help` Windows 명령 프롬프트에서 예를 들면, 입니다 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 명령은 로깅 정보를 표시합니다.

설치가 완료되면 시스템이 자동으로 재부팅됩니다.

--
====