---
sidebar: sidebar 
permalink: nvme-rhel-82.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: ONTAP를 사용하여 RHEL 8.2에 대해 NVMe/FC 호스트를 구성하는 방법 
---
= ONTAP 스토리지를 사용하여 NVMe-oF에 대한 RHEL 8.2 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Red Hat Enterprise Linux(RHEL) 호스트는 비대칭 네임스페이스 액세스(ANA)를 통해 NVMe over Fibre Channel(NVMe/FC) 및 NVMe over TCP(NVMe/TCP) 프로토콜을 지원합니다.  ANA는 iSCSI 및 FCP 환경에서 ALUA(비대칭 논리 장치 액세스)와 동일한 다중 경로 기능을 제공합니다.

RHEL 8.2에 대해 NVMe over Fabrics(NVMe-oF) 호스트를 구성하는 방법을 알아보세요.  추가 지원 및 기능 정보는 다음을 참조하세요.link:hu-nvme-index.html["NVME-oF 개요"^] .

*RHEL 8.2를 사용하는 NVMe-oF에는 다음과 같은 알려진 제한 사항이 있습니다.*

* NVMe-oF 프로토콜을 사용한 SAN 부팅은 현재 지원되지 않습니다.
* RHEL 8.2의 NVMe-oF 호스트에서는 커널 내부 NVMe 멀티패스가 기본적으로 비활성화되어 있습니다. 수동으로 활성화해야 합니다.




== 1단계: 필요에 따라 SAN 부팅을 활성화합니다

SAN 부팅을 사용하도록 호스트를 구성하여 배포를 간소화하고 확장성을 개선할 수 있습니다. 사용하다link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] Linux OS, 호스트 버스 어댑터(HBA), HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인하세요.

.단계
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["NVMe 네임스페이스를 생성하고 호스트에 매핑합니다."^] .
. SAN 부팅 네임스페이스가 매핑된 포트에 대해 서버 BIOS에서 SAN 부팅을 활성화합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하고 OS가 제대로 실행 중인지 확인하세요.




== 2단계: 소프트웨어 버전 및 NVMe 구성 확인

시스템이 소프트웨어 요구 사항을 충족하는지 확인하고 NVMe 패키지 설치와 호스트 구성을 확인하세요.

.단계
. 서버에 RHEL 8.2를 설치합니다.  설치가 완료되면 필요한 RHEL 8.2 커널을 실행하고 있는지 확인하세요.
+
[source, cli]
----
uname -r
----
+
RHEL 커널 버전 예:

+
[listing]
----
4.18.0-193.el8.x86_64
----
. NVMe-CLI 패키지를 설치합니다.
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
다음 예에서는 nvme-cli 패키지 버전을 보여줍니다.

+
[listing]
----
nvme-cli-1.9.5.el8.x86_64
----
. 인커널 NVMe 다중 경로 지원:
+
[source, cli]
----
grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----
. RHEL 8.2 호스트에서 호스트 NQN 문자열을 확인하세요. `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
다음 예제는 hostnqn 문자열을 보여줍니다.

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
. RHEL 8.2 호스트에서 hostnqn 문자열을 확인하세요. `/etc/nvme/hostnqn` :
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
vs_fcnvme_141   nvme_141_1      nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
====
+

NOTE: 호스트 NQN 문자열이 일치하지 않으면 다음을 사용하십시오. `vserver modify` 해당 ONTAP 어레이 서브시스템에서 호스트 NQN 문자열을 업데이트하여 호스트 NQN 문자열과 일치하도록 하는 명령 `/etc/nvme/hostnqn` 호스트에서.

. 호스트를 재부팅합니다.
. 필요한 경우 를 업데이트합니다 `enable_foreign` 설정.
+
[NOTE]
====
동일한 호스트에서 NVMe와 SCSI 트래픽을 모두 실행하려면 NetApp ONTAP 네임스페이스에 커널 내 NVMe 멀티패스를 사용하고 ONTAP LUN에 dm-multipath를 사용할 것을 권장합니다.  dm-multipath가 ONTAP 네임스페이스 장치를 청구하지 못하도록 하려면 다음을 추가하여 제외합니다. `enable_foreign` 설정 `/etc/multipath.conf` 파일:

[source, cli]
----
cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
====
. 'stemctl restart multipathd'를 실행하여 multipathd 데몬을 다시 시작합니다.




== 3단계: Broadcom/Emulex에 대한 NVMe/FC 구성

Broadcom/Emulex에 대해 NVMe/FC를 구성할 수 있습니다.

.단계
. 지원되는 어댑터 모델을 사용하고 있는지 확인합니다.
+
.. 모델 이름을 표시합니다:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
.. 모델 설명을 표시합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----


. 의 예상 출력이 `3` 다음과 같이 설정되었는지 확인합니다 `lpfc_enable_fc4_type`.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 이니시에이터 포트가 작동 중이고 대상 LIF를 볼 수 있는지 확인하세요.
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
0x100000109b1c1204
0x100000109b1c1205
----
. 이니시에이터 포트가 온라인 상태인지 확인합니다.
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Online
Online
----
. NVMe/FC 이니시에이터 포트가 활성화되었고 타겟 포트가 표시되는지 확인합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 *ONLINE*
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 *TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 *ONLINE*
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 *TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
====




== 4단계: 선택적으로 NVMe/FC에 대해 1MB I/O를 활성화합니다.

ONTAP Identify Controller 데이터에서 최대 데이터 전송 크기(MDTS)를 8로 보고합니다.  즉, 최대 I/O 요청 크기는 1MB까지 가능합니다.  Broadcom NVMe/FC 호스트에 대해 1MB 크기의 I/O 요청을 발행하려면 다음을 늘려야 합니다. `lpfc` 의 가치 `lpfc_sg_seg_cnt` 매개변수를 기본값 64에서 256으로 변경합니다.


NOTE: 이 단계는 Qlogic NVMe/FC 호스트에는 적용되지 않습니다.

.단계
.  `lpfc_sg_seg_cnt`매개변수를 256으로 설정합니다.
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
다음 예와 비슷한 출력이 표시되어야 합니다.

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
.  `dracut -f`명령을 실행하고 호스트를 재부팅합니다.
. 의 값이 256인지 `lpfc_sg_seg_cnt` 확인합니다.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 5단계: NVMe-oF 검증

커널 내 NVMe 다중 경로 상태, ANA 상태 및 ONTAP 네임스페이스가 NVMe-oF 구성에 적합한지 확인합니다.

.단계
. in-kernel NVMe multipath가 활성화되어 있는지 확인합니다.
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Y
----
. 각 ONTAP 네임스페이스에 대한 적절한 NVMe-oF 설정(예: NetApp ONTAP 컨트롤러로 설정된 모델 및 라운드 로빈으로 설정된 로드 밸런싱 IPolicy가 호스트에 올바르게 반영되는지 확인합니다.
+
.. 하위 시스템을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 정책을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
round-robin
round-robin
----


. 호스트에서 네임스페이스가 생성되고 올바르게 검색되는지 확인합니다.
+
[source, cli]
----
nvme list
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. 각 경로의 컨트롤러 상태가 라이브이고 올바른 ANA 상태인지 확인합니다.
+
[source, cli]
----
nvme list-subsys /dev/nvme0n1
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 *live optimized*
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 *live inaccessible*
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 *live optimized*
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 *live inaccessible*
----
====
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다.
+
[role="tabbed-block"]
====
.열
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB
----
=====
--
.JSON을 참조하십시오
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----
=====
--
====




== 6단계: 알려진 문제를 검토합니다

알려진 문제가 없습니다.
