---
sidebar: sidebar 
permalink: nvme-windows-2012r2.html 
keywords: nvme, windows, enterprise 
summary: 'ONTAP LUN과 함께 작동하도록 Windows Server 2012 R2를 실행하는 호스트에서 NVMe/FC(NVMe over Fibre Channel)를 구성할 수 있습니다.' 
---
= Windows Server 2012 R2와 ONTAP용 NVMe/FC를 구성합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP LUN과 함께 작동하도록 Windows Server 2012 R2를 실행하는 호스트에서 NVMe/FC(NVMe over Fibre Channel)를 구성할 수 있습니다.

.이 작업에 대해
Windows 2012 R2의 NVMe/FC 호스트 구성에 다음 지원을 사용할 수 있습니다. 또한 구성 프로세스를 시작하기 전에 알려진 제한 사항을 검토해야 합니다.


NOTE: 이 절차에 제공된 구성 설정을 사용하여 및 에 연결된 클라우드 클라이언트를 구성할 수 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^]있습니다.

* 사용 가능한 지원:
+
ONTAP 9.7부터 Windows Server 2012 R2에서 NVMe/FC가 지원됩니다.

+
지원되는 FC 어댑터 및 컨트롤러 목록은 을 참조하십시오link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. 지원되는 구성 및 버전의 최신 목록은 를 참조하십시오link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^].

* 알려진 제한 사항:
+
ONTAP은 현재 NVMe/FC를 통한 영구 예약을 지원하지 않으므로 Windows 페일오버 클러스터가 NVMe/FC에서 지원되지 않습니다.

+

NOTE: Broadcom은 진정한 NVMe/FC 드라이버가 아닌 변환 SCSI ⇄ NVMe 드라이버인 Windows NVMe/FC용 외부 드라이버를 제공합니다. 전환 오버헤드가 성능에 영향을 미칠 필요는 없지만 NVMe/FC의 성능 이점을 부정합니다. 그 결과, NVMe/FC 및 FCP 성능은 Linux 등의 다른 운영 체제와 동일하게 NVME/FC 성능이 FCP보다 훨씬 더 뛰어납니다.





== NVMe/FC를 사용하도록 설정합니다

Windows 이니시에이터 호스트에서 FC/NVMe를 사용하도록 설정합니다.

.단계
. Windows 호스트에 Emulex HBA Manager 유틸리티를 설치합니다.
. 각 HBA 이니시에이터 포트에서 다음 HBA 드라이버 매개 변수를 설정합니다.
+
** EnableNVMe=1
** NVMeMode = 0


. 호스트를 재부팅합니다.




== Broadcom FC 어댑터를 구성합니다

Broadcom 이니시에이터는 동일한 32G FC 어댑터 포트를 통해 NVMe/FC 및 FCP 트래픽을 모두 처리할 수 있습니다. FCP 및 FC/NVMe의 경우 Microsoft MPIO(다중 경로 I/O) 옵션으로 Microsft DSM(장치별 모듈)을 사용해야 합니다.

는 `+hostnqn+` Windows 환경에서 FC/NVMe를 사용하는 Broadcom 어댑터용 각 HBA(호스트 버스 어댑터) 포트와 연결됩니다. 의 `+hostnqn+` 형식은 다음 예제와 같습니다.

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== NVMe 장치에 MPIO를 활성화합니다

Windows 호스트에서 NVMe 구성을 완료하려면 NVMe 장치에 대해 MPIO를 활성화해야 합니다.

.단계
. 설치합니다 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Windows 호스트 유틸리티 키트 7.1"] FC 및 NVMe 모두에 공통되는 드라이버 매개 변수를 설정합니다.
. MPIO 속성을 엽니다.
. Discover Multi-Paths * 탭에서 NVMe에 나열된 장치 ID를 추가합니다.
+
MPIO는 디스크 관리 아래에 표시되는 NVMe 장치를 인식합니다.

. 디스크 관리 * 를 열고 * 디스크 속성 * 으로 이동합니다.
. MPIO * 탭에서 * Details * 를 선택합니다.
. 다음 Microsoft DSM 설정을 설정합니다.
+
** PathVerifiedPeriod: * 10 *
** PathVerifyEnabled: * 활성화 *
** RetryCount: * 6 *
** 재시도 간격: * 1 *
** PDORemovedPeriod: * 130 *


. MPIO Policy * Round Robin with Subset * 를 선택합니다.
. 레지스트리 값을 변경합니다.
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. 호스트를 재부팅합니다.




== NVMe/FC를 검증합니다

NVMe 서브시스템이 검색되었고 ONTAP 네임스페이스가 NVMe-oF 구성에 적합한지 확인합니다.

.단계
. "포트 유형"이다음과 같은지 확인합니다. `+FC+NVMe+`
+
`listhba`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. NVMe/FC 서브시스템이 검색되었는지 확인:
+
** `+nvme-list+`
+
.예제 보기
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.예제 보기
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. 네임스페이스가 생성되었는지 확인합니다.
+
`+nvme-list-ns+`

+
.예제 보기
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

