---
sidebar: sidebar 
permalink: nvme-rhel-88.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: ONTAP를 사용하여 RHEL 8.8에 대한 NVMe-of 호스트를 구성하는 방법 
---
= ONTAP 스토리지를 사용하여 NVMe-oF에 대한 RHEL 8.8 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Red Hat Enterprise Linux(RHEL) 호스트는 비대칭 네임스페이스 액세스(ANA)를 통해 NVMe over Fibre Channel(NVMe/FC) 및 NVMe over TCP(NVMe/TCP) 프로토콜을 지원합니다.  ANA는 iSCSI 및 FCP 환경에서 ALUA(비대칭 논리 장치 액세스)와 동일한 다중 경로 기능을 제공합니다.

RHEL 8.8에 대해 NVMe over Fabrics(NVMe-oF) 호스트를 구성하는 방법을 알아보세요.  추가 지원 및 기능 정보는 다음을 참조하세요.link:hu-nvme-index.html["NVME-oF 개요"^] .

*RHEL 8.8을 사용하는 NVMe-oF에는 다음과 같은 알려진 제한 사항이 있습니다.*

* NVMe-oF 프로토콜을 사용한 SAN 부팅은 현재 지원되지 않습니다.
* RHEL 8.8의 NVMe-oF 호스트에서는 커널 내부 NVMe 멀티패스가 기본적으로 비활성화되어 있습니다. 수동으로 활성화해야 합니다.
* 알려진 문제로 인해 NVMe/TCP는 기술 미리보기로 제공됩니다.




== 1단계: 필요에 따라 SAN 부팅을 활성화합니다

SAN 부팅을 사용하도록 호스트를 구성하여 배포를 간소화하고 확장성을 개선할 수 있습니다. 사용하다link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] Linux OS, 호스트 버스 어댑터(HBA), HBA 펌웨어, HBA 부팅 BIOS 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인하세요.

.단계
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["NVMe 네임스페이스를 생성하고 호스트에 매핑합니다."^] .
. SAN 부팅 네임스페이스가 매핑된 포트에 대해 서버 BIOS에서 SAN 부팅을 활성화합니다.
+
HBA BIOS를 활성화하는 방법에 대한 자세한 내용은 공급업체별 설명서를 참조하십시오.

. 호스트를 재부팅하고 OS가 제대로 실행 중인지 확인하세요.




== 2단계: 소프트웨어 버전 및 NVMe 구성 확인

시스템이 소프트웨어 요구 사항을 충족하는지 확인하고 NVMe 패키지 설치와 호스트 구성을 확인하세요.

.단계
. 서버에 RHEL 8.8을 설치합니다.  설치가 완료되면 필요한 RHEL 8.8 커널을 실행하고 있는지 확인하세요.
+
[source, cli]
----
uname -r
----
+
RHEL 커널 버전 예:

+
[listing]
----
4.18.0-477.10.1.el8_8.x86_64
----
. "NVMe-CLI" 패키지를 설치합니다.
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
다음 예에서는 nvme-cli 패키지 버전을 보여줍니다.

+
[listing]
----
nvme-cli-1.16-7.el8.x86_64
----
. 를 설치합니다 `libnvme` 패키지:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
다음 예제는 libnvme 패키지 버전을 보여줍니다.

+
[listing]
----
libnvme-1.4-3.el8.x86_64
----
. 인커널 NVMe 다중 경로 지원:
+
[source, cli]
----
grubby --args=nvme_core.multipath=Y --update-kernel /boot/vmlinuz-4.18.0-477.10.1.el8_8.x86_64
----
. RHEL 8.8 호스트에서 다음을 확인하세요. `hostnqn` 문자열 `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
다음 예에서는 다음을 보여줍니다.  `hostnqn` 버전:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
----
. 다음을 확인하십시오. `hostnqn` 문자열이 일치합니다 `hostnqn` ONTAP 스토리지 시스템의 해당 하위 시스템에 대한 문자열:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Vserver     Subsystem          Host NQN
----------- --------------- ----------------------------------------------------------
vs_nvme161   rhel_161_LPe32002    nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
----
====
+

NOTE: 만약 `hostnqn` 문자열이 일치하지 않으면 다음을 사용하세요. `vserver modify` 업데이트 명령 `hostnqn` 해당 ONTAP 스토리지 시스템 하위 시스템의 문자열을 일치시키세요. `hostnqn` 문자열에서 `/etc/nvme/hostnqn` 호스트에서.

. 호스트를 재부팅합니다.
+
[NOTE]
====
동일한 호스트에서 NVMe와 SCSI 트래픽을 모두 실행하려면 NetApp ONTAP 네임스페이스에 커널 내 NVMe 멀티패스를 사용하고 ONTAP LUN에 dm-multipath를 사용할 것을 권장합니다.  dm-multipath가 ONTAP 네임스페이스 장치를 청구하지 못하도록 하려면 다음을 추가하여 제외합니다. `enable_foreign` 설정 `/etc/multipath.conf` 파일:

[source, cli]
----
cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
====




== 3단계: NVMe/FC 및 NVMe/TCP 구성

Broadcom/Emulex 또는 Marvell/QLogic 어댑터를 사용하여 NVMe/FC를 구성하거나 수동 검색 및 연결 작업을 사용하여 NVMe/TCP를 구성합니다.

[role="tabbed-block"]
====
.FC - 브로드컴/에뮬렉스
--
Broadcom/Emulex 어댑터용 NVMe/FC를 구성합니다.

.단계
. 지원되는 어댑터 모델을 사용하고 있는지 확인합니다.
+
.. 모델 이름을 표시합니다:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
다음 예와 비슷한 출력이 표시됩니다.

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
.. 모델 설명을 표시합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
다음 예와 비슷한 출력이 표시됩니다.

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----


. 권장 Broadcom을 사용하고 있는지 확인합니다 `lpfc` 펌웨어 및 받은 편지함 드라이버:
+
.. 펌웨어 버전을 표시합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
이 명령은 펌웨어 버전을 반환합니다.

+
[listing]
----
14.0.639.18, sli-4:2:c
14.0.639.18, sli-4:2:c
----
.. 받은 편지함 드라이버 버전을 표시합니다.
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
다음 예에서는 드라이버 버전을 보여줍니다.

+
[listing]
----
0:14.0.0.18
----


+
지원되는 어댑터 드라이버 및 펌웨어 버전의 현재 목록은 를 참조하십시오link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^].

. 확인합니다 `lpfc_enable_fc4_type` 가 로 설정되어 있습니다 `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 이니시에이터 포트를 볼 수 있는지 확인합니다.
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
다음 예와 비슷한 출력이 표시됩니다.

+
[listing]
----
0x100000109b1c1204
0x100000109b1c1205
----
. 이니시에이터 포트가 온라인 상태인지 확인합니다.
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Online
Online
----
. NVMe/FC 이니시에이터 포트가 활성화되었고 타겟 포트가 표시되는지 확인합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 *ONLINE*
NVME RPORT       WWPN x2049d039ea36a105 WWNN x2048d039ea36a105 DID x0a0c0a *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x204bd039ea36a105 WWNN x2048d039ea36a105 DID x0a100a *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000134 Cmpl 0000000134 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000825e567 Issue 000000000825d7ed OutIO fffffffffffff286
abort 0000027c noxri 00000000 nondlp 00000a02 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000782 Err 000130fa

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 *ONLINE*
NVME RPORT       WWPN x204ad039ea36a105 WWNN x2048d039ea36a105 DID x0a080a *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x204cd039ea36a105 WWNN x2048d039ea36a105 DID x0a090a *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000134 Cmpl 0000000134 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000826ced5 Issue 000000000826c226 OutIO fffffffffffff351
        abort 0000029d noxri 00000000 nondlp 000008df qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000821 Err 00012fcd
----
=====


--
.FC - 마벨/Q로직
--
Marvell/QLogic 어댑터용 NVMe/FC를 구성합니다.

.단계
. 지원되는 어댑터 드라이버와 펌웨어 버전을 사용하고 있는지 확인하세요.
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
다음 예에서는 드라이버와 펌웨어 버전을 보여줍니다.

+
[listing]
----
QLE2772 FW:v9.10.11 DVR:v10.02.07.900-k-debug
QLE2772 FW:v9.10.11 DVR:v10.02.07.900-k-debug
----
. 확인합니다 `ql2xnvmeenable` 가 설정됩니다. 그러면 Marvell 어댑터가 NVMe/FC Initiator로 작동할 수 있습니다.
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
예상 출력은 1입니다.



--
.TCP
--
NVMe/TCP 프로토콜은 자동 연결 작업을 지원하지 않습니다.  대신 NVMe/TCP를 수행하여 NVMe/TCP 하위 시스템과 네임스페이스를 검색할 수 있습니다. `connect` 또는 `connect-all` 수동으로 작업합니다.

.단계
. 지원되는 NVMe/TCP LIF를 통해 개시자 포트가 검색 로그 페이지 데이터를 가져올 수 있는지 확인하세요.
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.14

Discovery Log Number of Records 8, Generation counter 10
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  0
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.111.15
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.14
sectype: none
----
=====
. 다른 NVMe/TCP 개시자-대상 LIF 조합이 검색 로그 페이지 데이터를 성공적으로 검색할 수 있는지 확인합니다.
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.14
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.15
nvme discover -t tcp -w 192.168.211.79 -a 192.168.211.14
nvme discover -t tcp -w 192.168.211.79 -a 192.168.211.15
----
=====
. 를 실행합니다 `nvme connect-all` 노드에 걸쳐 지원되는 모든 NVMe/TCP 이니시에이터-타겟 LIF에 대한 명령:
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr -1 1800
----
+
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme connect-all -t tcp -w 192.168.111.79 -a 192.168.111.14 -l 1800
nvme connect-all -t tcp -w 192.168.111.79 -a 192.168.111.15 -l 1800
nvme connect-all -t tcp -w 192.168.211.79 -a 192.168.211.14 -l 1800
nvme connect-all -t tcp -w 192.168.211.79 -a 192.168.211.15 -l 1800
----
=====


--
====


== 4단계: 선택적으로 NVMe/FC에 대해 1MB I/O를 활성화합니다.

ONTAP Identify Controller 데이터에서 최대 데이터 전송 크기(MDTS)를 8로 보고합니다.  즉, 최대 I/O 요청 크기는 1MB까지 가능합니다.  Broadcom NVMe/FC 호스트에 대해 1MB 크기의 I/O 요청을 발행하려면 다음을 늘려야 합니다. `lpfc` 의 가치 `lpfc_sg_seg_cnt` 매개변수를 기본값 64에서 256으로 변경합니다.


NOTE: 이 단계는 Qlogic NVMe/FC 호스트에는 적용되지 않습니다.

.단계
.  `lpfc_sg_seg_cnt`매개변수를 256으로 설정합니다.
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
다음 예와 비슷한 출력이 표시되어야 합니다.

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
.  `dracut -f`명령을 실행하고 호스트를 재부팅합니다.
. 의 값이 256인지 `lpfc_sg_seg_cnt` 확인합니다.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 5단계: NVMe-oF 검증

커널 내 NVMe 다중 경로 상태, ANA 상태 및 ONTAP 네임스페이스가 NVMe-oF 구성에 적합한지 확인합니다.

.단계
. in-kernel NVMe multipath가 활성화되어 있는지 확인합니다.
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Y
----
. 각 ONTAP 네임스페이스에 대한 적절한 NVMe-oF 설정(예: NetApp ONTAP 컨트롤러로 설정된 모델 및 라운드 로빈으로 설정된 로드 밸런싱 IPolicy가 호스트에 올바르게 반영되는지 확인합니다.
+
.. 하위 시스템을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 정책을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
round-robin
round-robin
----


. 호스트에서 네임스페이스가 생성되고 올바르게 검색되는지 확인합니다.
+
[source, cli]
----
nvme list
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. 각 경로의 컨트롤러 상태가 라이브이고 올바른 ANA 상태인지 확인합니다.
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme3n1
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.ab4fa6a5ba8b11ecbe3dd039ea359e4b:subsystem.rhel_161_Lpe32002
\
 +- nvme0 fc traddr=nn-0x2048d039ea36a105:pn-0x204cd039ea36a105 host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 *live non-optimized*
 +- nvme1 fc traddr=nn-0x2048d039ea36a105:pn-0x204ad039ea36a105 host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 *live optimized*
 +- nvme2 fc traddr=nn-0x2048d039ea36a105:pn-0x204bd039ea36a105 host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 *live non-optimized*
 +- nvme4 fc traddr=nn-0x2048d039ea36a105:pn-0x2049d039ea36a105 host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 *live optimized*
----
=====
--
.NVMe/TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme0n1
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
\
 +- nvme0 tcp traddr=192.168.111.15 trsvcid=4420 host_traddr=192.168.111.79 *live non-optimized*
 +- nvme1 tcp traddr=192.168.111.14 trsvcid=4420 host_traddr=192.168.111.79 *live optimized*
 +- nvme2 tcp traddr=192.168.211.15 trsvcid=4420 host_traddr=192.168.211.79 *live non-optimized*
----
=====
--
====
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다.
+
[role="tabbed-block"]
====
.열
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme0n1 vs_tcp           /vol/vol1/ns1



NSID       UUID                                   Size
------------------------------------------------------------
1          338d73ce-b5a8-4847-9cc9-b127c75d8855	21.47GB
----
=====
--
.JSON을 참조하십시오
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
  "ONTAPdevices" : [
    {
      "Device" : "/dev/nvme0n1",
      "Vserver" : "vs_tcp79",
      "Namespace_Path" : "/vol/vol1/ns1",
      "NSID" : 1,
      "UUID" : "338d73ce-b5a8-4847-9cc9-b127c75d8855",
      "Size" : "21.47GB",
      "LBA_Data_Size" : 4096,
      "Namespace_Size" : 5242880
    },
]

}
----
=====
--
====




== 6단계: 알려진 문제를 검토합니다

알려진 문제는 다음과 같습니다.

[cols="20,40,40"]
|===
| NetApp 버그 ID | 제목 | 설명 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"] | RHEL 8.8 NVMe-oF 호스트는 중복된 PDC(지속적 검색 컨트롤러)를 생성합니다. | NVMe-oF 호스트에서는 "nvme discover -p" 명령을 사용하여 PDC를 생성할 수 있습니다.  이 명령을 사용하면 개시자-대상 조합당 하나의 PDC만 생성되어야 합니다.  하지만 NVMe-oF 호스트에서 RHEL 8.8을 실행하는 경우 "nvme discover -p"를 실행할 때마다 중복된 PDC가 생성됩니다.  이로 인해 호스트와 대상 모두에서 불필요한 리소스 사용이 발생합니다. 
|===