---
sidebar: sidebar 
permalink: nvme_ol_78.html 
keywords: nvme, linux, oracle, 7.8 
summary: 예를 들어, Oracle Linux 7.8용 VME/FC 호스트 구성을 ONTAP와 함께 설정합니다 
---
= Oracle Linux 7.8 및 ONTAP용 NVMe/FC 호스트 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle Linux 7.8 및 ONTAP를 타겟으로 실행하는 이니시에이터 호스트에서 NVMe/FC(NVMe over Fibre Channel)를 구성할 수 있습니다.



== 지원 가능성

ONTAP 9.6부터 Oracle Linux 7.8에서 NVMe/FC가 지원됩니다. Oracle Linux 7.8 호스트는 동일한 FC(Fibre Channel) 이니시에이터 어댑터 포트를 통해 NVMe 및 SCSI 트래픽을 모두 실행할 수 있습니다. Broadcom 이니시에이터는 동일한 FC 어댑터 포트를 통해 NVMe/FC 및 FCP 트래픽을 모두 처리할 수 있습니다. 지원되는 FC 어댑터 및 컨트롤러 목록은 를 link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] 참조하십시오. 지원되는 구성의 현재 목록은 을 link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^]참조하십시오.


NOTE: 이 절차에 제공된 구성 설정을 사용하여 및 에 연결된 클라우드 클라이언트를 구성할 수 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^]있습니다.



== 알려진 제한 사항

* 기본 NVMe/FC 자동 연결 스크립트는 NVMe-CLI 패키지에서 사용할 수 없습니다. HBA 공급업체에서 제공한 외부 자동 연결 스크립트를 사용합니다.
* 기본적으로 라운드 로빈 로드 밸런싱은 NVMe 다중 경로에 사용되지 않습니다. 이 기능을 사용하려면 udev 규칙을 작성해야 합니다. Oracle Linux 7.8에서 NVMe/FC 활성화 섹션에 단계가 나와 있습니다.
* NVMe/FC에 대한 sanlun 지원은 없으며, 따라서 Oracle Linux 7.8에서 NVMe/FC에 대한 Linux Host Utilities가 지원되지 않습니다. 기본 NVMe-CLI에 포함된 NetApp 플러그인의 일부로 제공되는 ONTAP 명령 출력을 사용합니다.
* 현재 NVMe-oF 프로토콜을 사용한 SAN 부팅은 지원되지 않습니다.




== NVMe/FC 활성화

. 서버에 Oracle Linux 7.8을 설치합니다.
. 설치가 완료되면 지원되는 Unbreakable Enterprise 커널을 실행 중인지 확인합니다. 를 link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^]참조하십시오.
+
[listing]
----
# uname -r
4.14.35-1902.9.2.el7uek
----
. NVMe-CLI 패키지를 업그레이드합니다.
+
[listing]
----
# rpm -qa | grep nvme-cli
nvme-cli-1.8.1-3.el7.x86_64
----
. 아래 문자열을 /lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules 에서 별도의 udev 규칙으로 추가합니다. 이를 통해 NVMe 다중 경로에 라운드 로빈 로드 밸런싱을 사용할 수 있습니다.
+
[listing]
----
# cat /lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules
# Enable round-robin for NetApp ONTAP
ACTION=="add", SUBSYSTEM=="nvme-subsystem", ATTR{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="round-robin"
----
. Oracle Linux L 7.8 호스트에서 /etc/NVMe/hostnqn의 호스트 NQN 문자열을 확인하고 ONTAP 스토리지에 있는 해당 하위 시스템의 호스트 NQN 문자열과 일치하는지 확인합니다.
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
ol_157_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
hostnqn+ 문자열이 일치하지 않으면 vserver modify 명령을 사용하여 해당 ONTAP 어레이 하위 시스템의 호스트 NQN 문자열을 호스트의 etc/NVMe/hostnqn에서 호스트 NQN 문자열과 일치하도록 업데이트해야 합니다.

. 호스트를 재부팅합니다.




== NVMe/FC용 Broadcom FC 어댑터 구성

. 지원되는 어댑터를 사용하고 있는지 확인합니다. 지원되는 어댑터의 현재 목록은 를 참조하십시오link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. lpfc의 NVMe 지원은 기본적으로 이미 활성화되어 있습니다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
+
최신 lpfc 드라이버(수신함 및 아웃박스 모두)에는 lpfc_enable_fc4_type 기본값이 3으로 설정되어 있습니다. 따라서 /etc/modprobe.d/lpfc.conf에서 명시적으로 설정할 필요가 없습니다.

. 그런 다음 권장되는 lpfc 자동 연결 스크립트를 설치합니다.
+
 # rpm -ivh nvmefc-connect-12.4.65.0-1.noarch.rpm
. 자동 연결 스크립트가 설치되어 있는지 확인합니다.
+
[listing]
----
# rpm -qa | grep nvmefc
nvmefc-connect-12.4.65.0-1.noarch
----
. 이니시에이터 포트가 실행 중인지 확인합니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62

# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. NVMe/FC 이니시에이터 포트가 활성화되고 타겟 포트를 볼 수 있으며 모두 작동 및 실행 중인지 확인합니다.
+
아래 예에서는 아래 출력에 표시된 것처럼 단일 이니시에이터 포트만 사용하도록 설정되어 두 개의 타겟 LIF에 연결되어 있습니다.

+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info

NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2947 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
----




== NVMe/FC 확인 중

. 다음 NVMe/FC 설정을 확인하십시오.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
+
위 예에서는 두 개의 네임스페이스가 Oracle Linux 7.8 ANA 호스트에 매핑됩니다. 이러한 LIF는 4개의 타겟 LIF: 2개의 로컬 노드 LIF와 2개의 다른 파트너/원격 노드 LIF를 통해 확인할 수 있습니다. 이 설정은 호스트의 각 네임스페이스에 대해 ANA 최적화 경로 2개와 ANA 접근 불가 경로 2개로 표시됩니다.

. 네임스페이스가 만들어졌는지 확인합니다.
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. ANA 경로 상태를 확인한다.
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.ol_157_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. ONTAP 장치용 NetApp 플러그인을 확인합니다.
+
[listing]
----
# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/ol_157_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/ol_157_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----




== Broadcom NVMe/FC의 1MB I/O 크기 활성화

ONTAP Identify Controller 데이터에서 최대 데이터 전송 크기(MDTS)를 8로 보고합니다.  즉, 최대 I/O 요청 크기는 1MB까지 가능합니다.  Broadcom NVMe/FC 호스트에 대해 1MB 크기의 I/O 요청을 발행하려면 다음을 늘려야 합니다. `lpfc` 의 가치 `lpfc_sg_seg_cnt` 매개변수를 기본값 64에서 256으로 변경합니다.


NOTE: 이 단계는 Qlogic NVMe/FC 호스트에는 적용되지 않습니다.

.단계
.  `lpfc_sg_seg_cnt`매개변수를 256으로 설정합니다.
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
다음 예와 비슷한 출력이 표시되어야 합니다.

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
.  `dracut -f`명령을 실행하고 호스트를 재부팅합니다.
. 의 값이 256인지 `lpfc_sg_seg_cnt` 확인합니다.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----

