---
sidebar: sidebar 
permalink: nvme_rhel_90.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: ONTAP를 사용하여 RHEL 9.0용 NVMe-oF 호스트를 구성하는 방법 
---
= ONTAP가 있는 RHEL 9.0에 대한 NVMe-oF 호스트 구성
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:source-highlighter: highlighter.js
:toc-position: content




== 지원 가능성

NVMe-oF(NVMe/FC 및 NVMe/TCP 포함)는 ONTAP 어레이에서 정상적인 스토리지 장애 조치(SFO)에 필요한 ANA(Asymmetric Namespace Access)가 있는 RHEL 9.0에서 지원됩니다. ANA는 NVM-of 환경에서 ALUA와 동등한 제품이며 현재 In-kernel NVMe Multipath로 구현되고 있습니다. 이 문서에는 RHEL 9.0에서 ANA를 사용하고 ONTAP를 대상으로 커널 내 NVMe 다중 경로를 사용하여 NVMe-oF를 활성화하는 방법에 대한 세부 정보가 포함되어 있습니다.



== 피처

* RHEL 9.0부터 NVMe/TCP는 더 이상 기술 미리 보기 기능(RHEL 8과 다름)이 아니라 완전히 지원되는 엔터프라이즈 기능 자체입니다.
* RHEL 9.0부터는 명시적 설정 없이 커널 내 NVMe 다중 경로가 기본적으로 NVMe 네임스페이스에 대해 활성화됩니다(RHEL 8과 다름).




== 제한 사항

* NVMe/FC와 달리 NVMe/TCP에는 자동 연결 기능이 없습니다. 이는 Linux 호스트에서 다음과 같은 두 가지 주요 제한 사항을 반영합니다.
+
** 경로가 복구되면 자동 재연결되지 않음 - NVMe/TCP는 경로가 다운된 후 10분 동안 기본 'Ctrl-Loss-TMO'를 벗어나 복원되는 경로에 자동으로 다시 연결할 수 없습니다.
** 호스트 부팅 중에 자동 연결 안 됨 - NVMe/TCP는 호스트 부팅 중에도 자동으로 연결할 수 없습니다. NVMe/TCP용 SFO와 같은 ONTAP 장애 조치 이벤트를 편안하게 넘기 위해서는 Ctrl_Loss_TMO 타이머를 조정하여 30분 등 더 긴 재시도 시간을 설정하는 것이 좋습니다.






== 구성 요구 사항

을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 지원되는 구성에 대한 자세한 내용은 를 참조하십시오.



== In-kernel NVMe Multipath를 활성화합니다

.단계
. 서버에 RHEL 9.0을 설치합니다. 설치가 완료되면 지정된 RHEL 9.0 커널을 실행 중인지 확인합니다. 을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 를 참조하십시오.
. 설치가 완료되면 지정된 RHEL 9.0 커널을 실행 중인지 확인합니다. 을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 를 참조하십시오.
+
[listing]
----
# uname -r
5.14.0-70.13.1.el9_0.x86_64
----
. NVMe-CLI 패키지를 설치합니다.
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.16-3.el9.x86_64
----
. 호스트에서 '/etc/NVMe/hostnqn'의 호스트 NQN 문자열을 확인하고 ONTAP 배열의 해당 하위 시스템에 대한 호스트 NQN 문자열과 일치하는지 확인합니다. 예를 들면, 다음과 같습니다.
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver     Subsystem Host     NQN
----------- --------------- ----------------------------------------------------------
vs_fcnvme_14 nvme_141_1 nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+

NOTE: 호스트 NQN 문자열이 일치하지 않으면 "vserver modify" 명령을 사용하여 해당 ONTAP NVMe 하위 시스템의 호스트 NQN 문자열을 업데이트하여 호스트의 '/etc/NVMe/hostnqn'에서 호스트 NQN 문자열과 일치시켜야 합니다.

. 호스트를 재부팅합니다.




== NVMe/FC 구성



=== Broadcom/Emulex

. 지원되는 어댑터를 사용하고 있는지 확인합니다. 지원되는 어댑터의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 권장 Broadcom lpfc 펌웨어 및 받은 편지함 드라이버를 사용하고 있는지 확인합니다. 지원되는 어댑터 드라이버 및 펌웨어 버전의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.8.351.47, sli-4:2:c
12.8.351.47, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:14.0.0.4
----
. lpfc_enable_fc4_type이 3으로 설정되어 있는지 확인한다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 이니시에이터 포트가 실행 중이며 타겟 LIF를 볼 수 있는지 확인합니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info

NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. 1MB I/O 크기 활성화
+
lpfc 드라이버가 입출력 요청을 1MB 크기로 발급하려면 lpfc_sg_seg_cnt 매개변수를 256으로 설정해야 합니다.

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
+
.. dracut -f 명령을 실행한 다음 호스트를 재부팅합니다.
.. 호스트 부팅 후 lpfc_sg_seg_cnt가 256으로 설정되어 있는지 확인합니다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----






=== Marvell/QLogic

RHEL 9.0 커널에 포함된 기본 받은 편지함 qla2xxx 드라이버에는 ONTAP 지원에 필수적인 최신 업스트림 픽스가 포함되어 있습니다. 지원되는 어댑터 드라이버 및 펌웨어 버전을 실행하고 있는지 확인합니다.

[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2742 FW:v9.06.02 DVR:v10.02.00.200-k
QLE2742 FW:v9.06.02 DVR:v10.02.00.200-k
----
Marvell 어댑터가 NVMe/FC Initiator로 작동하도록 하는 "ql2xnvmeenable"이 설정되어 있는지 확인합니다.

[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


== NVMe/TCP를 구성합니다

NVMe/FC와 달리 NVMe/TCP에는 자동 연결 기능이 없습니다. Linux NVMe/TCP 호스트에 대한 두 가지 주요 제한 사항이 반영되어 있습니다.

* 경로가 복구되면 자동 재연결되지 않음 - NVMe/TCP는 경로가 다운된 후 10분 동안 기본 'Ctrl-Loss-TMO'를 벗어나 복원되는 경로에 자동으로 다시 연결할 수 없습니다.
* 호스트 부팅 중에 자동 연결 안 됨 - NVMe/TCP는 호스트 부팅 중에도 자동으로 연결할 수 없습니다. SFO와 같은 ONTAP 장애 조치 이벤트를 편안하게 넘기 위해서는 Ctrl_Loss_TMO 타이머를 조정하여 30분 등 더 긴 재시도 시간을 설정하는 것이 좋습니다. 다음은 세부 정보입니다.


.단계
. 이니시에이터 포트가 지원되는 NVMe/TCP LIF에서 검색 로그 페이지 데이터를 가져올 수 있는지 확인합니다.
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51

Discovery Log Number of Records 10, Generation counter 119
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.2.56
sectype: none
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.1.51
sectype: none
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_2
traddr: 192.168.2.56
sectype: none
...
----
. 마찬가지로, 다른 NVMe/TCP 이니시에이터 타겟 LIF 콤보에서 검색 로그 페이지 데이터를 성공적으로 가져올 수 있는지 확인하십시오. 예를 들면, 다음과 같습니다.
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.52
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.56
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.57
----
. 노드를 통해 지원되는 모든 NVMe/TCP 이니시에이터-타겟 LIF에서 'NVMe connect-all' 명령을 실행합니다. 연결 중에 더 긴 "Ctrl_Loss_TMO" 기간(예: 30분, '-l 1800'을 통해 설정 가능)을 경과하여 경로 손실 시 더 긴 기간 동안 재시도해야 합니다. 예를 들면, 다음과 같습니다.
+
[listing]
----
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.51 -l 1800
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.52 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.56 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.57 -l 1800
----




== NVMf 확인

. 다음을 확인하여 In-kernel NVMe multipath가 실제로 활성화되어 있는지 확인합니다.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
. 각 ONTAP 네임스페이스에 대한 적절한 NVMf 설정(예: 모델이 'NetApp ONTAP 컨트롤러'로 설정되고 로드 밸런싱이 '라운드 로빈'으로 설정된 모델)이 호스트에 올바로 반영되는지 확인합니다.
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. ONTAP 네임스페이스가 호스트에 제대로 반영되는지 확인합니다. 예를 들어 (A),
+
[listing]
----
# nvme list
Node         SN                    Model                   Namespace   Usage
------      ---------------------------------------      ------------------------
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller  1          85.90 GB / 85.90 GB

Format         FW Rev
---------------------
4 KiB + 0 B   FFFFFFFF
----
+
예 (b):

+
[listing]
----
# nvme list
Node           SN                   Model                    Namespace   Usage
---------------------------------------------------- ------------------------------------
/dev/nvme0n1   81CZ5BQuUNfGAAAAAAAB NetApp ONTAP Controller   1         85.90 GB / 85.90 GB

Format         FW Rev
-----------------------
4 KiB + 0 B   FFFFFFFF
----
. 각 경로의 컨트롤러 상태가 라이브이고 적절한 ANA 상태인지 확인합니다. 예를 들어 (A),
+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_141_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
----
+
예 (b):

+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
\
+- nvme0 tcp traddr=192.168.1.51 trsvcid=4420 host_traddr=192.168.1.8 live optimized
+- nvme10 tcp traddr=192.168.2.56 trsvcid=4420 host_traddr=192.168.2.9 live optimized
+- nvme15 tcp traddr=192.168.2.57 trsvcid=4420 host_traddr=192.168.2.9 live non-optimized
+- nvme5 tcp traddr=192.168.1.52 trsvcid=4420 host_traddr=192.168.1.8 live non-optimized
----
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다. 예를 들어 (A),
+
[listing]
----
# nvme netapp ontapdevices -o column
Device       Vserver        Namespace Path                            NSID
----------------------- ------------------------------ -------------------------
/dev/nvme0n1  vs_fcnvme_141  /vol/fcnvme_141_vol_1_1_0/fcnvme_141_ns   1

UUID                                   Size
--------------------------------------------
72b887b1-5fb6-47b8-be0b-33326e2542e2   85.90GB

# nvme netapp ontapdevices -o json
{
"ONTAPdevices" : [
    {
        "Device" : "/dev/nvme0n1",
        "Vserver" : "vs_fcnvme_141",
        "Namespace_Path" : "/vol/fcnvme_141_vol_1_1_0/fcnvme_141_ns",
        "NSID" : 1,
        "UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
    }
  ]
}
----
+
예 (b):

+
[listing]
----
# nvme netapp ontapdevices -o column
Device               Vserver                   Namespace Path
--------------------- ------------------------- ------------------------------------
/dev/nvme0n1         vs_tcp_118                /vol/tcpnvme_118_1_0_0/tcpnvme_118_ns

NSID   UUID                               Size
-------------------------------------------------
1     4a3e89de-b239-45d8-be0c-b81f6418283c 85.90GB
----
+
[listing]
----
# nvme netapp ontapdevices -o json
{
"ONTAPdevices" : [
    {
     "Device" : "/dev/nvme0n1",
      "Vserver" : "vs_tcp_118",
      "Namespace_Path" : "/vol/tcpnvme_118_1_0_0/tcpnvme_118_ns",
      "NSID" : 1,
      "UUID" : "4a3e89de-b239-45d8-be0c-b81f6418283c",
      "Size" : "85.90GB",
      "LBA_Data_Size" : 4096,
      "Namespace_Size" : 20971520
    },
  ]

}
----




== 기술 지원 문의 시기

NVMe/FC 오류에 대한 문제 해결을 시작하기 전에 항상 IMT 사양을 준수하는 구성을 실행 중인지 확인하십시오. 호스트 측 문제를 디버깅하려면 다음 단계를 수행하십시오.



=== lpfc 세부 정보 로깅

driver/scsi/lpfc/lpfc_logmsg.h에서 볼 수 있는 NVMe/FC에 사용할 수 있는 비트 마스크를 로깅하는 lpfc 드라이버 목록은 다음과 같습니다.

[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
"lpfc" 드라이버 관점에서 NVMe/FC 이벤트를 로깅하기 위해 위의 모든 값으로 "lpfc_log_verbose" 드라이버 설정("/etc/modprobe.d/lpfc.conf"의 lpfc 행에 추가됨)을 설정할 수 있습니다. 그런 다음 dracut -f 명령을 실행하여 initiramfs를 다시 생성한 다음 호스트를 재부팅합니다. 재부팅 후 위의 'log_NVMe_disc' 비트마스크를 예로 사용하여 상세 로깅이 적용되었는지 확인합니다.

[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc_enable_fc4_type=3 lpfc_log_verbose=0xf00083
----
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


=== qla2xxx 세부 정보 로깅

lpfc와 마찬가지로 NVMe/FC에 대한 유사한 특정 qla2xxx 로깅이 없습니다. 여기서 일반적인 qla2xxx 로깅 수준을 설정할 수 있습니다(예: "ql2xextended_error_logging=0x1e400000"). 이 값은 해당 'modprobe qla2xxx conf' 파일에 추가하면 됩니다. 그런 다음 드라쿠트-프(dracut-f)를 실행하여 initramfs를 다시 만든 다음 호스트를 재부팅합니다. 재부팅 후 상세 로깅이 다음과 같이 적용되었는지 확인합니다.

[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
----
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


=== 일반적인 NVMe-CLI 오류 및 해결 방법

[cols="20, 20, 50"]
|===
| NVMe-CLI에 표시되는 오류 | 가능한 원인 | 해결 방법 


| /dev/NVMe-fabric에 쓸 수 없음: NVMe 발견, NVMe 연결 또는 NVMe 연결 중 잘못된 인수 오류 | 이 오류 메시지는 일반적으로 구문이 잘못된 경우 표시됩니다. | 위의 NVMe 명령에 올바른 구문을 사용하고 있는지 확인하십시오. 


| NVMe Discover, NVMe connect, NVMe connect에 쓰는 동안 /dev/NVMe-fabric에 쓰는 데 실패했습니다 | 여러 가지 문제로 인해 이 문제가 발생할 수 있습니다. 일반적인 경우 위의 NVMe 명령에 잘못된 인수를 전달했습니다.  a| 
위 명령에 대한 적절한 인수(예: 적절한 WWNN 문자열, WWPN 문자열 등)를 전달했는지 확인하십시오. 인수가 올바르지만 여전히 이 오류가 표시되는 경우 NVMe 이니시에이터가 "Enabled"로 표시되고 NVMe/FC target LIF가 원격 포트 섹션 아래에 올바르게 표시되는지 '/sys/class/scsi_host/host * /NVMe_info' 출력이 올바른지 확인하십시오. 예를 들면, 다음과 같습니다.

[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001

NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
해결책: 타겟 LIF가 "NVMe_info" 출력에서 위와 같이 표시되지 않으면 의심되는 NVMe/FC 오류에 대해 '/var/log/messages' 및 'dmesg' 출력을 확인하여 그에 따라 보고 또는 수정하십시오.



| NVMe discover, NVMe connect 또는 NVMe connect-all 중에 가져올 검색 로그 항목이 없습니다 | 이 오류 메시지는 일반적으로 '/etc/NVMe/hostnqn' 문자열이 NetApp 어레이의 해당 하위 시스템에 추가되지 않았거나 잘못된 hostnqn 문자열이 해당 하위 시스템에 추가된 경우에 표시됩니다. | 정확한 '/etc/NVMe/hostnqn' 문자열이 NetApp 어레이의 해당 하위 시스템에 추가되었는지 확인합니다('vserver NVMe subsystem host show'를 통해 확인). 


| NVMe Discover, NVMe connect 또는 NVMe connect-all에서 /dev/NVMe-fabric:Operation already in progress | 이 오류 메시지는 컨트롤러 연결 또는 지정된 작업이 이미 생성되었거나 생성 중인 경우에 표시됩니다. 이 문제는 위에 설치된 자동 연결 스크립트의 일부로 발생할 수 있습니다. | 없음. "NVMe 검색"을 위해 잠시 후에 이 명령을 실행해 보십시오. NVMe connect와 connect-all의 경우 NVMe list를 실행하여 네임스페이스 디바이스가 이미 생성되어 호스트에 표시되는지 확인합니다. 
|===


=== 디버깅에 필요한 파일 및 명령 출력입니다

여전히 문제가 발생하는 경우 다음 파일 및 명령 출력을 수집하여 추가 분류를 위해 보내주십시오.

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----