---
sidebar: sidebar 
permalink: nvme-ol-7x.html 
keywords: nvme, linux, oracle, 7x 
summary: 'ONTAP 사용하여 Oracle Linux 7x에 대한 VMe/FC 호스트 구성 설정(예제 포함)' 
---
= ONTAP 스토리지를 위한 NVMe-oF로 Oracle Linux 7x 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle Linux 호스트는 비대칭 네임스페이스 액세스(ANA)를 통해 NVMe over Fibre Channel(NVMe/FC) 및 NVMe over TCP(NVMe/TCP) 프로토콜을 지원합니다. ANA는 iSCSI 및 FCP 환경에서 ALUA(비대칭 논리 장치 액세스)와 동일한 다중 경로 기능을 제공합니다.

Oracle Linux 7x에 대해 NVMe over Fabrics(NVMe-oF) 호스트를 구성하는 방법을 알아보세요. 추가 지원 및 기능 정보는 다음을 참조하세요. link:nvme-ol-supported-features.html["Oracle Linux ONTAP 지원 및 기능"].

Oracle Linux 7x를 사용하는 NVMe-oF에는 다음과 같은 알려진 제한 사항이 있습니다.

* NVMe-oF 프로토콜을 사용한 SAN 부팅은 지원되지 않습니다.
* NetApp sanlun 호스트 유틸리티는 Oracle Linux 7x 호스트의 NVMe-oF에 대해 지원되지 않습니다. 대신, 기본으로 포함된 NetApp 플러그인을 사용할 수 있습니다. `nvme-cli` 모든 NVMe-oF 전송을 위한 패키지입니다.
* 기본 NVMe/FC 자동 연결 스크립트는 NVMe-CLI 패키지에서 사용할 수 없습니다. HBA 공급업체에서 제공한 외부 자동 연결 스크립트를 사용합니다.
* NVMe 멀티패스의 경우 라운드 로빈 부하 분산은 기본적으로 활성화되어 있지 않습니다.  이 기능을 사용하려면 udev 규칙을 작성하세요.




== 1단계: Oracle Linux 및 NVMe 소프트웨어 설치 및 구성 확인

다음 절차에 따라 지원되는 최소 Oracle Linux 7x 소프트웨어 버전을 확인하세요.

.단계
. 서버에 Oracle Linux 7x를 설치합니다.  설치가 완료된 후 지정된 Oracle Linux 7x 커널을 실행하고 있는지 확인하세요.
+
[source, cli]
----
uname -r
----
+
Oracle Linux 커널 버전 예:

+
[listing]
----
5.4.17-2011.6.2.el7uek.x86_64
----
. "NVMe-CLI" 패키지를 설치합니다.
+
[source, cli]
----
rpm -qa | grep nvme-cli
----
+
다음 예에서는 다음을 보여줍니다.  `nvme-cli` 패키지 버전:

+
[listing]
----
nvme-cli-1.8.1-3.el7.x86_64
----
. 다음 문자열을 별도의 udev 규칙으로 추가합니다. `/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules` .  이를 통해 NVMe 멀티패스에 대한 라운드 로빈 부하 분산이 가능해집니다.
+
[source, cli]
----
cat /lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules
Enable round-robin for NetApp ONTAP
ACTION=="add", SUBSYSTEMS=="nvme-subsystem", ATTRS{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="round-robin"
----
. Oracle Linux 7x 호스트에서 다음을 확인하세요. `hostnqn` 문자열 `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
다음 예에서는 다음을 보여줍니다.  `hostnqn` 버전:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:497ad959-e6d0-4987-8dc2-a89267400874
----
. ONTAP 시스템에서 다음을 확인하십시오. `hostnqn` 문자열이 일치합니다 `hostnqn` ONTAP 스토리지 시스템의 해당 하위 시스템에 대한 문자열:
+
[source, cli]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
ol_157_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:497ad959-e6d0-4987-8dc2-a89267400874
----
====
+

NOTE: 문자열이 일치하지 않으면 `hostnqn` 명령을 `hostnqn` 사용하여 `vserver modify` 해당 ONTAP 배열 하위 시스템의 문자열을 `/etc/nvme/hostnqn` 호스트의 문자열과 일치하도록 `hostnqn` 업데이트합니다.

. 호스트를 재부팅합니다.




== 2단계: NVMe/FC 구성

Broadcom/Emulex 어댑터용 NVMe/FC를 구성합니다.

. 지원되는 어댑터 모델을 사용 중인지 확인합니다.
+
.. 모델 이름을 표시합니다:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
.. 모델 설명을 표시합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
다음 예와 비슷한 출력이 표시되어야 합니다.

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----


. 가 "3"으로 설정되어 있는지 `lpfc_enable_fc4_type` 확인합니다.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 권장하는 lpfc 자동 연결 스크립트를 설치하세요.
+
[source, cli]
----
rpm -ivh nvmefc-connect-12.8.264.0-1.noarch.rpm
----
. 자동 연결 스크립트가 설치되었는지 확인하세요.
+
[source, cli]
----
rpm -qa | grep nvmefc
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
nvmefc-connect-12.8.264.0-1.noarch
----
. 이니시에이터 포트가 온라인 상태인지 확인합니다.
+
.. 포트 이름을 표시합니다:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
0x10000090fae0ec61
0x10000090fae0ec62
----
.. 포트 이름을 표시합니다:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Online
Online
----


. NVMe/FC 이니시에이터 포트가 활성화되었고 타겟 포트가 표시되는지 확인합니다.
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2947 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 *ONLINE*
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 *TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 *TARGET DISCSRVC ONLINE*
----
====




== 3단계: 선택적으로 NVMe/FC에 대해 1MB I/O를 활성화합니다.

ONTAP Identify Controller 데이터에서 최대 데이터 전송 크기(MDTS)를 8로 보고합니다.  즉, 최대 I/O 요청 크기는 1MB까지 가능합니다.  Broadcom NVMe/FC 호스트에 대해 1MB 크기의 I/O 요청을 발행하려면 다음을 늘려야 합니다. `lpfc` 의 가치 `lpfc_sg_seg_cnt` 매개변수를 기본값 64에서 256으로 변경합니다.


NOTE: 이 단계는 Qlogic NVMe/FC 호스트에는 적용되지 않습니다.

.단계
.  `lpfc_sg_seg_cnt`매개변수를 256으로 설정합니다.
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
다음 예와 비슷한 출력이 표시되어야 합니다.

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
.  `dracut -f`명령을 실행하고 호스트를 재부팅합니다.
. 의 값이 256인지 `lpfc_sg_seg_cnt` 확인합니다.
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 4단계: 다중 경로 구성 확인

커널 내 NVMe 다중 경로 상태, ANA 상태 및 ONTAP 네임스페이스가 NVMe-oF 구성에 적합한지 확인합니다.

.단계
. in-kernel NVMe multipath가 활성화되어 있는지 확인합니다.
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Y
----
. 각 ONTAP 네임스페이스에 대한 적절한 NVMe-oF 설정(예: NetApp ONTAP 컨트롤러로 설정된 모델 및 라운드 로빈으로 설정된 로드 밸런싱 IPolicy가 호스트에 올바르게 반영되는지 확인합니다.
+
.. 하위 시스템을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 정책을 표시합니다.
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
round-robin
round-robin
----


. 호스트에서 네임스페이스가 생성되고 올바르게 검색되는지 확인합니다.
+
[source, cli]
----
nvme list
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
====
. 각 경로의 컨트롤러 상태가 라이브이고 올바른 ANA 상태인지 확인합니다.
+
[source, cli]
----
nvme list-subsys /dev/nvme0n1
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.ol_157_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
====
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다.
+
[role="tabbed-block"]
====
.열
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/ol_157_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB
----
=====
--
.JSON을 참조하십시오
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.예제 보기
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/ol_157_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----
=====
--
====




== 5단계: 알려진 문제 검토

알려진 문제가 없습니다.
