---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: ONTAP를 사용하여 AIX용 NVMe/FC 호스트를 구성하는 방법 
---
= ONTAP 스토리지를 위한 NVMe-oF로 AIX 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
IBM AIX 및 Virtual I/O Server(VIOS)/PowerVM 호스트는 ANA(Asymmetric Namespace Access)를 갖춘 NVMe/FC 프로토콜을 지원합니다.  ANA는 iSCSI 및 FCP 환경에서 ALUA(비대칭 논리 장치 액세스) 다중 경로와 동일합니다.

지원되는 구성에 대한 추가 세부 사항은 다음을 참조하세요.link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴(IMT)"^] .

.이 작업에 대해
AIX 호스트에 대한 NVMe-oF 호스트 구성과 함께 다음 지원 및 기능을 사용할 수 있습니다.  구성 과정을 시작하기 전에 알려진 제한 사항도 검토해야 합니다.

* 사용 가능한 지원:
+
** ONTAP 9.13.1부터 IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 및 VIOS 3.1.4.21에 대한 NVMe/FC 지원이 추가되었으며, 물리적 스택과 가상 스택 모두에 대한 SAN 부팅이 지원됩니다.  SAN 부팅 지원 설정에 대한 자세한 내용은 IBM 설명서를 참조하세요.
** NVMe/FC는 Power9 및 Power10 IBM 서버에서 지원됩니다.
** AIX SCSI Multipath I/O(MPIO) 지원을 위한 호스트 유틸리티와 같은 별도의 PCM(경로 제어 모듈)은 NVMe 장치에 필요하지 않습니다.
** NetApp(VIOS/PowerVM)의 가상화 지원은 VIOS 3.1.4.21에서 도입되었습니다. Power10 IBM 서버를 사용하는 NPIV(N_PortID Virtualization) 스토리지 가상화 모드를 통해 _OVJIT_SUPPORTED_SUPPORTED입니다.


* 알려진 제한 사항:
+
** AIX 호스트의 Qlogic/Marvel 32G FC HBA는 NVMe/FC를 지원하지 않습니다.
** Power9 IBM 서버를 사용하는 NVMe/FC 장치에서는 SAN 부팅이 지원되지 않습니다.




.시작하기 전에
* 어댑터 펌웨어 12.4.257.30 이상 버전이 있는 32Gb FC Emulex 어댑터(EN1A, EN1B, EN1L, EN1M) 또는 64GB FC 어댑터(EN1N, EN1P)가 있는지 확인합니다.
* MetroCluster 구성을 사용하는 경우 NetApp는 AIX 운영 체제에서 짧은 I/O 시간 초과를 강제로 적용하는 것을 방지하기 위해 MetroCluster 계획되지 않은 전환 이벤트를 지원하기 위해 AIX NVMe/FC 기본 APD(All Path Down) 시간을 변경하는 것이 좋습니다. 추가 정보 및 기본 설정에 대한 권장 변경 사항은 NetApp 온라인 버그 - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* AIX 버전에 따라 AIX 호스트 OS의 ANATT(비대칭 네임스페이스 액세스 전환 시간 초과)는 기본적으로 30초 또는 60초입니다.  호스트의 ANATT 기본값이 30초인 경우 IBM 웹사이트에서 IBM Interim Fix(ifix)를 설치해야 합니다. 이 설치는 ANATT를 60초로 설정하여 모든 ONTAP 워크플로가 중단 없이 진행되도록 합니다.
+
[NOTE]
====
NVMe/FC AIX 지원을 위해서는 AIX OS의 GA 버전에 ifix를 설치해야 합니다.  VIOS/PowerVM OS에는 ifix가 필요하지 않습니다.

이전에 설치된 ifixes가 없는 AIX 버전에 ifixes를 설치해야 합니다. `devices.pciex.pciexclass.010802.rte` 시스템에 대하여.  이전에 설치된 ifix는 새로 설치된 ifix와 충돌할 수 있습니다.

====
+
[role="tabbed-block"]
====
.ANATT를 60초로 설정하세요
--
AIX 레벨 72-TL5-SP6-2320 및 AIX 레벨 73-TL1-SP2-2320 릴리스의 기본 ANATT는 30초입니다.  IBM은 ANATT를 60초로 설정하는 ifix를 제공합니다.  ifix는 IBM 케이스 ID TS018079082를 통해 제공되며 다음 AIX 릴리스에 설치할 수 있습니다.

** AIX 레벨 72-TL5-SP6-2320의 경우 를 설치하십시오 `IJ46710s6a.230509.epkg.Z` 패키지.
** AIX 레벨 73-TL1-SP2-2320의 경우 를 설치합니다 `IJ46711s2a.230509.epkg.Z` 패키지.


--
.기본 ANATT는 60초입니다.
--
다음 AIX 릴리스의 기본 ANATT는 60초입니다.

** AIX 레벨 73-TL2-SP3-2446
** AIX 레벨 73-TL2-SP2-2420
** AIX 레벨 72-TL5-SP8-2420


--
.선택적으로 ANATT를 120초로 설정하세요.
--
IBM은 ANATT를 120초로 설정하는 ifix를 제공합니다.  ANATT를 120초로 설정하면 ONTAP 스토리지 장애 조치 이벤트 중에 성능이 향상됩니다.  ifix는 IBM 케이스 ID TS012877410을 통해 제공되며 다음 AIX 릴리스에 설치할 수 있습니다.

** AIX 레벨 73-TL3-SP0-2446의 경우 다음을 설치하세요. `IJ53487s0a.250130.epkg.Z` 패키지.
** AIX 레벨 72-TL5-SP9-2446의 경우 다음을 설치하세요. `IJ53445s9a.250130.epkg.Z` 패키지.


--
====
+
[NOTE]
====
NVMe/FC를 지원하는 Power9 서버의 최소 서버 펌웨어 버전은 FW 950입니다.

NVMe/FC를 지원하는 Power10 서버의 최소 서버 펌웨어 버전은 FW 1010입니다.

====
+
접미사 관리에 대한 자세한 내용은 을 참조하십시오 link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["AIX에서 중간 수정 관리"^].





== 1단계: 호스트에 대한 다중 경로 구성 확인

AIX OS를 설치하면 NVMe 다중 경로에 사용되는 IBM MPIO가 기본적으로 활성화됩니다.

.단계
. NVMe 다중 경로가 활성화되어 있는지 확인하세요.
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.예제 보기
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== 2단계: NVMe/FC 구성

VIOS의 가상 파이버 채널(vFC)에서 NVMe/FC 프로토콜 지원이 비활성화되어 있으므로 VIOS에서 Broadcom/Emulex 어댑터에 대해 NVMe/FC를 구성해야 합니다.  NVMe/FC 프로토콜 지원은 기본적으로 물리적 FC에서 활성화됩니다.

.단계
. link:https://mysupport.netapp.com/matrix/["지원되는 어댑터를 사용하고 있는지 확인하세요"^] .
. 가상 어댑터 목록을 검색합니다.
+
[source, cli]
----
lsmap -all -npiv
----
+
.예제 보기
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. 를 실행하여 어댑터에서 NVMe/FC 프로토콜 지원을 설정합니다 `ioscli vfcctrl` VIOS의 명령:
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.예제 출력
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. 어댑터에서 지원이 활성화되었는지 확인합니다.
+
[source, cli]
----
lsattr -El vfchost0
----
+
.예제 보기
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. 모든 어댑터에 대해 NVMe/FC 프로토콜을 활성화합니다.
+
.. 를 변경합니다 `dflt_enabl_nvme` 의 속성 값 `viosnpiv0` 의사 디바이스 `yes`.
.. 를 설정합니다 `enable_nvme` 속성 값 `yes` 모든 VFC 호스트 디바이스에 대해
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.예제 보기
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. 를 변경하여 선택한 어댑터에 대해 NVMe/FC 프로토콜을 활성화합니다 `enable_nvme` 에 대한 VFC 호스트 디바이스 속성의 값입니다 `yes`.
. 확인합니다 `FC-NVMe Protocol Device` 이(가) 서버에 생성되었습니다.
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.출력 예
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. 서버에서 호스트 NQN을 기록합니다.
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.예제 보기
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.예제 보기
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. 호스트 NQN을 확인하고 ONTAP 스토리지의 해당 하위 시스템에 대한 호스트 NQN 문자열과 일치하는지 확인합니다.
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.예제 출력
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. 이니시에이터 포트가 실행 중이며 타겟 LIF가 표시되는지 확인합니다.




== 3단계: NVMe/FC 검증

ONTAP 네임스페이스가 NVMe/FC 구성에 맞는지 확인하세요.

.단계
. ONTAP 네임스페이스가 호스트에 올바르게 반영되는지 확인하세요.
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.예제 출력
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. 선택적으로 다중 경로 상태를 확인하세요.
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.예제 보기
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== 4단계: 알려진 문제 검토

ONTAP 스토리지가 있는 AIX의 NVMe/FC 호스트 구성에는 다음과 같은 알려진 문제가 있습니다.

[cols="10,30,30"]
|===
| Burt ID를 참조하십시오 | 제목 | 설명 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | MCC 계획되지 않은 Switchover 이벤트를 지원하기 위해 AIX NVMe/FC 기본 APD 시간을 수정해야 합니다 | 기본적으로 AIX 운영 체제는 NVMe/FC에 대해 모든 경로 다운(APD) 시간 초과 값 20초를 사용합니다.  하지만 ONTAP MetroCluster 자동 비계획 전환(AUSO) 및 Tiebreaker가 시작한 스위치오버 워크플로우가 APD 시간 초과 기간보다 약간 오래 걸릴 수 있으며, 이로 인해 I/O 오류가 발생할 수 있습니다. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC는 ONTAP에서 광고한 120초 대신 60초 이내에 ANATT를 CAP 합니다 | ONTAP는 컨트롤러 ID의 ANA(비대칭 네임스페이스 액세스) 전환 시간 초과를 120초로 알립니다. 현재 ifix를 사용하여 AIX는 컨트롤러에서 ANA 전환 시간 제한을 읽지만, 이 제한을 초과하면 60초로 효과적으로 클램핑합니다. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386)을 참조하십시오"^] | AIX NVMe/FC는 ANATT 만료 후 EIO를 적중합니다 | 스토리지 페일오버(SFO) 이벤트의 경우 ANA(비대칭 네임스페이스 액세스) 전환이 지정된 경로에서 ANA 전환 시간 제한 한도를 초과할 경우, AIX NVMe/FC 호스트는 네임스페이스에 사용할 수 있는 대체 정상 경로가 있더라도 I/O 오류와 함께 실패합니다. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380)을 참조하십시오"^] | AIX NVMe/FC는 ANA ANN 이후 I/O를 재개하기 전에 반/전체 ANATT가 만료될 때까지 대기합니다 | IBM AIX NVMe/FC는 ONTAP가 게시하는 일부 비동기 알림(AIN)을 지원하지 않습니다. 이와 같이 최적화되지 않은 ANA 처리는 SFO 작업 중 성능 저하를 초래합니다. 
|===


== 5단계: 문제 해결

NVMe/FC 오류를 해결하기 전에 다음 사항을 준수하는 구성을 실행하고 있는지 확인하십시오.link:https://mysupport.netapp.com/matrix/["IMT"^] 명세서.  문제가 지속되면 문의하세요.link:https://mysupport.netapp.com["NetApp 지원"^] .
