---
sidebar: sidebar 
permalink: nvme_ol_85.html 
keywords: nvme, linux, oracle, 8.5 
summary: 예를 들어, Oracle Linux 8.5 및 ONTAP용 VME/FC 호스트 구성을 설정합니다 
---
= Oracle Linux 8.5 및 ONTAP용 NVMe/FC 호스트 구성
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== 지원 가능성

NVMe/FC는 Oracle Linux 8.5용 ONTAP 9.6 이상에서 지원됩니다. Oracle Linux 8.5 호스트는 동일한 파이버 채널(FC) 이니시에이터 어댑터 포트를 통해 NVMe/FC와 FCP 트래픽을 모두 실행할 수 있습니다. 를 참조하십시오 link:https://hwu.netapp.com/["Hardware Universe"^] 지원되는 FC 어댑터 및 컨트롤러 목록은 를 참조하십시오. 지원되는 구성의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].


NOTE: 이 컨텐츠에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== 피처

* Oracle Linux 8.5에는 NVMe 네임스페이스에 대해 기본적으로 활성화된 in-kernel NVMe 다중 경로가 있습니다.
* Oracle Linux 8.5를 사용할 경우 기본 NVMe-CLI 패키지에 NVMe-FC 자동 연결 스크립트가 포함되어 있습니다. 따라서 외부 공급업체가 제공한 아웃박스 자동 연결 스크립트를 설치할 필요 없이 이러한 기본 자동 연결 스크립트 자체에 의존할 수 있습니다.
* Oracle Linux 8.5에서는 NVMe 다중 경로에 라운드 로빈 로드 밸런싱을 지원하는 NVMe-CLI 패키지의 일부로 기본 'udev' 규칙이 이미 제공됩니다. 따라서 Oracle Linux 8.1에서와 같이 이 규칙을 수동으로 만들지 않아도 됩니다.
* Oracle Linux 8.5를 사용하면 동일한 기존 호스트에서 NVMe 및 SCSI 트래픽을 모두 실행할 수 있습니다. 실제로 이는 일반적으로 배포되는 호스트 구성일 것으로 예상됩니다. 따라서 SCSI의 경우 mpath 장치를 생성하는 SCSI LUN에 대해 평소처럼 dm-multipath를 구성할 수 있는 반면, NVMe multipath를 사용하여 호스트에 NVMe-of multipath 장치(즉, /dev/nvmeXnY")를 구성할 수 있습니다.
* Oracle Linux 8.5를 사용하는 기본 "NVMe-CLI"의 NetApp 플러그인은 ONTAP 네임스페이스에 대한 ONTAP 세부 정보를 표시할 수 있습니다.




== 알려진 제한 사항

* NVMe/TCP는 기술 미리 보기 기능이므로 IMT에 지원되지 않습니다.
* NVMe/TCP의 스토리지 장애 조치(SFO) 같은 ONTAP 장애 조치 이벤트가 원활하게 진행되도록 하려면 "Ctrl_Loss_TMO" 타이머를 조정하여 30분 등의 더 긴 재시도 기간을 설정하는 것이 좋습니다. 다음 세부 정보를 참조하십시오.




== 구성 요구 사항

을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 지원되는 구성에 대한 자세한 내용은 를 참조하십시오.



== Oracle Linux 8.5를 사용하여 NVMe/FC 활성화

.단계
. 서버에 Oracle Linux 8.5 GA(General Availability)를 설치합니다. 설치가 완료되면 지정된 Oracle Linux 8.5 GA 커널을 실행 중인지 확인합니다. 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 를 참조하십시오.
+
[listing]
----
# uname -r
5.4.17-2136.309.4.el8uek.x86_64
----
. NVMe-CLI 패키지를 설치합니다.
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.14-3.el8.x86_64
----
. Oracle Linux 8.5 호스트에서 '/etc/NVMe/hostnqn'의 hostnqn 문자열을 확인하여 ONTAP 스토리지에 있는 해당 하위 시스템의 hostnqn 문자열과 일치하는지 확인합니다.
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
::> vserver nvme subsystem host show -vserver vs_ol_nvme

Vserver    Subsystem      Host NQN
---------------------------------------------
vs_ol_nvme nvme_ss_ol_1   nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+

NOTE: "hostnqn" 문자열이 일치하지 않으면 "vserver modify" 명령을 사용하여 해당 ONTAP 어레이 하위 시스템의 "hostnqn" 문자열을 호스트의 "hostnqn" 문자열과 일치시키기 위해 해당 어레이 하위 시스템의 "hostnqn" 문자열을 업데이트해야 합니다.

. 호스트를 재부팅합니다.
+
[NOTE]
====
동일한 Oracle Linux 8.5 공동 존재하는 호스트에서 NVMe 및 SCSI 트래픽을 모두 실행하려는 경우 ONTAP 네임스페이스에는 인커널 NVMe 다중 경로, ONTAP LUN에는 dm-multipath를 각각 사용하는 것이 좋습니다. 이는 또한 dm-multipath가 이러한 네임스페이스 장치를 변경하지 못하도록 dm-multipath에 ONTAP 네임스페이스를 블랙리스트에 표시해야 함을 의미합니다. 이렇게 하려면 '/etc/multipath.conf'에 'enable_Foreign' 설정을 추가합니다.

[listing]
----
# cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
====
. 새 설정을 적용하려면 'stemctl restart multipathd'를 실행하여 'multipathd' 데몬을 다시 시작합니다.




=== NVMe/FC용 Broadcom FC 어댑터 구성

.단계
. 지원되는 어댑터를 사용하고 있는지 확인합니다. 지원되는 어댑터의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 권장 Broadcom lpfc 펌웨어 및 받은 편지함 드라이버를 사용하고 있는지 확인합니다. 지원되는 어댑터 드라이버 및 펌웨어 버전의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.0.505.11, sli-4:2:c
14.0.505.11, sli-4:2:c

# cat /sys/module/lpfc/version
0:12.8.0.11
----
. lpfc_enable_fc4_type이 3으로 설정되어 있는지 확인한다
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 이니시에이터 포트가 가동 및 실행 중이며 타겟 LIF를 볼 수 있는지 확인합니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
# cat /sys/class/fc_host/host*/port_state
Online
Online
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----




=== 1MB I/O 크기 활성화

.단계
. lpfc 드라이버가 입출력 요청을 1MB 크기로 이슈하려면 'lpfc_sg_seg_cnt' 매개변수를 256으로 설정해야 합니다.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. dracut -f 명령을 실행한 다음 호스트를 재부팅합니다. 호스트 부팅 후 lpfc_sg_seg_cnt가 256으로 설정되어 있는지 확인합니다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----




== NVMe/FC용 Marvell/QLogic FC 어댑터 구성

.단계
. OL 8.5 GA 커널에 포함된 기본 받은 편지함 qla2xxx 드라이버는 ONTAP 지원에 필수적인 최신 업스트림 픽스를 갖추고 있습니다. 지원되는 어댑터 드라이버 및 펌웨어 버전을 실행하고 있는지 확인합니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
----
. Marvell 어댑터가 NVMe/FC Initiator로 작동하도록 하는 "ql2xnvmeenable"이 설정되어 있는지 확인합니다.
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----




== NVMe/TCP 구성

NVMe/FC와 달리 NVMe/TCP에는 자동 연결 기능이 없습니다. Linux NVMe/TCP 호스트에 대한 두 가지 주요 제한 사항이 반영되어 있습니다.

* 경로가 복구되면 자동 재연결되지 않음 - NVMe/TCP는 경로가 다운된 후 10분 동안 기본 'Ctrl-Loss-TMO'를 벗어나 복원되는 경로에 자동으로 다시 연결할 수 없습니다.
* 호스트 부팅 중에 자동 연결 안 됨 - NVMe/TCP는 호스트 부팅 중에도 자동으로 연결할 수 없습니다.


SFO와 같은 ONTAP 장애 조치 이벤트를 편안하게 넘기 위해서는 Ctrl_Loss_TMO 타이머를 조정하여 30분 등 더 긴 재시도 시간을 설정하는 것이 좋습니다. 다음 지침을 따르십시오.

.단계
. 이니시에이터 포트가 지원되는 NVMe/TCP LIF에서 검색 로그 페이지 데이터를 가져올 수 있는지 확인합니다.
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
Discovery Log Number of Records 10, Generation counter 119
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.2.56
sectype: none
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.1.51
sectype: none
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_2
traddr: 192.168.2.56
sectype: none
...
----
. 마찬가지로, 다른 NVMe/TCP 이니시에이터 타겟 LIF 콤보에서 검색 로그 페이지 데이터를 성공적으로 가져올 수 있는지 확인하십시오. 예를 들면, 다음과 같습니다.
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.52
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.56
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.57
----
. 이제 노드를 통해 지원되는 모든 NVMe/TCP 이니시에이터 타겟 LIF에서 'NVMe connect-all'을 실행하십시오. 'CONNECT-ALL'이 진행되는 동안 'Ctrl_Loss_TMO' 기간(예: 30분, -l 1800'을 통해 설정 가능)을 더 길게 전달하여 경로 손실이 발생할 경우 더 오랜 기간 동안 재시도하도록 해야 합니다. 예를 들면, 다음과 같습니다.
+
[listing]
----
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.51 -l 1800
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.52 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.56 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.57 -l 1800
----




== NVMe/FC 확인 중

.단계
. Oracle Linux 8.5 호스트에서 다음 NVMe/FC 설정을 확인합니다.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. 호스트에서 네임스페이스가 생성되어 제대로 검색되는지 확인합니다.
+
[listing]
----
# nvme list
Node         SN                    Model
---------------------------------------------------------------
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n2 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n3 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller

Namespace Usage  Format                  FW            Rev
--------------------------------------------------------------
1                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
2                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
3                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
----
. 각 경로의 컨트롤러 상태가 라이브이고 적절한 ANA 상태인지 확인합니다
+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_ss_ol_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
----
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다
+
[listing]
----
# nvme netapp ontapdevices -o column
Device       Vserver  Namespace Path
-----------------------------------
/dev/nvme0n1  vs_ol_nvme  /vol/ol_nvme_vol_1_1_0/ol_nvme_ns
/dev/nvme0n2  vs_ol_nvme  /vol/ol_nvme_vol_1_0_0/ol_nvme_ns
/dev/nvme0n3  vs_ol_nvme  /vol/ol_nvme_vol_1_1_1/ol_nvme_ns

NSID    UUID                                   Size
-----------------------------------------------------
1       72b887b1-5fb6-47b8-be0b-33326e2542e2   85.90GB
2       04bf9f6e-9031-40ea-99c7-a1a61b2d7d08   85.90GB
3       264823b1-8e03-4155-80dd-e904237014a4   85.90GB

# nvme netapp ontapdevices -o json
{
"ONTAPdevices" : [
    {
        "Device" : "/dev/nvme0n1",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_1_0/ol_nvme_ns",
        "NSID" : 1,
        "UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
    },
    {
        "Device" : "/dev/nvme0n2",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_0_0/ol_nvme_ns",
        "NSID" : 2,
        "UUID" : "04bf9f6e-9031-40ea-99c7-a1a61b2d7d08",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
      },
      {
         "Device" : "/dev/nvme0n3",
         "Vserver" : "vs_ol_nvme",
         "Namespace_Path" : "/vol/ol_nvme_vol_1_1_1/ol_nvme_ns",
         "NSID" : 3,
         "UUID" : "264823b1-8e03-4155-80dd-e904237014a4",
         "Size" : "85.90GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 20971520
       },
  ]
}
----




== 문제 해결

NVMe/FC 오류에 대한 문제 해결을 시작하기 전에 항상 IMT 사양을 준수하는 구성을 실행 중인지 확인하십시오. 그런 다음 아래의 다음 단계를 진행하여 호스트측 문제를 디버깅합니다.



=== lpfc 세부 정보 로깅

driver/scsi/lpfc/lpfc_logmsg.h에서 볼 수 있는 NVMe/FC에 사용할 수 있는 비트 마스크를 로깅하는 lpfc 드라이버 목록은 다음과 같습니다.

[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
따라서 lpfc 드라이버 관점에서 NVMe/FC 이벤트를 로깅하기 위해 위의 값 중 한 값으로 lpfc_log_verbose 드라이버 설정('/etc/modprobe.d/lpfc.conf'의 lpfc 행에 추가됨)을 설정할 수 있습니다. 그런 다음 dracut-f를 실행하여 initiramfs를 다시 생성한 다음 호스트를 재부팅합니다. 재부팅 후 위의 'log_NVMe_disc bitmask'를 예로 사용하여 상세 로깅이 적용되었는지 확인합니다.

[listing]
----
# cat /etc/modprobe.d/lpfc.conf
lpfc_enable_fc4_type=3 lpfc_log_verbose=0xf00083
# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


=== qla2xxx 세부 정보 로깅

lpfc 드라이버에 대한 NVMe/FC에 대한 유사한 특정 qla2xxx 로깅이 없습니다. 따라서 다음 단계를 사용하여 일반 qla2xxx 로깅 수준을 설정할 수 있습니다.

.단계
. 해당 modprobe qla2xxx conf 파일에 "ql2xextended_error_logging=0x1e400000" 값을 추가합니다.
. dracut -f 명령을 실행하여 initramfs를 재생성한 다음 호스트를 재부팅합니다.
. 재부팅 후 상세 로깅이 다음과 같이 적용되었는지 확인합니다.
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----




=== 일반적인 NVMe-CLI 오류 및 해결 방법

다음 표에는 NVMe 검색, NVMe 연결 또는 NVMe 연결 모든 작업 중에 "NVMe-CLI" 명령으로 표시되는 오류와 해결 방법이 나와 있습니다.

[cols="20, 20, 50"]
|===
| NVMe-CLI에 의해 표시되는 오류 | 가능한 원인 | 해결 방법 


| NVMe 검색, NVMe 연결 또는 NVMe 연결 중 '/dev/NVMe-fabric에 쓸 수 없음: 잘못된 인수' 오류가 표시됩니다 | 구문이 잘못되었습니다 | 지정된 NVMe 명령에 올바른 구문을 사용하고 있는지 확인하십시오. 


| NVMe 검색, NVMe 연결 또는 NVMe 연결 중 '/dev/NVMe-fabric에 쓸 수 없음: 해당 파일이나 디렉토리가 없습니다' 오류가 표시됩니다 | 여러 가지 문제로 인해 이 문제가 발생할 수 있습니다. 일반적인 경우 지정된 NVMe 명령에 잘못된 인수를 전달했습니다.  a| 
* 주어진 명령에 대해 적절한 인수(예: WWNN 문자열, WWPN 문자열 등)를 전달했는지 확인하십시오.
* 인수가 올바르지만 여전히 이 오류가 표시되는 경우 원격 포트 섹션 아래에 NVMe intitator가 "Enabled"로 표시되고 NVMe/FC target LIF가 올바르게 표시되는지 "/sys/class/scsi_host/host * /NVMe_info" 출력이 올바른지 확인하십시오. 예를 들면, 다음과 같습니다.
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* 타겟 LIF가 "NVMe_info" 출력에서 위와 같이 표시되지 않으면 의심되는 NVMe/FC 오류에 대한 '/var/log/' 메시지 및 'dmesg' 출력을 확인하여 그에 따라 보고 또는 수정하십시오.




| NVMe discover, NVMe connect 또는 NVMe connect-all 중에 "가져올 검색 로그 항목 없음" 오류가 표시됩니다 | 이 오류 메시지는 일반적으로 '/etc/NVMe/hostnqn' 문자열이 NetApp 어레이의 해당 하위 시스템에 추가되지 않은 경우에 표시됩니다. 또는 잘못된 "hostnqn" 문자열이 해당 하위 시스템에 추가되었습니다. | 정확한 '/etc/NVMe/hostnqn' 문자열이 NetApp 어레이의 해당 하위 시스템에 추가되었는지 확인합니다('vserver NVMe subsystem host show' 명령을 통해 확인). 


| NVMe 검색, NVMe 연결 또는 NVMe 연결 중 '/dev/NVMe-fabric: Operation already in progress(이미 진행 중인 작업)' 메시지가 표시됩니다 | 이 오류 메시지는 컨트롤러 연결 또는 지정된 작업이 이미 생성되었거나 생성 중인 경우에 표시됩니다. 이 문제는 위에 설치된 자동 연결 스크립트의 일부로 발생할 수 있습니다. | 없음. NVMe 검색의 경우 잠시 후에 이 명령을 실행해 보십시오. NVMe 연결 및 모두 연결 의 경우 "NVMe 목록"을 실행하여 네임스페이스 장치가 이미 생성되어 호스트에 표시되는지 확인하십시오. 
|===


=== 기술 지원 문의 시기

여전히 문제가 발생하는 경우 다음 파일 및 명령 출력을 수집하고 기술 지원 부서에 문의하여 추가 분류를 요청하십시오.

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----


== 알려진 문제 및 해결 방법

없음.
