---
sidebar: sidebar 
permalink: nvme_ol_85.html 
keywords: nvme, linux, oracle, 
summary:  
---
= Oracle Linux 8.5 및 ONTAP용 NVMe/FC 호스트 구성
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== 지원 가능성

NVMe over Fabrics 또는 NVMe-oF(NVMe/FC 및 NVMe/TCP 포함)는 ONTAP 어레이에서 정상 스토리지 페일오버(SFO)에 필요한 ANA(Asymmetric Namespace Access)가 포함된 Oracle Linux 8.5에서 지원됩니다. ANA는 NVMe-oF 환경에 해당하는 비대칭 논리 유닛 액세스(ALUA)이며, 현재 In-kernel NVMe Multipath를 통해 구현되고 있습니다. 이 문서에서는 Oracle Linux 8.5 및 ONTAP에서 ANA를 사용하여 커널 내 NVMe 다중 경로를 사용하여 NVMe-oF를 대상으로 사용하는 방법에 대해 자세히 설명합니다.


NOTE: 이 문서에 제공된 구성 설정을 사용하여 에 연결된 클라우드 클라이언트를 구성할 수 있습니다 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP용 Amazon FSx"^].



== 피처

* Oracle Linux 8.5에는 기본적으로 NVMe namepaces에 대해 활성화된 in-kernel NVMe 다중 경로가 있습니다.
* Oracle Linux 8.5를 사용하는 경우 `nvme-fc auto-connect` 스크립트는 네이티브 에 포함되어 있습니다 `nvme-cli` 패키지. 외부 공급업체가 제공한 아웃박스 자동 연결 스크립트를 설치하는 대신 이러한 기본 자동 연결 스크립트를 사용할 수 있습니다.
* Oracle Linux 8.5는 기본적으로 제공됩니다 `udev` 규칙은 의 일부로 제공됩니다 `nvme-cli` NVMe 다중 경로에 라운드 로빈 로드 밸런싱을 지원하는 패키지 따라서 이 규칙을 더 이상 수동으로 만들 필요가 없습니다.
* Oracle Linux 8.5를 사용하면 동일한 기존 호스트에서 NVMe 및 SCSI 트래픽을 모두 실행할 수 있습니다. 실제로 이는 일반적으로 배포되는 호스트 구성일 것으로 예상됩니다. 따라서 SCSI LUN에 대해 평소처럼 dm-multipath를 구성하여 mpath 장치를 생성할 수 있지만, NVMe 다중 경로를 사용하여 다중 경로 장치의 NVMe-를 구성할 수 있습니다(예: `/dev/nvmeXnY`)를 호스트에 표시합니다.
* Oracle Linux 8.5에서 NetApp 플러그인은 기본적으로 제공됩니다 `nvme-cli` 패키지는 ONTAP 세부 정보 및 ONTAP 네임스페이스를 표시할 수 있습니다.




== 알려진 제한 사항

현재 NVMe-oF 프로토콜을 사용한 SAN 부팅은 지원되지 않습니다.



== 구성 요구 사항

을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 지원되는 구성에 대한 자세한 내용은 를 참조하십시오.



== Oracle Linux 8.5를 사용하여 NVMe/FC를 활성화합니다

.단계
. 서버에 Oracle Linux 8.5 GA(General Availability)를 설치합니다. 설치가 완료되면 지정된 Oracle Linux 8.5 GA 커널을 실행 중인지 확인합니다. 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 를 참조하십시오.
+
[listing]
----
# uname -r
5.4.17-2136.309.4.el8uek.x86_64
----
. NVMe-CLI 패키지를 설치합니다.
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.14-3.el8.x86_64
----
. Oracle Linux 8.5 호스트에서 를 확인합니다 `hostnqn` 에 문자열이 있습니다 `/etc/nvme/hostnqn` 와 일치하는지 확인합니다 `hostnqn` ONTAP 배열의 해당 하위 시스템에 대한 문자열입니다.
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
::> vserver nvme subsystem host show -vserver vs_ol_nvme

Vserver    Subsystem      Host NQN
---------------------------------------------
vs_ol_nvme nvme_ss_ol_1   nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+

NOTE: 를 누릅니다 `hostnqn` 문자열이 일치하지 않습니다. 을 사용해야 합니다 `vserver modify` 명령을 사용하여 를 업데이트합니다 `hostnqn` 에 일치하는 해당 ONTAP 배열 하위 시스템의 문자열입니다 `hostnqn` 문자열 시작 `/etc/nvme/hostnqn` 호스트.

. 호스트를 재부팅합니다.
+
[NOTE]
====
동일한 Oracle Linux 8.5 공동 존재 호스트에서 NVMe와 SCSI 트래픽을 모두 실행하려는 경우, ONTAP 네임스페이스에는 인커널 NVMe 다중 경로, ONTAP LUN에는 dm-multipath를 각각 사용하는 것이 좋습니다. 이는 또한 dm-multipath가 이러한 네임스페이스 장치를 변경하지 못하도록 ONTAP 네임스페이스를 dm-multipath에 블랙리스트에 표시해야 함을 의미합니다. 이 작업은 를 추가하여 수행할 수 있습니다 `enable_foreign` 를 로 설정합니다 `/etc/multipath.conf` 파일:

[listing]
----
#cat /etc/multipath.conf
defaults {
    enable_foreign  NONE
}
----
를 다시 시작합니다 `multipathd` 를 실행하여 데몬으로 이동합니다 `systemctl restart multipathd` 명령을 사용하여 새 설정을 적용합니다.

====




== NVMe/FC용 Broadcom FC 어댑터를 구성합니다

.단계
. 지원되는 어댑터를 사용하고 있는지 확인합니다. 지원되는 어댑터의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 권장 Broadcom lpfc 펌웨어 및 받은 편지함 드라이버를 사용하고 있는지 확인합니다. 지원되는 어댑터 드라이버 및 펌웨어 버전의 최신 목록은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.0.505.11, sli-4:2:c
14.0.505.11, sli-4:2:c

# cat /sys/module/lpfc/version
0:12.8.0.5
----
. 확인합니다 `lpfc_enable_fc4_type` 가 3으로 설정되어 있습니다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 이니시에이터 포트가 가동 및 실행 중인지 확인하고 타겟 LIF를 볼 수 있습니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b213a00
0x100000109b2139ff
# cat /sys/class/fc_host/host*/port_state
Online
Online
# cat /sys/class/scsi_host/host*/nvme_info

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b213a00 WWNN x200000109b213a00 DID x031700     ONLINE
NVME RPORT WWPN x208cd039ea243510 WWNN x208bd039ea243510 DID x03180a TARGET DISCSRVC ONLINE
NVME RPORT WWPN x2090d039ea243510 WWNN x208bd039ea243510 DID x03140a TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 000000000e Cmpl 000000000e Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000079efc Issue 0000000000079eeb OutIO ffffffffffffffef
abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err   00000000
FCP CMPL: xb 00000002 Err 00000004

NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b2139ff WWNN x200000109b2139ff DID x031300 ONLINE
NVME RPORT WWPN x208ed039ea243510 WWNN x208bd039ea243510 DID x03230c TARGET DISCSRVC ONLINE
NVME RPORT WWPN x2092d039ea243510 WWNN x208bd039ea243510 DID x03120c TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 000000000e Cmpl 000000000e Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000029ba0 Issue 0000000000029ba2 OutIO 0000000000000002
abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000002 Err 00000004

----




=== 1MB I/O 크기 활성화

ONTAP는 컨트롤러 식별 데이터에 8의 MDTS(MAX Data 전송 크기)를 보고합니다. 이는 최대 I/O 요청 크기가 1MB가 될 수 있음을 의미합니다. 그러나 Broadcom NVMe/FC 호스트에 대해 1MB의 입출력 요청을 발급하려면 을 늘려야 합니다 `lpfc` 의 값 `lpfc_sg_seg_cnt` 매개 변수를 기본값 64에서 256으로 설정합니다.

.단계
. lpfc_sg_seg_cnt 매개변수를 256으로 설정합니다.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. dracut -f 명령을 실행하고 호스트를 재부팅합니다.
. lpfc_sg_seg_cnt가 256인지 확인합니다.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----



NOTE: Qlogic NVMe/FC 호스트에는 적용되지 않습니다.



== NVMe/FC용으로 Marvell/QLogic FC 어댑터를 구성합니다

.단계
. 지원되는 어댑터 드라이버 및 펌웨어 버전을 실행 중인지 확인합니다. OL 8.5 GA 커널에 포함된 기본 받은 편지함 qla2xxx 드라이버에는 ONTAP 지원에 필수적인 최신 업스트림 픽스가 있습니다.
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
----
. 확인합니다 `ql2xnvmeenable` Marvell 어댑터가 NVMe/FC 이니시에이터로 작동할 수 있도록 설정됩니다.
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----




== NVMe/TCP를 구성합니다

NVMe/TCP에는 자동 연결 기능이 없습니다. 따라서 경로가 10분의 기본 시간 제한 내에 복원되지 않고 다운되면 NVMe/TCP가 자동으로 다시 연결되지 않습니다. 시간 초과를 방지하려면 페일오버 이벤트에 대한 재시도 기간을 최소 30분으로 설정해야 합니다.

.단계
. 이니시에이터 포트가 지원되는 NVMe/TCP LIF에서 검색 로그 페이지 데이터를 가져올 수 있는지 확인합니다.
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
Discovery Log Number of Records 10, Generation counter 119
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.2.56
sectype: none
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.1.51
sectype: none
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_2
traddr: 192.168.2.56
sectype: none

...
----
. 마찬가지로, 다른 NVMe/TCP 이니시에이터-타겟 LIF 조합이 검색 로그 페이지 데이터를 성공적으로 가져올 수 있는지 확인하십시오. 예:
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.52
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.56
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.57
----
. 이제 를 실행합니다 `nvme connect-all` 노드를 통해 지원되는 모든 NVMe/TCP 이니시에이터-타겟 LIF에 대해 명령을 실행합니다. 더 오래 제공해야 합니다 `ctrl_loss_tmo` 타이머 기간(예: 30분, 추가 설정 가능 `-l 1800`)를 참조하십시오 `connect-all` 따라서 경로 손실이 발생할 경우 더 긴 기간 동안 재시도합니다. 예:


[listing]
----
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.51 -l 1800
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.52 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.56 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.57 -l 1800
----


== NVMe/FC를 검증합니다

.단계
. Oracle Linux 8.5 호스트에서 다음 NVMe/FC 설정을 확인하십시오.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. 네임스페이스가 생성되어 호스트에서 올바르게 검색되는지 확인합니다.
+
[listing]
----
# nvme list
Node         SN                    Model
---------------------------------------------------------------
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n2 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n3 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller

Namespace Usage  Format                  FW            Rev
--------------------------------------------------------------
1                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
2                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
3                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
----
. 각 경로의 컨트롤러 상태가 라이브이고 올바른 ANA 상태인지 확인합니다.
+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_ss_ol_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live non-optimized
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live non-optimized
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
----
. NetApp 플러그인에 각 ONTAP 네임스페이스 장치에 대한 올바른 값이 표시되는지 확인합니다.
+
[listing]
----
# nvme netapp ontapdevices -o column
Device       Vserver  Namespace Path
-----------------------------------
/dev/nvme0n1  vs_ol_nvme  /vol/ol_nvme_vol_1_1_0/ol_nvme_ns
/dev/nvme0n2  vs_ol_nvme  /vol/ol_nvme_vol_1_0_0/ol_nvme_ns
/dev/nvme0n3  vs_ol_nvme  /vol/ol_nvme_vol_1_1_1/ol_nvme_ns

NSID    UUID                                   Size
-----------------------------------------------------
1       72b887b1-5fb6-47b8-be0b-33326e2542e2   85.90GB
2       04bf9f6e-9031-40ea-99c7-a1a61b2d7d08   85.90GB
3       264823b1-8e03-4155-80dd-e904237014a4   85.90GB

# nvme netapp ontapdevices -o json
{
"ONTAPdevices" : [
    {
        "Device" : "/dev/nvme0n1",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_1_0/ol_nvme_ns",
        "NSID" : 1,
        "UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
    },
    {
        "Device" : "/dev/nvme0n2",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_0_0/ol_nvme_ns",
        "NSID" : 2,
        "UUID" : "04bf9f6e-9031-40ea-99c7-a1a61b2d7d08",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
      },
      {
         "Device" : "/dev/nvme0n3",
         "Vserver" : "vs_ol_nvme",
         "Namespace_Path" : "/vol/ol_nvme_vol_1_1_1/ol_nvme_ns",
         "NSID" : 3,
         "UUID" : "264823b1-8e03-4155-80dd-e904237014a4",
         "Size" : "85.90GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 20971520
       },
  ]
}
----




== 알려진 문제

OL 8.5 및 ONTAP의 NVMe-oF 호스트 구성에는 다음과 같은 알려진 문제가 있습니다.

[cols=""20"]
|===
| NetApp 버그 ID | 제목 | 설명 | Bugzilla ID입니다 


| 1517321 | Oracle Linux 8.5 NVMe-of 호스트는 중복된 영구 검색 컨트롤러를 만듭니다 | Oracle Linux 8.5 NVMe over Fabrics (NVMe-oF) 호스트에서 를 사용할 수 있습니다 `nvme discover -p` PDC(영구적 검색 컨트롤러)를 생성하는 명령입니다. 이 명령을 사용할 경우 이니시에이터-타겟 조합당 하나의 PDC만 생성해야 합니다. 하지만 ONTAP 9.10.1 및 Oracle Linux 8.5를 NVMe-oF 호스트와 함께 실행하는 경우, 매번 중복 PDC가 생성됩니다 `nvme discover -p` 실행됩니다. 이로 인해 호스트와 타겟 모두에서 리소스가 불필요하게 사용됩니다. | https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=18118["18118"^] 
|===