---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP SAN 호스트 및 클라우드 클라이언트
    url: "/index.html"
  - title: SAN 호스트 구성에 대해 자세히 알아보십시오
    url: "/overview.html"
  - title: SAN Host Utilities를 설치합니다
    entries:
    - title: SAN Host Utilities에 대해 알아보십시오
      url: "/hu_sanhost_index.html"
    - title: AIX 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu-aix-release-notes.html"
      - title: AIX 호스트 유틸리티 설치
        entries:
        - title: AIX 호스트 유틸리티 8.0 설치
          url: "/hu-aix-80.html"
        - title: AIX Host Utilities 7.0을 설치합니다
          url: "/hu-aix-70.html"
        - title: AIX 호스트 유틸리티 6.1 설치
          url: "/hu_aix_61.html"
      - title: AIX SAN Tollkit에 대해 알아보세요
        url: "/hu-aix-san-toolkit.html"
      - title: AIX 호스트 유틸리티 명령 참조
        url: "/hu-aix-command-reference.html"
    - title: HP-UX 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu-hpux-release-notes.html"
      - title: HP-UX Host Utilities 6.0을 설치합니다
        url: "/hu_hpux_60.html"
      - title: SAN 툴킷에 대해 알아보세요
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: HP-UX 명령 참조에 대해 알아보세요
        url: "/hu_hpux_60_cmd.html"
    - title: Linux 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu-luhu-release-notes.html"
      - title: Linux 호스트 유틸리티 설치
        entries:
        - title: Linux Host Utilities 8.0 설치
          url: "/hu-luhu-80.html"
        - title: Linux Host Utilities 7.1을 설치합니다
          url: "/hu_luhu_71.html"
      - title: Sanlun 유틸리티에 대해 알아보세요
        url: "/hu-luhu-sanlun-utility.html"
      - title: Linux 호스트 유틸리티 명령 참조
        url: "/hu-luhu-command-reference.html"
    - title: Solaris 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu-solaris-release-notes.html"
      - title: Solaris 호스트 유틸리티를 설치합니다
        entries:
        - title: Solaris 호스트 유틸리티 8.0 설치
          url: "/hu-solaris-80.html"
        - title: Solaris Host Utilities 6.2 설치
          url: "/hu_solaris_62.html"
      - title: SAN 툴킷에 대해 알아보세요
        url: "/hu-solaris-san-toolkit.html"
      - title: Solaris 명령 참조에 대해 알아보세요
        url: "/hu-solaris-command-reference.html"
    - title: Windows 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu-wuhu-release-notes.html"
      - title: Windows 호스트 유틸리티 설치
        entries:
        - title: Windows Host Utilities 8.0 설치
          url: "/hu-wuhu-80.html"
        - title: Windows Host Utilities 7.2를 설치합니다
          url: "/hu_wuhu_72.html"
        - title: Windows Host Utilities 7.1을 설치합니다
          url: "/hu_wuhu_71.html"
      - title: Windows 호스트 유틸리티에 대한 설정 구성
        url: "/hu_wuhu_hba_settings.html"
      - title: Windows Host Utilities를 업그레이드합니다
        url: "/hu_wuhu_upgrade.html"
      - title: Windows 호스트 유틸리티를 복구 및 제거합니다
        url: "/hu_wuhu_repair_remove.html"
      - title: 문제 해결
        url: "/hu_wuhu_troubleshoot.html"
  - title: FCP 및 iSCSI로 호스트를 구성합니다
    entries:
    - title: 개요
      url: "/hu_fcp_scsi_index.html"
    - title: AIX 및 PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 7.2/3.1
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: 센트OS 8.x
        url: "/hu-centos-8x.html"
      - title: CentOS 7
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: '7.8'
          url: "/hu_centos_78.html"
        - title: '7.7'
          url: "/hu_centos_77.html"
        - title: '7.6'
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: '7.4'
          url: "/hu_centos_74.html"
        - title: '7.3'
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: '7.1'
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6.10'
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: '6.8'
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: '6.6'
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: '6.4'
          url: "/hu_centos_64.html"
    - title: Citrix를 참조하십시오
      entries:
      - title: 젠서버 8.4
        url: "/hu_citrix_84.html"
      - title: 하이퍼바이저 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 및 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX를 참조하십시오
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: ol-FCP
      entries:
      - title: 오라클 리눅스 9.x
        url: "/hu-ol-9x.html"
      - title: 오라클 리눅스 8.x
        url: "/hu-ol-8x.html"
      - title: Oracle Linux 7
        pdf-filename: OL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: '7.8'
          url: "/hu_ol_78.html"
        - title: '7.7'
          url: "/hu_ol_77.html"
        - title: '7.6'
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: '7.4'
          url: "/hu_ol_74.html"
        - title: '7.3'
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: '7.1'
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: Oracle Linux 6
        pdf-filename: ol-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: '6.8'
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: '6.6'
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: '6.4'
          url: "/hu_ol_64.html"
    - title: 프록스목스
      entries:
      - title: 프록스목스 9.0
        url: "/hu-proxmox-9x.html"
    - title: RHEL을 참조하십시오
      entries:
      - title: RHEL 10 를 참조하십시오
        url: "/hu-rhel-10.html"
        pdf-filename: RHEL-10-FCP를 참조하십시오
      - title: RHEL 9.x
        url: "/hu-rhel-9x.html"
        pdf-filename: RHEL-9-FCP
      - title: RHEL 8.x
        pdf-filename: RHEL-8-FCP
        url: "/hu-rhel-8x.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: '7.8'
          url: "/hu_rhel_78.html"
        - title: '7.7'
          url: "/hu_rhel_77.html"
        - title: '7.6'
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: '7.4'
          url: "/hu_rhel_74.html"
        - title: '7.3'
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: '7.1'
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: '6.8'
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: '6.6'
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: '6.4'
          url: "/hu_rhel_64.html"
    - title: 로키 리눅스
      entries:
      - title: 록키 리눅스 10
        pdf-filename: RL-10-FCP를 참조하십시오
        url: "/hu-rockylinux-10.html"
      - title: 로키 리눅스 9.x
        pdf-filename: RL-9-FCP를 참조하십시오
        url: "/hu-rockylinux-9x.html"
      - title: 로키 리눅스 8.x
        pdf-filename: RL-8-FCP를 참조하십시오
        url: "/hu-rockylinux-8x.html"
    - title: Solaris
      entries:
      - title: '11.4'
        url: "/hu-solaris-114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: SLES-15 - FCP
        url: "/hu-sles-15spx.html"
      - title: SUSE Linux Enterprise Server 12
        entries:
        - title: SP 5 12개
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3
          url: "/hu_sles_12SP3.html"
        - title: SP 2 12개
          url: "/hu_sles_12SP2.html"
        - title: SP 1 12개
          url: "/hu_sles_12SP1.html"
        - title: '12'
          url: "/hu_sles_12.html"
    - title: 우분투
      pdf-filename: Ubuntu - FCP
      entries:
      - title: '24.04'
        url: "/hu_ubuntu_2404.html"
      - title: '22.04'
        url: "/hu_ubuntu_2204.html"
      - title: '20.04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: Infoscale 8
        url: "/hu_veritas_8x.html"
      - title: Infoscale 7
        url: "/hu_veritas_7x.html"
      - title: 스토리지 기반 6
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows - FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: 2019년
        url: "/hu_windows_2019.html"
      - title: '2016'
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: NVMe-oF를 사용하여 호스트 구성
    entries:
    - title: NVMe-oF 호스트 구성에 대해 알아보세요
      url: "/hu-nvme-index.html"
    - title: AIX
      url: "/nvme_aix.html"
    - title: ESXi
      pdf-filename: NVMeoF ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme_esxi_8.html"
      - title: VMware vSphere 7
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux
      entries:
      - title: Oracle Linux 9
        pdf-filename: NVMeF OL
        entries:
        - title: '9.5'
          url: "/nvme-ol-95.html"
        - title: 9.4 를 참조하십시오
          url: "/nvme_ol_94.html"
        - title: '9.3'
          url: "/nvme_ol_93.html"
        - title: '9.2'
          url: "/nvme_ol_92.html"
        - title: '9.1'
          url: "/nvme_ol_91.html"
        - title: '9.0'
          url: "/nvme_ol_90.html"
      - title: Oracle Linux 8
        pdf-filename: NVMeF OL
        entries:
        - title: '8.10'
          url: "/nvme-ol-810.html"
        - title: '8.9'
          url: "/nvme_ol_89.html"
        - title: '8.8'
          url: "/nvme_ol_88.html"
        - title: '8.7'
          url: "/nvme_ol_87.html"
        - title: '8.6'
          url: "/nvme_ol_86.html"
        - title: '8.5'
          url: "/nvme_ol_85.html"
        - title: '8.4'
          url: "/nvme_ol_84.html"
        - title: '8.3'
          url: "/nvme_ol_83.html"
        - title: '8.2'
          url: "/nvme_ol_82.html"
        - title: '8.1'
          url: "/nvme_ol_81.html"
      - title: Oracle Linux 7
        entries:
        - title: '7.9'
          url: "/nvme_ol_79.html"
        - title: '7.8'
          url: "/nvme_ol_78.html"
        - title: '7.7'
          url: "/nvme_ol_77.html"
    - title: 프록스목스
      pdf-filename: NVMeoF 프로크스목스
      entries:
      - title: ONTAP 지원 및 기능
        url: "/nvme-proxmox-supported-features.html"
      - title: 프록스목스 VE 9x
        url: "/nvme-proxmox-ve-9x.html"
    - title: RHEL을 참조하십시오
      pdf-filename: RHEL의 NVMeoF
      entries:
      - title: ONTAP 지원 및 기능
        url: "/nvme-rhel-supported-features.html"
      - title: 10x
        url: "/nvme-rhel-10x.html"
      - title: 9x
        url: "/nvme-rhel-9x.html"
      - title: 8x
        url: "/nvme-rhel-8x.html"
    - title: 로키 리눅스
      pdf-filename: NVMeoF Rocky Linux
      entries:
      - title: ONTAP 지원 및 기능
        url: "/nvme-rockylinux-supported-features.html"
      - title: 록키 리눅스 10
        entries:
        - title: '10.0'
          url: "/nvme-rockylinux-10.html"
      - title: 록키 리눅스 9
        entries:
        - title: '9.6'
          url: "/nvme-rockylinux-96.html"
        - title: '9.5'
          url: "/nvme-rockylinux-95.html"
        - title: 9.4 를 참조하십시오
          url: "/nvme-rockylinux-94.html"
        - title: '9.3'
          url: "/nvme-rockylinux-93.html"
        - title: '9.2'
          url: "/nvme-rockylinux-92.html"
        - title: '9.1'
          url: "/nvme-rockylinux-91.html"
        - title: '9.0'
          url: "/nvme-rockylinux-90.html"
      - title: 록키 리눅스 8
        entries:
        - title: '8.10'
          url: "/nvme-rockylinux-810.html"
        - title: '8.9'
          url: "/nvme-rockylinux-89.html"
        - title: '8.8'
          url: "/nvme-rockylinux-88.html"
        - title: '8.7'
          url: "/nvme-rockylinux-87.html"
        - title: '8.6'
          url: "/nvme-rockylinux-86.html"
        - title: '8.5'
          url: "/nvme-rockylinux-85.html"
        - title: '8.4'
          url: "/nvme-rockylinux-84.html"
    - title: SUSE Linux Enterprise Server
      pdf-filename: NVMeSLES
      entries:
      - title: SUSE Linux Enterprise Server 15
        entries:
        - title: 15 SP7입니다
          url: "/nvme_sles15_sp7.html"
        - title: 15 SP6입니다
          url: "/nvme_sles15_sp6.html"
        - title: 15 SP5
          url: "/nvme_sles15_sp5.html"
        - title: 15 SP4
          url: "/nvme_sles15_sp4.html"
        - title: 15 SP3
          url: "/nvme_sles15_sp3.html"
        - title: 15 SP2
          url: "/nvme_sles15_sp2.html"
        - title: 15 SP1
          url: "/nvme_sles15_sp1.html"
    - title: 우분투
      pdf-filename: NVMeoF Ubuntu
      entries:
      - title: '24.04'
        url: "/nvme_ubuntu_2404.html"
      - title: '22.04'
        url: "/nvme_ubuntu_2204.html"
    - title: Windows
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: '2022'
        url: "/nvme_windows_2022.html"
      - title: 2019년
        url: "/nvme_windows_2019.html"
      - title: '2016'
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
    - title: 문제 해결
      url: "/troubleshoot.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
