---
settings:
  name: SAN hosts and cloud clients
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SAN 호스트 및 클라우드 클라이언트를 구성합니다
    url: "/index.html"
  - title: 개요
    url: "/overview.html"
  - title: SAN 호스트 유틸리티를 설치합니다
    entries:
    - title: 개요
      url: "/hu_sanhost_index.html"
    - title: AIX 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu_aix_61_rn.html"
      - title: AIX HU 6.1을 설치합니다
        url: "/hu_aix_61.html"
      - title: 명령 참조 예
        url: "/hu_aix_61_cmd.html"
    - title: HP-UX 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu_hpux_60_rn.html"
      - title: HP-UX HU 6.0을 설치합니다
        url: "/hu_hpux_60.html"
      - title: 명령 참조 예
        url: "/hu_hpux_60_cmd.html"
    - title: Linux Unified Host Utilities를 참조하십시오
      entries:
      - title: 릴리스 정보
        url: "/hu_luhu_71_rn.html"
      - title: LUHU 7.1을 설치합니다
        url: "/hu_luhu_71.html"
      - title: 명령 참조 예
        url: "/hu_luhu_71_cmd.html"
    - title: Solaris 호스트 유틸리티
      entries:
      - title: 릴리스 정보
        url: "/hu_solaris_62_rn.html"
      - title: Solaris HU 6.2를 설치합니다
        url: "/hu_solaris_62.html"
      - title: 명령 참조 예
        url: "/hu_solaris_62_cmd.html"
    - title: Windows Unified Host Utilities를 참조하십시오
      entries:
      - title: 릴리스 정보
        url: "/hu_wuhu_71_rn.html"
      - title: Wuhu 7.2를 설치합니다
        url: "/hu_wuhu_72.html"
      - title: Wuhu 7.1을 설치합니다
        url: "/hu_wuhu_71.html"
      - title: Wuhu를 업그레이드하세요
        url: "/hu_wuhu_upgrade.html"
      - title: Wuhu 수리 및 제거
        url: "/hu_wuhu_repair_remove.html"
      - title: 레지스트리 설정을 구성합니다
        url: "/hu_wuhu_hba_settings.html"
      - title: 문제 해결
        url: "/hu_wuhu_troubleshoot.html"
  - title: FCP 및 iSCSI로 호스트를 구성합니다
    entries:
    - title: 개요
      url: "/hu_fcp_scsi_index.html"
    - title: AIX 및 PowerVM/VIOS
      entries:
      - title: 7.2/3.1
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: 릴리스 정보
        url: "/hu_centos_asm_release_notes.html"
      - title: CentOS 8
        entries:
        - title: '8.5'
          url: "/hu_centos_85.html"
        - title: '8.4'
          url: "/hu_centos_84.html"
        - title: '8.3'
          url: "/hu_centos_83.html"
        - title: '8.2'
          url: "/hu_centos_82.html"
        - title: '8.1'
          url: "/hu_centos_81.html"
        - title: '8.0'
          url: "/hu_centos_80.html"
      - title: CentOS 7
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: '7.8'
          url: "/hu_centos_78.html"
        - title: '7.7'
          url: "/hu_centos_77.html"
        - title: '7.6'
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: '7.4'
          url: "/hu_centos_74.html"
        - title: '7.3'
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: '7.1'
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6.10'
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: '6.8'
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: '6.6'
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: '6.4'
          url: "/hu_centos_64.html"
    - title: Citrix를 참조하십시오
      entries:
      - title: 하이퍼바이저 8
        url: "/hu_citrix_8x.html"
      - title: XenServer 7을 참조하십시오
        url: "/hu_citrix_7x.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 및 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX를 참조하십시오
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: ol-FCP
      entries:
      - title: 릴리스 정보
        url: "/hu_ol_asm_release_notes.html"
      - title: 열 9
        entries:
        - title: '9.2'
          url: "/hu_ol_92.html"
        - title: '9.1'
          url: "/hu_ol_91.html"
        - title: '9.0'
          url: "/hu_ol_90.html"
      - title: 열 8
        pdf-filename: ol-8-FCP
        entries:
        - title: '8.8'
          url: "/hu_ol_88.html"
        - title: '8.7'
          url: "/hu_ol_87.html"
        - title: '8.6'
          url: "/hu_ol_86.html"
        - title: '8.5'
          url: "/hu_ol_85.html"
        - title: '8.4'
          url: "/hu_ol_84.html"
        - title: '8.3'
          url: "/hu_ol_83.html"
        - title: '8.2'
          url: "/hu_ol_82.html"
        - title: '8.1'
          url: "/hu_ol_81.html"
        - title: '8.0'
          url: "/hu_ol_80.html"
      - title: 열 7
        pdf-filename: OL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: '7.8'
          url: "/hu_ol_78.html"
        - title: '7.7'
          url: "/hu_ol_77.html"
        - title: '7.6'
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: '7.4'
          url: "/hu_ol_74.html"
        - title: '7.3'
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: '7.1'
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: 열 6
        pdf-filename: ol-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: '6.8'
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: '6.6'
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: '6.4'
          url: "/hu_ol_64.html"
    - title: RHEL을 참조하십시오
      entries:
      - title: 릴리스 정보
        url: "/hu_rhel_asm_release_notes.html"
      - title: RHEL 9
        pdf-filename: RHEL-9-FCP
        entries:
        - title: '9.3'
          url: "/hu_rhel_93.html"
        - title: '9.2'
          url: "/hu_rhel_92.html"
        - title: '9.1'
          url: "/hu_rhel_91.html"
        - title: '9.0'
          url: "/hu_rhel_90.html"
      - title: RHEL 8
        pdf-filename: RHEL-8-FCP
        entries:
        - title: '8.9'
          url: "/hu_rhel_89.html"
        - title: '8.8'
          url: "/hu_rhel_88.html"
        - title: '8.7'
          url: "/hu_rhel_87.html"
        - title: '8.6'
          url: "/hu_rhel_86.html"
        - title: '8.5'
          url: "/hu_rhel_85.html"
        - title: '8.4'
          url: "/hu_rhel_84.html"
        - title: '8.3'
          url: "/hu_rhel_83.html"
        - title: '8.2'
          url: "/hu_rhel_82.html"
        - title: '8.1'
          url: "/hu_rhel_81.html"
        - title: '8.0'
          url: "/hu_rhel_80.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: '7.8'
          url: "/hu_rhel_78.html"
        - title: '7.7'
          url: "/hu_rhel_77.html"
        - title: '7.6'
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: '7.4'
          url: "/hu_rhel_74.html"
        - title: '7.3'
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: '7.1'
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: '6.8'
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: '6.6'
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: '6.4'
          url: "/hu_rhel_64.html"
    - title: Solaris
      entries:
      - title: '11.4'
        url: "/hu_solaris_114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SLES
      entries:
      - title: 릴리스 정보
        url: "/hu_sles_asm_release_notes.html"
      - title: SLES 15
        pdf-filename: SLES-15 - FCP
        entries:
        - title: 15 SP5
          url: "/hu_sles_15SP5.html"
        - title: 15 SP4
          url: "/hu_sles_15SP4.html"
        - title: 15 SP3
          url: "/hu_sles_15SP3.html"
        - title: 15 SP2
          url: "/hu_sles_15SP2.html"
        - title: 15 SP1
          url: "/hu_sles_15SP1.html"
        - title: '15'
          url: "/hu_sles_15.html"
      - title: SLES 12
        entries:
        - title: SP 5 12개
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3
          url: "/hu_sles_12SP3.html"
        - title: SP 2 12개
          url: "/hu_sles_12SP2.html"
        - title: SP 1 12개
          url: "/hu_sles_12SP1.html"
        - title: '12'
          url: "/hu_sles_12.html"
    - title: 우분투
      pdf-filename: Ubuntu - FCP
      entries:
      - title: '20.04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: Infoscale 8
        url: "/hu_veritas_8x.html"
      - title: Infoscale 7
        url: "/hu_veritas_7x.html"
      - title: 스토리지 기반 6
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows - FCP
      entries:
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: 2019년
        url: "/hu_windows_2019.html"
      - title: '2016'
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: NVMe-oF를 사용하여 호스트 구성
    entries:
    - title: 개요
      url: "/hu_nvme_index.html"
    - title: AIX
      url: "/nvme_aix.html"
    - title: ESXi
      pdf-filename: NVMeoF ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme_esxi_8.html"
      - title: VMware vSphere 7
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux
      entries:
      - title: 열 9
        pdf-filename: NVMeF OL
        entries:
        - title: '9.2'
          url: "/nvme_ol_92.html"
        - title: '9.1'
          url: "/nvme_ol_91.html"
        - title: '9.0'
          url: "/nvme_ol_90.html"
      - title: 열 8
        pdf-filename: NVMeF OL
        entries:
        - title: '8.8'
          url: "/nvme_ol_88.html"
        - title: '8.7'
          url: "/nvme_ol_87.html"
        - title: '8.6'
          url: "/nvme_ol_86.html"
        - title: '8.5'
          url: "/nvme_ol_85.html"
        - title: '8.4'
          url: "/nvme_ol_84.html"
        - title: '8.3'
          url: "/nvme_ol_83.html"
        - title: '8.2'
          url: "/nvme_ol_82.html"
        - title: '8.1'
          url: "/nvme_ol_81.html"
      - title: 열 7
        entries:
        - title: '7.9'
          url: "/nvme_ol_79.html"
        - title: '7.8'
          url: "/nvme_ol_78.html"
        - title: '7.7'
          url: "/nvme_ol_77.html"
    - title: RHEL을 참조하십시오
      pdf-filename: RHEL의 NVMeoF
      entries:
      - title: RHEL 9
        entries:
        - title: '9.3'
          url: "/nvme_rhel_93.html"
        - title: '9.2'
          url: "/nvme_rhel_92.html"
        - title: '9.1'
          url: "/nvme_rhel_91.html"
        - title: '9.0'
          url: "/nvme_rhel_90.html"
      - title: RHEL 8
        entries:
        - title: '8.9'
          url: "/nvme_rhel_89.html"
        - title: '8.8'
          url: "/nvme_rhel_88.html"
        - title: '8.7'
          url: "/nvme_rhel_87.html"
        - title: '8.6'
          url: "/nvme_rhel_86.html"
        - title: '8.5'
          url: "/nvme_rhel_85.html"
        - title: '8.4'
          url: "/nvme_rhel_84.html"
        - title: '8.3'
          url: "/nvme_rhel_83.html"
        - title: '8.2'
          url: "/nvme_rhel_82.html"
        - title: '8.1'
          url: "/nvme_rhel_81.html"
    - title: SLES
      pdf-filename: NVMeSLES
      entries:
      - title: SLES 15
        entries:
        - title: 15 SP5
          url: "/nvme_sles15_sp5.html"
        - title: 15 SP4
          url: "/nvme_sles15_sp4.html"
        - title: 15 SP3
          url: "/nvme_sles15_sp3.html"
        - title: 15 SP2
          url: "/nvme_sles15_sp2.html"
        - title: 15 SP1
          url: "/nvme_sles15_sp1.html"
    - title: Windows
      entries:
      - title: '2022'
        url: "/nvme_windows_2022.html"
      - title: 2019년
        url: "/nvme_windows_2019.html"
      - title: '2016'
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
    - title: 문제 해결
      url: "/troubleshoot.html"
  - title: 법적 고지
    url: "/legal_notice.html"
product-family:
  name: ONTAP
  repo: ontap-family
