= 1단계: 필요에 따라 SAN 부팅을 활성화합니다
:allow-uri-read: 




== 1단계: 필요에 따라 SAN 부팅을 활성화합니다

SAN 부팅을 사용하도록 호스트를 구성하여 배포를 간소화하고 확장성을 개선할 수 있습니다.  구성이 SAN 부팅을 지원하지 않으면 로컬 부팅을 사용할 수 있습니다.

[role="tabbed-block"]
====
.SAN 부팅
--
SAN 부팅은 AIX/PowerVM 호스트 호스트의 부팅 장치로 SAN에 연결된 디스크(LUN)를 설정하는 프로세스입니다.  FC 프로토콜을 사용하고 FC 또는 FCoE 프로토콜로 AIX 호스트 유틸리티를 실행하는 AIX Multipath I/O(MPIO) 환경에서 작동하도록 SAN 부팅 LUN을 설정할 수 있습니다.  AIX MPIO 환경에서 SAN 부팅 LUN을 생성하고 새 OS 이미지를 설치하는 데 사용하는 방법은 사용하는 프로토콜에 따라 달라집니다.


NOTE: AIX에서는 MPIO가 활성화될 때까지 SAN 부팅 디스크에 하나의 경로만 표시되도록 요구합니다. AIX 부팅 디스크를 설치하거나 마이그레이션할 때는 일반적으로 호스트의 FC 영역 설정을 일시적으로 제한하여 FC 이니시에이터 하나와 FC 타겟 하나만 포함하도록 해야 합니다. 호스트 유틸리티(PCM 패키지 포함)를 설치한 후 운영 체제를 재부팅하면 MPIO를 완전히 활성화할 수 있습니다. 재부팅 후 추가 FC 이니시에이터와 FC 타겟을 영역에 추가합니다. 그런 다음,  `cfgmgr -v` 및  `bosboot -a`을 실행하여 사용 가능한 모든 경로를 포함하도록 부팅 구성을 업데이트합니다.

.단계
. 사용하세요link:https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 툴"^] AIX OS, 프로토콜 및 ONTAP 버전이 SAN 부팅을 지원하는지 확인하세요.
. 공급업체 설명서에서 SAN 부팅을 설정하는 모범 사례를 따르세요.


--
.로컬 부팅
--
예를 들어 SSD, SATA 또는 RAID 등 로컬 하드 디스크에 AIX OS를 설치하여 로컬 부팅을 수행합니다.

--
====