= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Oracle Linux 호스트
--
호스트에 대해 다중 경로가 올바르게 구성되었는지 확인하려면 `/etc/multipath.conf`이(가) 정의되어 있고 ONTAP LUN에 대해 NetApp 권장 설정이 구성되어 있는지 확인하십시오.

.단계
.  `/etc/multipath.conf` 파일이 있는지 확인합니다. 파일이 없으면 비어 있는 0바이트 파일을 생성합니다.
+
[source, cli]
----
touch /etc/multipath.conf
----
. 파일을 처음 생성할 때 `multipath.conf` 권장 설정을 로드하려면 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. 호스트를 부팅할 때마다 빈 0바이트 파일이 `/etc/multipath.conf` NetApp 권장 호스트 다중 경로 매개 변수를 기본 설정으로 자동으로 로드합니다. 운영 체제는 ONTAP LUN을 올바르게 인식하고 관리하는 다중 경로 매개 변수를 사용하여 컴파일되므로 호스트의 파일을 변경할 필요가 없습니다 `/etc/multipath.conf`.
+
다음 표는 ONTAP LUN에 대한 네이티브 Linux 운영 체제 컴파일 다중 경로 매개 변수 설정을 보여줍니다.

+
.매개 변수 설정을 표시합니다
[#multipath-parameter-settings%collapsible]
=====
[cols="2"]
|===
| 매개 변수 | 설정 


| detect_prio(사전 감지) | 예 


| DEV_Loss_TMO | "무한대" 


| 장애 복구 | 즉시 


| Fast_IO_FAIL_TMO | 5 


| 피처 | "2 pg_init_retries 50" 


| Flush_on_last_del.(마지막 삭제 시 플러시 | "예" 


| hardware_handler를 선택합니다 | "0" 


| no_path_retry 를 선택합니다 | 대기열 


| path_checker를 선택합니다 | "tur" 


| path_grouping_policy | "group_by_prio(그룹 기준/원시)" 


| 경로 선택 | "서비스 시간 0" 


| polling_interval입니다 | 5 


| 프리오 | "ONTAP" 


| 제품 | LUN입니다 


| Retain_attached_hw_handler 를 참조하십시오 | 예 


| RR_WEIGHT | "균일" 


| 사용자_친화적_이름 | 아니요 


| 공급업체 | 넷엡 
|===
=====
. ONTAP LUN의 매개 변수 설정 및 경로 상태를 확인합니다.
+
[source, cli]
----
multipath -ll
----
+
기본 다중 경로 매개변수는 ASA, AFF 및 FAS 구성을 지원합니다. 이러한 구성에서는 단일 ONTAP LUN에 4개 이상의 경로가 필요하지 않습니다. 경로가 4개 이상이면 저장소 오류 발생 시 문제가 발생할 수 있습니다.

+
다음 출력 예는 ASA, AFF 또는 FAS 구성에 있는 ONTAP LUN에 대한 올바른 매개 변수 설정 및 경로 상태를 보여줍니다.

+
*ASA 구성*

+
ASA 구성은 지정된 LUN에 대한 모든 경로를 최적화하여 활성 상태를 유지합니다. 그 결과, 모든 경로를 통해 I/O 작업을 동시에 처리함으로써 성능이 향상됩니다.

+
.예제 보기
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
=====
+
*AFF 또는 FAS 구성*

+
AFF 또는 FAS 구성에는 우선 순위가 높거나 낮은 두 개의 경로 그룹이 있어야 합니다. 우선 순위가 더 높은 활성/최적화 경로는 애그리게이트가 위치한 컨트롤러에서 제공합니다. 낮은 우선 순위 경로는 다른 컨트롤러에서 제공되기 때문에 활성 상태이지만 최적화되지 않습니다. 최적화되지 않은 경로는 최적화 경로를 사용할 수 없는 경우에만 사용됩니다.

+
다음 예에서는 활성/최적화 경로 2개와 활성/최적화되지 않은 경로 2개가 있는 ONTAP LUN에 대한 출력을 표시합니다.

+
.예제 보기
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
.OLVM - ONTAP HA
--
Oracle Linux Virtualization Manager(OLVM)에서 VDSM 데몬은 하이퍼바이저의 기본 다중 경로 매개 변수를 제어합니다.  `/etc/multipath.conf`을(를) 직접 편집하지 마십시오. 대신 다중 경로 드롭인 파일을 사용하여 기본값을 재정의하십시오.

ONTAP 고가용성(HA) 구성의 경우 NetApp에서는 다음 드롭인 파일을 사용하여  `dev_loss_tmo` 및  `no_path_retry`를 재정의할 것을 권장합니다. 다른 모든 다중 경로 매개변수는 Oracle Linux 호스트 매개변수 설정 표의 설정과 일치해야 합니다.

.단계
. 드롭인 파일을 생성합니다.
+
[source, cli]
----
cat <<'EOF' > /etc/multipath/conf.d/ontap-ha-mpath-netapp.conf
# Finite multipath retry window aligned with sanlock io_timeout
# default sanlock:io_timeout=10s, polling_interval=5s => no_path_retry = (8*10)/5 = 16

devices {
  device {
    vendor "NETAPP"
    product "LUN"
    no_path_retry 16
    dev_loss_tmo "infinity"
  }
}
EOF
----
. 다중 경로 데몬을 다시 로드합니다.
+
[source, cli]
----
systemctl reload multipathd
----
. 업데이트된 다중 경로 구성을 확인합니다.
+
[source, cli]
----
multipathd -k"show config"
----


--
.OLVM - ONTAP SnapMirror 액티브 동기화
--
Oracle Linux Virtualization Manager(OLVM)에서 VDSM 데몬은 하이퍼바이저의 기본 다중 경로 매개 변수를 제어합니다.  `/etc/multipath.conf`을(를) 직접 편집하지 마십시오. 대신 다중 경로 드롭인 파일을 사용하여 기본값을 재정의하십시오.

OLVM 호스트에서 ONTAP SnapMirror active sync를 사용하는 경우, 스토리지 페일오버 이벤트 발생 시 호스트 및 VM의 올바른 동작을 보장하기 위해 sanlock 및 다중 경로 시간 초과 매개 변수를 조정해야 합니다. 기본 OLVM 시간 초과 값은 다중 경로 복구가 완료되기 전에 임대 갱신 기간이 만료될 수 있으므로, 계획되지 않은 사이트 페일오버 중에 의도하지 않은 고가용성 VM 페일오버를 유발할 수 있습니다.

NetApp 기술 자료 문서 https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Oracle_Linux_Virtualization_Manager_-_Sanlock_Settings_for_ONTAP_SnapMirror_Active_Sync["Oracle Linux Virtualization Manager - ONTAP SnapMirror Active Sync용 Sanlock 설정"]에 나와 있는 구성 단계를 따라 sanlock 및 다중 경로 시간 초과 값을 업데이트하여 스토리지 페일오버 이벤트 중에 다중 경로 복구가 완료될 수 있도록 임대 갱신 기간이 충분히 확보되도록 하십시오.

--
====