= 
:allow-uri-read: 


* 를 클릭합니다 `multipath.conf` 다중 경로 데몬을 시작하려면 파일이 있어야 하지만 다음 명령을 사용하여 빈 0바이트 파일을 생성할 수 있습니다.
`touch /etc/multipath.conf`.
* 이 파일을 처음 생성할 때 다중 경로 서비스를 활성화하고 시작해야 할 수 있습니다.


[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
* 에 직접 추가할 필요는 없습니다 `multipath.conf` 파일 - 다중 경로를 관리하지 않으려는 장치가 있거나 기본값을 덮어쓰는 기존 설정이 없는 경우
* 다음 구문을 'multitpath.conf' 파일에 추가하여 원치 않는 디바이스를 제외할 수 있습니다.
* <DevId>를 제외할 장치의 WWID 문자열로 바꿉니다.


....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.예
이 예에서는 `sda` 블랙리스트에 추가해야 하는 로컬 SCSI 디스크입니다.

. 다음 명령을 실행하여 WWID를 확인하십시오.
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. 이 WWID를 /etc/multipath.conf의 "blacklist" 스탠자에 추가합니다.
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


을 항상 확인해야 합니다 `/etc/multipath.conf` 기본 설정을 재정의할 수 있는 레거시 설정 파일, 특히 기본값 섹션에 있는 파일입니다.

다음 표에서는 위험 요소를 보여 줍니다 `multipathd` ONTAP LUN에 대한 매개 변수 및 필수 값입니다. 호스트가 다른 공급업체의 LUN에 연결되어 있고 이러한 매개 변수 중 하나라도 재정의되면 에서 나중에 Stanzas를 통해 수정해야 합니다 `multipath.conf` ONTAP LUN에 특별히 적용되는 파일입니다. 그렇지 않으면 ONTAP LUN이 예상대로 작동하지 않을 수 있습니다. 이러한 기본값은 NetApp 및/또는 OS 공급업체와 협의하여 완전히 이해될 때만 재정의해야 합니다.
