= 
:allow-uri-read: 


GRUB 부팅 로더를 사용하여 Linux 게스트 운영 체제에서 MBR을 PowerShell Toolkit과 일치시킬 수 있도록 디스크에 대한 'bralign'을 실행한 후 게스트 운영 체제가 올바르게 부팅되도록 GRUB를 다시 설치해야 합니다.

.이 작업에 대해
가상 머신에 대한 VHD 파일에서 PowerShell Toolkit cmdlet을 완료했습니다. 이 절차는 GRUB 부팅 Loader 및 를 사용하는 Linux 게스트 운영 체제에만 `SystemRescueCd` 적용됩니다.

.단계
. 설치 CD의 디스크 1의 ISO 이미지를 마운트하여 가상 시스템에 맞는 Linux 버전을 만듭니다.
. Hyper-V Manager에서 가상 머신의 콘솔을 엽니다.
. VM이 실행 중이고 GRUB 화면에서 정지된 경우 표시 영역을 클릭하여 활성 상태인지 확인한 다음 * Ctrl-Alt-Delete * 도구 모음 아이콘을 선택하여 VM을 재부팅합니다. VM이 실행되고 있지 않으면 VM을 시작한 다음 표시 영역을 즉시 클릭하여 활성 상태인지 확인합니다.
. VMware BIOS 시작 화면이 나타나면 * Esc * 키를 한 번 누릅니다. 부팅 메뉴가 표시됩니다.
. 부팅 메뉴에서 * CD-ROM * 을 선택합니다.
. Linux 부팅 화면에서 '리눅스 구조'를 입력합니다
. Anaconda(파란색/빨간색 구성 화면)의 기본값을 사용합니다. 네트워킹은 선택 사항입니다.
. grub을 입력하여 GRUB를 실행한다
. 이 VM에 가상 디스크가 하나만 있거나 디스크가 여러 개 있고 첫 번째 디스크가 부팅 디스크인 경우 다음 GRUB 명령을 실행합니다.
+
[listing]
----
root (hd0,0)
setup (hd0)
quit
----
+
VM에 여러 개의 가상 디스크가 있고 부팅 디스크가 첫 번째 디스크가 아니거나 잘못 정렬된 백업 VHD에서 부팅하여 GRUB를 수정하는 경우 다음 명령을 입력하여 부팅 디스크를 식별합니다.

+
[listing]
----
find /boot/grub/stage1
----
+
그런 다음 다음 다음 명령을 실행합니다.

+
[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----
+

NOTE: 에서 `setup (boot_disk)` `boot_disk` 는 부팅 디스크의 실제 디스크 식별자에 대한 자리 표시자입니다.



. 로그아웃하려면 * Ctrl-D * 를 누릅니다.
+
Linux Rescue가 종료된 후 재부팅됩니다.


